### ISSUE TITLE
Additional Fields - Staff Teaching a Module (INSTANCE)

### ISSUE THREAD

**Issue by robwynj** [jiscdev/analytics-udd#10]
Do we need to include any further fields, as part of UDD 1.2, in the additional data elements which link to the core predictive data/ UDD model, **specifically for STAFF**? 

Might be worth putting in (some of) the following, or will SSP be relying on pulling this data from/ via authentication with central institution systems. Maybe worth consulting with Steve Cody @ UNICON to confirm what fields are required? AND also relevant for Tribal / Student Insight config.

STAFF_ID **(ALREADY CATERED FOR)**
STAFF_USERNAME
STAFF_FIRST_NAME
STAFF_LAST_NAME
STAFF_PRIMARY_EMAIL_ADDRESS
STAFF_HOME_PHONE
STAFF_MOBILE_PHONE
STAFF_PHOTO_URL

Kind Regards,

Rob

**Comment by arc12** [comment]
Rob - 

linking staff to students and module-instances is important for Tribal, for configuring the Student Insight application (AFAIK we won't touch these for prediction; its a very sensitive area). We'll feed in our analysis of requirements ...

**Comment by robwynj** [comment]
Agreed, for both sides of the fence - let us know so we can implement in consultation with you and UNICON :)

Kind Regards

Rob

**Comment by robwynj** [comment]
Also need to identify those which are mandatory and optional of course. Have also contacted UNICON now to this effect.

**Comment by wilmTap** [comment]
Addressed in #27
