### ISSUE TITLE
student on course/module/assessment instance does not specify what the unique index is

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#104]
It would he helpful for this to be explicit, so that correct choices are made for validation and joining

We think:
STUDENT_ON_COURSE_INSTANCE:
PK is a composite: ['STUDENT_COURSE_MEMBERSHIP_ID',  'STUDENT_COURSE_MEMBERSHIP_SEQ', 'COURSE_INSTANCE_ID']

STUDENT_ON_MODULE_INSTANCE
PK is a composite: ['STUDENT_COURSE_MEMBERSHIP_ID',  'STUDENT_COURSE_MEMBERSHIP_SEQ', 'COURSE_INSTANCE_ID', 'MOD_INSTANCE_ID']

STUDENT_ON_ASSESSMENT_INSTANCE
PK is a composite: ['STUDENT_COURSE_MEMBERSHIP_ID',  'STUDENT_COURSE_MEMBERSHIP_SEQ', 'ASSESS_INSTANCE_ID', 'ASSESS_SEQ_ID'

Note that in all cases the reference to SCM is 'STUDENT_COURSE_MEMBERSHIP_ID' and 'STUDENT_COURSE_MEMBERSHIP_SEQ' combined, since these comprise the composite PK for SCM.

There are also a few entities where the ID field is described as e.g. "the institution's own identifier" while many include the word "unique". It would be good to avoid ambiguity IMO.

Adam

**Comment by wilmTap** [comment]
Would it help if we defined a dedicated single value primary key for each of these entities?

In a surplus of consistency, I suppose we could also define PKs for staff_on_course_instance and staff_on_mod_instance.

Since it's a documentation change, do we want to roll it into v1.2.6 or v.1.2.7?

**Comment by wilmTap** [comment]
Document the composite PKs clearly
