### ISSUE TITLE
Period reference data

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#105]
Issue: while it may be possible to infer start and end dates for academic years from course and module instance data, this may not be reliable. Institutional users will have very clear ideas about periods and it is important our dashboards and data matches. A particular area of difficulty is likely to be in dealing with activity data: ensuring this is correctly matched to UDD instances.

We anticipate SRSs contain definitive start and end dates for academic years, and periods such as terms/semesters.

Propose: we scope out some simple requirements for an added entity in UDD for a future (>1.2) version.

**Comment by wilmTap** [comment]
Is the connection between a period and module and course instances reliable coming from the period data? Also, do all, most or some institutions have solid sources for that period data?

**Comment by wilmTap** [comment]
Having pondered this one for a bit, I've sketched out the following for v1.2.7:
One new year_academic entity (to distinguish the new entity from the existing property), and one new period entity. year_academic has a composite key of ACADEMIC_YEAR and TENANT_ID, period one of MOD_PERIOD, assuming that the latter can be used as the foreign key from module_instance. Feedback on that assumption would be welcome.

This would require the addition of ACADEMIC_YEAR to module_instance, and after v1.3, MOD_ACADEMIC_YEAR could be dropped.

The attached illustrates:
![proposedacademicyear1_2_7](https://cloud.githubusercontent.com/assets/689398/18437359/78b5a342-78f4-11e6-8d05-dbf2f7c40c1d.png)

**Comment by wilmTap** [comment]
Change column names, and take it off v1.2.7

**Comment by arc12** [comment]
Could we put this on the roadmap for 1.3

I have an alternative formulation which keeps the period reference data a bit more detached from the relational structure.
- no change to current AY fields
- periods reference data can be typed so it can cover both academic years and semesters/terms (for mod_period), and used for others as required in the future
- no crows feet

**Comment by arc12** [comment]
could we label this for 1.3 please

**Comment by alanepaull** [comment]
@arc12: you mentioned an 'alternative formulation' for this.  Could you put a bit more on the bones of your bullets above?  I don't quite "get it" yet.

**Comment by arc12** [comment]
OK... to be less elliptical!

PERIODS entity
has attributes (all required):
PERIOD_ID - string label for the period
PERIOD_TYPE - string code list with initial values 'ACADEMIC_YEAR' or 'MOD_PERIOD'
PERIOD_START_DATE - string in format YYYY-MM-DD
PERIOD_END_DATE

PERIOD_TYPE indicates the attribute in UDD to which PERIOD_ID pertains.

The slight wrinkle with this is that academic years are integers in UDD but module periods are strings.

Adam

**Comment by alanepaull** [comment]
From Monday 5 Dec call:

Implement on the basis of @arc12's suggestion.

**Comment by alanepaull** [comment]
I'm looking at a couple of possible solutions to this issue.

One is (as @wilmTap suggests above) to tie the PERIODS entity into the UDD structure in multiple places.  For example, linking PERIODS with COURSE_INSTANCE as well as INSTITUTION, because COURSE_INSTANCE uses the academic_year property.

However, this is not the only possible approach.  An alternative would be to provide a PERIODS entity that simply links to INSTITUTION as a look-up, without an explicit link to other tables.  This avoids possible issues, such as MODULE_INSTANCE, which has both mod_period and mod_academic_year.

Which approach is more helpful?

**Comment by alanepaull** [comment]
The addition of PERIOD may affect:

course_instance (ACADEMIC_YEAR)
module_instance (MOD_PERIOD, MOD_ACADEMIC_YEAR)
student_on_a_module_instance (X_MOD_ACADEMIC_YEAR)

Each of these properties could be changed to refer to the PERIOD identifier.  For example, an ACADEMIC_YEAR reference could contain a PERIOD string identifier "2017-18 Academic Year" that refers to a specific PERIOD record giving start and end date.  If just the academic year needs to be shown, use the YYYY from PERIOD_START_DATE.  Documentation for each of these properties would need to be changed.

In the future there may be other uses for the official dates of these periods.

I've drafted a PERIOD.MD file and amended the diagram as the basis of further discussion, but not yet altered the properties in the course_instance, module_instance and student_on_a_module_instance entities.  This can swiftly be done if there is agreement on this approach.

Alan

**Comment by alanepaull** [comment]
Monday 19 Dec:
Retain ACADEMIC_YEAR as is where used, because this enables easy lookup of the year (yyyy).  Add in a property that references the Period table, so that start and end dates can be looked up there if needed.

**Comment by alanepaull** [comment]
Proposal: add ACADEMIC_YEAR_PERIOD_ID as optional property to course_instance, module_instance and student_on_a_module_instance.  Amend MOD_PERIOD (in module_instance) so that it carries the institution's label matching the PERIOD_ID in the PERIOD table.

Each of these new properties takes the institution's own label for the period (for example "2017-18 Academic Year").  This enables look up of official start and end dates, if needed.  The existing ACADEMIC_YEAR property remains.

Question: do we need a more conventional ID for PERIOD?  Current proposal is simply to use the institution's label - relying on this being accurately stored.

Alan

**Comment by arc12** [comment]
Some reflections...
1. I think it is helpful to retain, for module instances, a label such as "term 1", "semester 2", etc. These will be locally-defined. They are helpful labels for institutional folk and are sometimes correlated with module outcomes.
2. Keeping academic year as a YYYY year, as mentioned above, is convenient
3. We do use academic year in Student Insight and will need to get the start and end dates from somewhere
4. At present, we don't use start and end dates for e.g. "term 1 in AY 2016", but I can see we might want this in the future, and it provides a useful way of qulity-checking the dates given in the instance data.

A workable approach (yet another candidate) would be for PERIOD to comprise:
ACADEMIC_YEAR = YYYY
SUB_PERIOD = optional, to indicate the MOD_PERIOD code
START_DATE
END_DATE

The AY period record has no SUB_PERIOD.
Records for module instances do have SUB_PERIOD, and the start/end dates are retrieved (should one wish to do so) by using a compound from module-instance on MOD_ACADEMIC_YEAR and MOD_PERIOD. In practice, however, I think we would generally want to get the dates for a given period e.g. 2015AY, rather than to perform some kind of "join" from course/module instance records.

Although this approach doesn;t look very database-y, it has low impact (no changes to existing data structures0 and will, I think "do the job".

**Comment by alanepaull** [comment]
I'm conscious that we need to make this a bit database-y to fit in with the UDD structures.  For example, PERIOD will need a primary key.  How about this:
ACADEMIC_YEAR* (YYYY)
MOD_PERIOD* (mandatory; indicates MOD_PERIOD, or "AY" for Academic Year)
START_DATE
END_DATE

Primary key is ACADEMIC_YEAR + MOD_PERIOD.
Then none of the existing entities has to change.

**Comment by alanepaull** [comment]
Period reference data entity updated.  Proposals also for very simple inst_tier and course_location entities.  See also diagrammatic representation.

![udddiagram_refdata_draft](https://cloud.githubusercontent.com/assets/17160871/22598663/18c6552c-ea2c-11e6-8269-5bdffc64210c.png)

**Comment by arc12** [comment]
I would like to COUNTER this approach to "reference data".

Location is just a code list. Its not a UDD list, but defined per institution.
This is what we do now, applying validation according to the list. It works fine.
Unless we have clear requirements for location to be more than "just a categorical", we should treat it like the other categoricals.

Inst-tier could also be treated in the same way. This is how we do it now, with validation. The downside of the status quo is that the tier hierarchy has to be inferred from the course records. Having said that, it works; we can meet all our requirements with existing data code.
I can see sense in removing the three tiers from COURSE but only if we create an entity which captures the relational structure. This isn't quite as simple as it might be since COURSE must relate to the lowest most tier, which may be 1-n levels down. Hence we may still choose to include all of INST_TIER_n in COURSE. Without the relational structure, we should treat it like any other categorical.

PERIOD is, I think, a special case because:
a) there is associated temporal data; they are not just catgoricals with labels.
b) there will be new records for each term/semeseter every year. Arguably it is instance data, not reference data.
c) adding it solves a problem which we have now.

Even given this, I see MOD_PERIOD as being just another categorical. e.g. to put all semester 1 modules in a group. The PERIOD entity provides additional information.

**Comment by alanepaull** [comment]
I guess I'll refer this one to Michael and / or Rob.  Is there a specific *requirement* for the inst_tier and course_location data to be in the UDD?  If not, then we can smartly drop it.

@arc12: are you content with the current PERIOD implementation as in period.md now?

**Comment by arc12** [comment]
@alanepaull re PERIOD
Broadly although:
A. 
changing ACADEMIC_YEAR in COURSE_INSTANCE and MOD_ACADEMIC_YEAR in MODULE_INSTANCE from integer to a string is a change which will break things. I can see why you did this, but equally, we could state this is the year part, the integer in a data structure. Neither is illogical. It people can swallow INT, I encourage it. It will save having to code-up conditionals on v1.2 vs v1.3

B.
I think an element for a human-readable label would be good, to allow for e.g. 2015-16. I would make this mandatory; people can easily make something up that makes sense (e.g. copy the other element content ;-)

C.
I'm sure I had a "C" which has now slipped my mind.

**Comment by robwynj** [comment]
I would keep this, maybe required in future for org structure replication @Michael?

RWJ

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; APMG PRINCE2 & APMG AGILE Certified Practitioner

Senior Data & Analytics Integrator - Jisc UK Learning Analytics
Cluster Lead – Jisc Data & Analytics Service

email/ skype: rob.jones@jisc.ac.uk<mailto:rob.jones@jisc.ac.uk> mobile: 07468 727040  web: www.jisc.ac.uk<http://www.jisc.ac.uk>

**Comment by arc12** [comment]
I move to include PERIOD in v1.3.0
I think we are close to agreement.

I move to exclude other changes in the ER diagram from v1.3.0

**Comment by robwynj** [comment]
This entity, and similar others proposed for 1.3.0 can be denoted as “optional” entities anyway… technically all entities “are” optional – let me know what you think…

Rob

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; APMG PRINCE2 & APMG AGILE Certified Practitioner

Senior Data & Analytics Integrator - Jisc UK Learning Analytics
Cluster Lead – Jisc Data & Analytics Service

email/ skype: rob.jones@jisc.ac.uk<mailto:rob.jones@jisc.ac.uk> mobile: 07468 727040  web: www.jisc.ac.uk<http://www.jisc.ac.uk>

**Comment by alanepaull** [comment]
Monday 13 February:

Agreed that in PERIOD we would rename the property MOD_PERIOD to PERIOD_CODE; and add a new property PERIOD_NAME, amending descriptions as appropriate.

**Rationale:** values in MOD_PERIOD are currently usually codes, not 'friendly' labels, so it is better to use this naming convention.  PERIOD_NAME should hold the user-friendly name (for example "Spring Term" or "Semester 1").

The PERIOD_CODE in PERIOD must explicitly match with MOD_PERIOD value in MODULE_INSTANCE.

We also agree to re-consider INST_TIER and COURSE_LOCATION entities for v1.3.1.

**Comment by alanepaull** [comment]
To enable lookup of academic year, we have a note that MOD_PERIOD (now PERIOD_CODE) should have the value "Academic Year" when the record refers to an academic year, rather than semester, term, and so on.  Is this required, or will institutions/vendors sort this out themselves?  I can easily remove that note, and I don't see any particular value in forcing conformance in this regard.

**Comment by arc12** [comment]
It would help us to have a standard code here. We need to query just the academic year periods and this will be easier if the query is independent of institution. I have a mild preference for an all-CAPS code because it says "I'm a code".

**Comment by arc12** [comment]
Re PERIOD_NAME:
I think this names the whole entry, so "should" guidance could indicate e.g. "Semester 1, AY 2014/15", but this is wholly up to the data supplier. Bottom line: what do you want users to see (don't expect us to compose anything)?

**Comment by alanepaull** [comment]
Re-drafted in new file.  See period.md.

I've suggested ACADYR for the code.

**Comment by arc12** [comment]
@alanepaull 
possible ambiguity here:
" For other periods, PERIOD_CODE uses institution-defined code values in conjunction with the 4-digit value of the ACADEMIC_YEAR property..." could be understood to mean that PERIOD_CODE contains the year number.

As I understood our discussion, PERIOD_CODE indicates the kind of period and should be either "ACADYR" or a value used in MOD_PERIOD. Critically, all values used in MOD_PERIOD must appear...
PERIOD_CODE examples: "SEM1", "WHOLE YEAR", "TRMS1+2"

**Comment by alanepaull** [comment]
That was my understanding too.  Perhaps poor wording.  How about limiting the Period description to:

"A period describes an institution's official start date and end date of time slices, such as academic years, terms and semesters."

Then have the PERIOD_CODE description as: 

"The institution's own code for the period."

and PERIOD_CODE Valid Values as:

"Where the period record sets the dates for the institution's academic year, PERIOD_CODE must use the fixed string "ACADYR".  For other periods, PERIOD_CODE uses institution-defined code values.  Each different code value in module_instance.MOD_PERIOD must have a matching code value in PERIOD_CODE.  Where the same code values are used across different academic years, the specific period record can be identified by reference to the PERIOD_CODE together with the ACADEMIC_YEAR property; these properties together form the primary key."

and PERIOD_CODE Notes:

"Examples: "SEM1", "WHOLE YEAR", "TRMS1+2""

I'll add a corresponding note to module_instance.MOD_PERIOD to clarify the matching values point.

Does this sound OK?

**Comment by arc12** [comment]
works for me!

**Comment by alanepaull** [comment]
inst_tier and course_location entities removed.  Will be reconsidered for v1.3.1 or later.
Alan

**Comment by ht2** [comment]
Hi all,

Can I check this wording: 
"[Any Each different code value in MOD_PERIOD must have a matching code value in period.PERIOD_CODE.](https://github.com/jiscdev/analytics-udd/blob/v1.3/udd/module_instance.md#valid-values-1)"

Should the LRW reject adding/updating a Module Instance entity where the `MOD_PERIOD` does not exist in a Period entity as a `PERIOD_CODE` for that organisation?

**Comment by alanepaull** [comment]
I'll correct the typo there.  Should be "Each different code value...".

**Comment by ht2** [comment]
Thanks @alanepaull - I'm still unsure if the LRW has to reject updates/inserts based on the values present in other entities? It would be a first if that was the case.

**Comment by alanepaull** [comment]
I'm not in a position to make that decision.
However, I strongly suspect that I should change the "must" to a "should" in that sentence.  Then there may be no requirement to validate as you suggest.

**Comment by ht2** [comment]
That was broadly our thinking, we'll go ahead with the "should" as the assumed language!

**Comment by alanepaull** [comment]
"must" changed to "should".

**Comment by alanepaull** [comment]
See issue #196 for INST_TIER and COURSE_LOCATION reference data.
