### ISSUE TITLE
Institution-specific code lists

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#106]
There are several UDD fields which can take institution-specific codes. While we could treat these as "free text", this reduces our ability to validate. More importantly, we might have the problem of relating codes in the LRW-UDD to nice human-readable labels. For example. institution tiers. We could require the use of the human-readable labels, but that would, I think, cut across good practice.

I suppose it is an open question whether this is in scope for the UDD specification, or whether this is an out-of-spec matter between an institution and Jisc (as an intermediary for possible suppliers).

Propose: for the first instance, provide these institution-specific code lists as JSON, following the form of the code lists I extracted from the markdown. i.e. a JSON associative array with the keys being the names of UDD fields and the values being further associative arrays with the keys as the permitted codes (including for historical data) and the values being the nice readable labels. (each language gets its own JSON file)

**Comment by leebaylis** [comment]
Where is it proposed that these would be provided — on the main github? So institutions would have an account and maintain them themselves?

 
> On 28 Jul 2016, at 09:18, Adam Cooper <notifications@github.com> wrote:
> 
> There are several UDD fields which can take institution-specific codes. While we could treat these as "free text", this reduces our ability to validate. More importantly, we might have the problem of relating codes in the LRW-UDD to nice human-readable labels. For example. institution tiers. We could require the use of the human-readable labels, but that would, I think, cut across good practice.
> 
> I suppose it is an open question whether this is in scope for the UDD specification, or whether this is an out-of-spec matter between an institution and Jisc (as an intermediary for possible suppliers).
> 
> Propose: for the first instance, provide these institution-specific code lists as JSON, following the form of the code lists I extracted from the markdown. i.e. a JSON associative array with the keys being the names of UDD fields and the values being further associative arrays with the keys as the permitted codes (including for historical data) and the values being the nice readable labels. (each language gets its own JSON file)
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Jisc is a registered charity (number 1149740) and a company limited by guarantee which is registered in England under Company No. 5747339, VAT No. GB 197 0632 86. Jisc’s registered office is: One Castlepark, Tower Hill, Bristol, BS2 0JA. T 0203 697 5800.

Jisc Services Limited is a wholly owned Jisc subsidiary and a company limited by guarantee which is registered in England under company number 2881024, VAT number GB 197 0632 86. The registered office is: One Castle Park, Tower Hill, Bristol BS2 0JA. T 0203 697 5800.

**Comment by arc12** [comment]
@lee - I haven't got an opinion. I suppose the answer depends on the kind of workflow Jisc is anticipating for on-boarding institution data.
Adam

**Comment by wilmTap** [comment]
I wonder whether there's a case for making institutional profiles of the whole spec. That way, people would be able to know exactly what is and what is not supported for a particular provider. If these profiles get their own repos, version management ought to be doable(ish)

**Comment by wilmTap** [comment]
Needs more discussion- from H2 particulary.

**Comment by andrewhickey** [comment]
Probably going to need a bit of a think and then a call to run through some options on this one. It looks like it could get tricky to maintain as most of the solutions that jump out would require an update to the LRW for every set of custom data. We probably want to avoid that as it would become a bottleneck pretty fast!

**Comment by alanepaull** [comment]
Invite to Skype call:  http://doodle.com/poll/mhqrd5c57f3dmh79gs72z5w5/private

Alan

**Comment by alanepaull** [comment]
Might James or Katharina be available, even if we might be lacking Andrew?  We're really short of a suitable mutually convenient time this month, otherwise.

Alan

**Comment by ds10** [comment]
When I use the above link it says that the link has already been used? Is there a link for everybody?

**Comment by alanepaull** [comment]
Apparently the one I sent by email works fine. I invited adam.cooper, Alan Paull, lee.baylis, andrew.hickey, james and katharina.lass.  I'll send you a link too.
Alan

**Comment by leebaylis** [comment]
Hi David, 

The one Alan sent by email was his own — but Doodle should have sent you an email too, which is the one that will let you in.

Thanks,
Lee

> On 23 Jan 2017, at 14:32, David Sherlock <notifications@github.com> wrote:
> 
> When I use the above link it says that the link has already been used? Is there a link for everybody?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Jisc is a registered charity (number 1149740) and a company limited by guarantee which is registered in England under Company No. 5747339, VAT No. GB 197 0632 86. Jisc’s registered office is: One Castlepark, Tower Hill, Bristol, BS2 0JA. T 0203 697 5800.

Jisc Services Limited is a wholly owned Jisc subsidiary and a company limited by guarantee which is registered in England under company number 2881024, VAT number GB 197 0632 86. The registered office is: One Castle Park, Tower Hill, Bristol BS2 0JA. T 0203 697 5800.

**Comment by alanepaull** [comment]
Yes.  I suspect I need to be a bit more careful with Doodle, and not put up a generic link, cos it ain't.  Apologies.

**Comment by alanepaull** [comment]
The Doodle poll didn't work, because we weren't able to arrange a suitable date for HT2 as well as our other interested parties.  I suggest that we try again at the meeting on Monday 30th.

Alan

**Comment by arc12** [comment]
We need institution-specific code lists and use them now for attributes which have no UDD code list. We can also allow sites to over-ride UDD lists, because enforcing conformity is sometimes a stumbling block.

BUT I move to exclude from v1.3.0, defer to later "dot" release
Should be part of a discussion on the LRW replatforming for UDD data. i.e. a non-spec issue at the moment

**Comment by alanepaull** [comment]
@arc12: Is there an example of the JSON format used for this.  I'd like to include that in the documentation.  Can you point me in the right direction, please?
Alan

**Comment by arc12** [comment]
Alan - I use the same format as the UDD code lists in my latest pull request.

**Comment by alanepaull** [comment]
Reference to this added to README.
