### ISSUE TITLE
Staff Membership - Role and Deletion Logic

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#107]
This is an issue statement which originates with the "soft deletion" and propagation of instance deletes downstream from the LRW. On thinking about solutions, the potential benefits of including role became aparrent. Note that including role is not actually a current requirement but this is conceivably a useful attribute to be used in dashboard access control, so is something of an opportunistic solution to the original problem. Arguably, the problem is NOT a UDD specification issue but... 

Problem statement:
we currently have a mechanism of propagating instance deletes which sends records with all-null values other than the index fields. This works well for most UDD tables but fails for the two cases which are purely joining staff ids to either course or module instances. These only contain the index fields so there is no way to pass a delete with the agreed mechanism. Since the association of staff with course/module instances will be used to control access to student-level predictions in the dashboard, customers will be likely to want to avoid the scenario where there is no way to recind access. At present, we would have no way to propagate dis-association to become a de-authorisation.

Possible solution:
add a field to both the staff-module and staff-course association tables for role. i.e. to code-up "staff-id is associated with group-id as a {role-code}". This would be NULL to signal deletes otherwise a string value of the role-type. At present, I do not think we'd be able to differentiate access according to role, so this would be effectively a dummy to resolve the deletion issue - and I propose that, if we do add a role field, there is only a single-valued code list - but I can forsee a situation where it could be used to grant access to group-only level aggregate visualisations, rather than to give access to individual-student level predictions, for some staff. (I have some reservations about the desirability of this scenario, but it is a conceivable customer requirement, I think).

**Comment by wilmTap** [comment]
Sounds like a good solution, but maybe we'd want to restrict the role value to an institutionally determined screen string. It seems to me that we'd better sort access control with a general mechanism across the whole LRW.

**Comment by wilmTap** [comment]
Pending resolution with HT2, Michael and Tribal

**Comment by arc12** [comment]
This has been discussed with HT2. We can resolve with a code change.
There is no need for UDD change
