### ISSUE TITLE
Example MODULE_INSTANCE.MOD_PERIOD values (Aber Uni) - change to Alphanumeric - APPROVED (for UDD 1.2)

### ISSUE THREAD

**Issue by robwynj** [jiscdev/analytics-udd#11]
Suggested options by Aberystwyth University - to be discussed - I would prefer to stick with the HESA definitions, but for information purposes below. Depends if we will benefit from this granularity in LA....

Kind Regards

Rob

0              Available CE students only
1              Semester 1
1R           Sem 1 resit only
2              Semester 2
2R           Sem 2 resit only
3              Semester 3 (Dissertation)
3R           Semester 3 resit only (Dissertation)
A             Available all semesters
B             Available semesters 1 and 2
N             Intended for use in future years
R             August Resit
X             To be deleted

**Comment by arc12** [comment]
Rob -
my observation on that list is that it appears to mix in resitting/retaking and "future years". In general, I value code list purity, and I think this is especially important when we're trying to get a scheme that will work across institutions; conflated code lists are likely to be reflective of idiosyncrasies.

Adam

**Comment by robwynj** [comment]
Agreed, I am proposing to stick with the HESA standard here.

**Comment by robwynj** [comment]
Just done a refresh on the HESA SR spec - I believe there is no indicator of this type in the current student return (double checked this) - therefore might be an idea to provide a few different options here (the field itself would also be optional), otherwise we purely make the field alphanumeric (as per CAMPUS field) for bespoke use, or deprecate it totally.

**Comment by robwynj** [comment]
Are we all agreed that this fields should now be free-text (alpha) - if so we should update the UDD for 1.2 :)

Kind Regards

Rob

**Comment by arc12** [comment]
The period is likely to be usfeul. We've found the start/end dates to be unreliable info in the Exeter SRS and period is the best guide to module scheduling.
I suspect free text is the way to go, with a presumption that there will be site-specific controlled-lists. I have a hunch these will often be messy, with module periods including combinations of single and multiple term delivery...

Adam

**Comment by robwynj** [comment]
Agreed. Wilbert - FYI.

Kind Regards

Rob

**Comment by wilmTap** [comment]
Changed the value space to any string (256) in #15 

Agreed with the change: I know several institutions where this field will have become a zoo because of past changes...
