### ISSUE TITLE
Clarify use of FIRST_, ACTUAL_, AGREED_ Marks and Grades

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#115]
We refer to moderation but do not clarify how the attributes should be used if:
- only the post-moderated result is in the SRS. Should ACTUAL be null or entered as the same value?
- there is no moderation process. Should the result appear in ACTUAL or AGREED

I propose we clarify the wording to indicate that the AGREED results are present whether or not moderation occurs, and that ACTUAL is only used where a moderation process occurs (whether or not the result is changed in that process).
Adding this clarification will aid consistent treatment of results.

**Comment by robwynj** [comment]
Hi Adam,

I have always seen/ interpreted "AGREED" to be the master/ 1st priority (so the final one which is used?).

I agree the wording/ explanation needs to be expanded as per above.

Kind Regards

Rob

**Comment by arc12** [comment]
Yes, I think "agreed" is the authoritative result, but that maybe our UDD wording was not clear to one of our currently-onboarding sites.

**Comment by robwynj** [comment]
I agreed definitely on this score. So important though in BAU/ Live updates scenario too…

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; APMG PRINCE2 & APMG AGILE Certified Practitioner

Consultant – JISC Special Projects

email/ skype: robert.jones@jisc.ac.uk<mailto:robert.jones@jisc.ac.uk> mobile: 07976 508860

**Comment by craig-petch** [comment]
Yep Agreed is the authoritative result where present. During moderation when we have data being regularly updated we may find that Actual is present but Agreed is empty. If no "Actual" mark is available from the SRS then I think a null would be fine and Agreed populated. First also would likely to be null in this scenario too.

**Comment by arc12** [comment]
+1 on agreed and actual.

I'm not sure about FIRST, though; I understood that this attribute was originally added to accommodate cases of referral, rather than to capture moderation. Whatever we decide, the documentation should be clarified...

**Comment by wilmTap** [comment]
How about:

FIRST_

Definition: The mark/grade awarded by the initial marker prior to any moderation process.

Note: FIRST_ mark/grade should only be part of a UDD compliant dataset if there is a moderation process and the input mark/grade is available in the source data. 
If a marking process involves concurrent initial marking, the reconciled result should be recorded in ACTUAL_.

ACTUAL_

The mark/grade awarded to the learner after any moderation process, but before any formal confirmation process. Moderation processes typically involve multiple markers, and confirmation processes typically involve external examiners.

Note: FIRST_ mark/grade should only be part of a UDD compliant dataset if there is a moderation process and if the result of that process is available in the source data. 

AGREED_

The mark/grade recorded after any moderation or confirmation processes, or the only recorded mark/grade if there are no moderation or confirmation processes. This mark/grade is typically the one used to determine degree classification.

Note: AGREED_ mark/grade is expected to be present in any UDD compliant dataset as soon as it becomes available.
