### ISSUE TITLE
Clarify use of SoAI for multiple attempts

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#118]
We currently have:
- ASSESS_SEQ_ID
- ASSESS_RETAKE
- ASSESS_CURRENT_ATTEMPT

The current spec wording could be more clear about how these should be used.
SEQ seems most clear in intent but maybe could be clarified by stating that there should be a separate SoAI record for each time work is submitted for assessment. On the other hand, would a failure to submit also lead to a record??
The main issue seems to be in the way that mitigating circumstances may mean that, as far as academic rules go, work may be submitted against a second opportunity but NOT count as a new attempt. If this is the intention of  CURRENT_ATTEMPT, then the difference to SEQ should be clarified. Similarly, the conditions underwhich a RETAKE is considered to occur, and whether RETAKE is equivalent to ATTEMPT>1, or not.

It might help to make RETAKE indicate the condition of mitigating circumstances.

**Comment by wilmTap** [comment]
Needs further investigation of the data.

**Comment by alanepaull** [comment]
From Monday 5 Dec call:

Craig at Tribal may be able to supply data.

**Comment by alanepaull** [comment]
Thanks to Craig for showing me around some relevant SITS data.  A key question here is how important this information is for analytics.  Many institutions won't have this data.  Is this vital, important, of nice-to-have?

However, we can re-draft for more clarity: 

ASSESS_RETAKE
Description: States whether this is a retake of the assessment for that student as a result of mitigating circumstances.

ASSESS_SEQ_ID
Description: A unique sequence number to indicate the order of assessments taken by a student on the assessment instance.
Purpose: To identify the latest assessment taken, whether or not results were achieved, and the order of assessments for a student, especially for those in reassessment.  Each assessment attempt should have a unique student_on_assessment_instance record, regardless of mitigating circumstances or results.

ASSESSMENT_CURRENT_ATTEMPT
Description: Number of attempts taken by a student so far on an assessment instance, that are recognised by the institution as separate attempts.
Purpose: Analytics
Notes: Some institution's regulations permit attempts with mitigating circumstances to be ignored as attempts.

Alan

**Comment by alanepaull** [comment]
From Monday 16 Jan call:
Above changes implemented and committed.
