### ISSUE TITLE
Expand guide to mandatory properties in the UDD

### ISSUE THREAD

**Issue by wilmTap** [jiscdev/analytics-udd#120]
In UDD v1.2.7 [a guide to mandatory properties in the UDD](https://github.com/jiscdev/analytics-udd/blob/v1.2.7/mandatory.md) was introduced to record how badly different properties are needed, and for what purpose. Since then, there has been a demand to expand the information recorded in the guide. Solutions include:
1. Embed the category information in the entity documents, and add property specific information about how different applications use the data.
2. Do not embed any usage information in the entity documents, but expand the current list into a table that records the categorisation of all properties, by entity, as well as usage by one or more applications.

Solution 1 could be problematic, because views on property usage is more fungible and faster changing than the datamodel itself. Separating usage information from the datamodel might generally be cleaner once more communities start making use of the UDD. Also, usage constraints apply to a combination of entity and property, but properties in the UDD are described only once- which could make the usage info potentially confusing.

For solution 2, a decision would need to be made about the format of the table, and the information it contains. Format options include: an html table embedded in the markdown document, or a CSV. Information options include all properties in rows grouped by entity, and columns for categories, app usage and general comments.

**Comment by arc12** [comment]
Re 

> For solution 2, a decision would need to be made about the format of the table, and the information it contains. Format options include: an html table embedded in the markdown document, or a CSV. Information options include all properties in rows grouped by entity, and columns for categories, app usage and general comments.

I see a balance between:
1. - editing ease
2.  - formatting and presentation usability
3. - facility of merging and change tracking

Most formats seem to be deficient in at least 1 respect!

it might be possible to use the atom table-editor, or some sublime equivalent, and to stay in pure markdown, but I suspect that this will be gnarley at some point.

Adam

**Comment by wilmTap** [comment]
Given the intended audience, and the size of the data, I've ended up with just Excel and ODF.

**Comment by wilmTap** [comment]
I've just added a new version with a code list column, as proposed by @robwynj .

One thing we may want to think about is how to maintain the spreadsheets. Google docs is convenient, but requires access to anyone who wants to propose a change, and it also means there could be clashes between the different version control systems of github and google docs: once a pull request from someone who hasn't used the one source google doc has been merged in, the connection with google docs is lost. 

The alternative is to edit the spreadsheets using either MS Office or LibreOffice / OpenOffice, and send a pull request, like you would with other changes in the UDD.

Preferences?

**Comment by wilmTap** [comment]
From @arc12, with inline responses:

> Thinking about presentation rather than content
> --------------
> Thought on category descriptors.
> For Cat 2, maybe add “(e.g. dashboard)” to clarify the applications and say “...all courses and students”.
> For Cat 3, possibly reword (if I understand correctly):
> “These properties are needed for the learning analytics (predictive) models to function well for all students. They are mostly attributes which allow the data to be segmented and managed. If they are missing from records, either the performance of the predictive models could be significantly impaired, or predictions could be missing for affected students/courses.”

Done
  
> Thought on formatting:
> Use heavy lines between entities.
>  
> Other presentation:
> Col heading “options list?” is a but cryptic

Sorted

> Thinking about the categories
> ------------
> Not sure about F5:F8. Maybe enough If they are in col D, which is where I suppose they are useful.

To my understanding, col D (student app) is a subset of category 2.

> Make F23 = Yes (AY used to go back in time in Student Insight)

Done

> Remove F50 (AGE), given we’re deprecating it.

Good catch.

> Is F60 correct? Stu app needs I guess, but that gets its own column. No student access to Student Insight dashboard for students.

Following the logic of col D (student app) being a subset of category 2. Also, since cat 2 implies a higher priority than 3, 4 and 5, it covers those other categories. I think.

> Rows 66:73 we wouldn’t use at all.

Cat. 5 is a remainder category, included for completeness. If no-one is going to ever use them, they should be removed...

> Photo url is a special case. Would be relevant for the dashboard but I think there are some logistical issues we haven’t yet covered in the infrastructure. I don’t believe these would be an open web URL. Would be somehow managed in the LRW???

Moved to cat 2- we can deal with the how separately.

> Tutor staff ID will be needed to manage personal tutor associations. This is a cat2 issue.

Done.

> Withdrawal date is deprecated – add comment, remove “YES”?

I've removed it; why direct people to include something we don't really want?

> Row93 join age would be better in col H

Done

> Should F104:F107 be in col H? These are useful but not critical IMO. Also we should acknowledge that “actual” may not always be applicable, and that different institutions may have different approaches re marks vs grades

I thought they were rather more crucial than that, but moved them and adjusted the comments.

> Move G125:G126 to col F. These drive whether the student appears as current against the module in the dashboard

Done

> F127 and F128 should be down-graded. Only applicable in some cases/institutions, and likely to be a minor indicator even then.

Moved to cat. 5

> YEAR_PRG in cat 3 please

Done

> For staff:
> Exclusively used for dashboard access control, not for any modelling. Also, we will need the email address for password delivery.

I'm assuming the 'dashboard access control' pertains to staff.STAFF_ID alone?


All implemented in two new outputs, still generated from google docs.

**Comment by arc12** [comment]
Re
> To my understanding, col D (student app) is a subset of category 2.
I can see the logic which says cat 2 is "stu app, dashboard, etc..." and "stu app" col is a subset. This isn't the case in the spreadsheet. It might be clearer to make the existing col F be dashboard and col D be stu app.

Re

> I'm assuming the 'dashboard access control' pertains to staff.STAFF_ID alone?

No. staff to module and course also needed to control access to groups of students.
In practice, we'd also recommend getting names too, so it is easier for people to validate access setttings.

**Comment by wilmTap** [comment]
All sorted
