### ISSUE TITLE
WITHDRAWAL_DATE is defined as int, needs to be ISO 8601

### ISSUE THREAD

**Issue by wilmTap** [jiscdev/analytics-udd#122]
student_course_membership.md#WITHDRAWAL_DATE is defined as int, but should be ISO 8601 YYYY-MM-DD 

Question is when to fix it- in v1.2.7 or v1.3?

**Comment by robwynj** [comment]
HI Wilbert - it functions fine (LRW API) but documentation (generic description) is just wrong

RWJ

**Comment by wilmTap** [comment]
Check with LRW just to make sure, then change

**Comment by andrewhickey** [comment]
It's implemented as a Date in the LRW (technically this is an INT)

**Comment by arc12** [comment]
issue #51 
we agreed to remove this

**Comment by wilmTap** [comment]
Check and mark as deprecated, and fix datatype in documentation

**Comment by robwynj** [comment]
1.2.7 and 1.3

☺

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; APMG PRINCE2 & APMG AGILE Certified Practitioner

Consultant – JISC Special Projects

email/ skype: robert.jones@jisc.ac.uk<mailto:robert.jones@jisc.ac.uk> mobile: 07976 508860
