### ISSUE TITLE
UDD 1.2.6+ Identification of Primary Keys for all UDD Entities (can be done for 1.2.7 & onwards?)

### ISSUE THREAD

**Issue by robwynj** [jiscdev/analytics-udd#124]
Hi Wilbert,

Having spoken to Huw this morning, and had a quick look at the UDD field-level documentation, can we build in (to 1.2.7 please, prior to any release) a primary key indicator for all entities please?

This would be picked-up by Huw’s initialisation for the UDD validation tool currently under construction.

Could this be done with a similar approach for mandatory/ optional denotation done previously.

Many Thanks,

Rob

**Comment by wilmTap** [comment]
Primary keys were added to each entity in v1.2.7 as part of resolving issue #104. Let me know if the form could be better, or if some need fixing.

**Comment by wilmTap** [comment]
After some offline discussion of various options to represent primary keys, there's two broad options:

1. continue with the PK statements (e.g. "Primary key: ('STUDENT_COURSE_MEMBERSHIP_ID', 'STUDENT_COURSE_MEMBERSHIP_SEQ', 'COURSE_INSTANCE_ID', 'MOD_INSTANCE_ID')"), perhaps augmented by a clearer, dedicated section header
2. some indicator on the listings such as:

> STUDENT_COURSE_MEMBERSHIP_ID [1] *
> STUDENT_COURSE_MEMBERSHIP_SEQ [1] *
> COURSE_INSTANCE_ID [1] *
> MOD_INSTANCE_ID [1] *
> * indicates that the property either is the primary key, or is part of a composite primary key for this entity.

In the interest of time, I'll change it to option 2 now, and leave it for a day to allow people to shout "stop" before I release v1.2.7

**Comment by robwynj** [comment]
Can you confirm that all composite PK's will also be identified in the UDD then?

Kind Regards

Rob

**Comment by wilmTap** [comment]
Hi Rob,

Yes- both single and composite PKs have been identified with * across the whole UDD in v1.2.7; let me know what you think.

**Comment by robwynj** [comment]
Brilliant ☺

Kind Regards

Rob

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; APMG PRINCE2 & APMG AGILE Certified Practitioner

Consultant – JISC Special Projects

email/ skype: rob.jones@jisc.ac.uk<mailto:rob.jones@jisc.ac.uk> mobile: 07468 727040
