### ISSUE TITLE
Date datatype notation inconsistency

### ISSUE THREAD

**Issue by wilmTap** [jiscdev/analytics-udd#125]
Over time, different conventions of notating date datatypes have crept in: some are format: strings constrained to ISO 8601 date values, some have format: xs:date and others ISO 8601. 

All of these date datatypes need to be noted consistently, and I'm open to suggestions on which format is preferred.

See also: issue #122

**Comment by arc12** [comment]
My vote is that all should be strings constrained in accordance with ISO8601 but specifically:
dates YYYY-MM-DD
times YYYY-MM-DDTHH:MM:SSZ (or with decimal seconds to ms or us for timestamps)

Adam

**Comment by alanepaull** [comment]
We do have some variability in how the spec asks for dates.

course_instance properties have:
###Valid Values
Date in ISO8601 format - YYYY-MM-DD
###Format
String (255)

while student_course_membership has:
###Valid Values
YYYY-MM-DD
###Format
ISO 8601 Date

As there is significant variability in what valid ISO 8601 dates and times can be, I suggest that we are consistent and explicit, as follows:

###Valid Values
YYYY-MM-DD [for date]; YYYY-MM-DDTHH:MM:SSZ [for datetime]

###Format
String in ISO 8601 Date extended format:
YYYY-MM-DD [for date]

String in ISO 8601 Date and Time extended format:
YYYY-MM-DDTHH:MM:SSZ [for datetime]

Properties affected are:

course_instance.start_date
course_instance.end_date
student.dob
student_course_membership.withdrawal_date
student_course_membership.course_expected_end_date
student_course_membership.course_end_date
student_course_membership.course_join_date
student_on_a_module_instance.mod_start_date
student_on_a_module_instance.mod_end_date
student_on_assessment_instance.assess_due_date
student_on_assessment_instance.grade_date
student_on_course_instance.year_com

If there is agreement, I'll change the files to make it consistent.

**Comment by alanepaull** [comment]
From Monday 5 Dec call:

Agreed. Alan to change, commit, then we'll confirm and close.

**Comment by alanepaull** [comment]
Also made the academic year Valid Values and Formats consistently this:

###Valid Values
Year in ISO 8601 format - YYYY

###Format
String in ISO 8601 Year format - YYYY

**Comment by alanepaull** [comment]
Noting that academic_year has traditionally been INT, not STRING, I was expecting a reaction to the above comment.  Could we confirm that academic_year throughout should be format = "INT"?  If we can, then I'll change the documentation back to INT.

An implication is that academic year will not be an ISO 8601 string.

**Comment by arc12** [comment]
I don't think it matters for us whether it is typed as INT or as an ISO year string which is parsable as an integer, since both JSON and CSV representations are just a series of four characters.
