### ISSUE TITLE
Remove student.AGE

### ISSUE THREAD

**Issue by wilmTap** [jiscdev/analytics-udd#126]
Following on from the discussion in #123, we've agreed to remove student.AGE in favour of using student.DOB.

**Comment by robwynj** [comment]
Is this also deprecated? If removed, could this apply for 1.3.x please.

Many Thanks

Rob

**Comment by wilmTap** [comment]
Yep; it's marked as deprecated in v1.2.7 (issue #123), and this issue is to remind us to remove it in v1.3.

**Comment by robwynj** [comment]
Thanks Wilbert ☺

Rob

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; APMG PRINCE2 & APMG AGILE Certified Practitioner

Consultant – JISC Special Projects

email/ skype: rob.jones@jisc.ac.uk<mailto:rob.jones@jisc.ac.uk> mobile: 07468 727040

**Comment by robwynj** [comment]
Is that deprecation – I get confused with these things!

Rob

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; APMG PRINCE2 & APMG AGILE Certified Practitioner

Consultant – JISC Special Projects

email/ skype: rob.jones@jisc.ac.uk<mailto:rob.jones@jisc.ac.uk> mobile: 07468 727040

**Comment by wilmTap** [comment]
The convention we've used so far is to say that a property is deprecated when it is still valid, but we're warning people that it will be deleted later. So if you _really_ want to or need to, you can send student.AGE to the LRW under v1.2.7 and be valid, but the property will go in v1.3.

We've not spelled that out, however, and we should, so I'll do that now.

**Comment by robwynj** [comment]
Thanks Wilbert – ideal ☺

Many Thanks

Rob

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; APMG PRINCE2 & APMG AGILE Certified Practitioner

Consultant – JISC Special Projects

email/ skype: rob.jones@jisc.ac.uk<mailto:rob.jones@jisc.ac.uk> mobile: 07468 727040

**Comment by alanepaull** [comment]
Now removed.

**Comment by alanepaull** [comment]
Confirmed, Monday 5 Dec call.
