### ISSUE TITLE
PK for assess instance id is wrong

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#127]
https://github.com/jiscdev/analytics-udd/blob/v1.2.7/udd/assessment_instance.md

should be assess_instance_id not module_instance_id

**Comment by arc12** [comment]
maybe also reorder fields to put PK at top

**Comment by wilmTap** [comment]
Sorted, thanks.

**Comment by robwynj** [comment]
Agreed

**Comment by robwynj** [comment]
Ideal ☺

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; APMG PRINCE2 & APMG AGILE Certified Practitioner

Consultant – JISC Special Projects

email/ skype: rob.jones@jisc.ac.uk<mailto:rob.jones@jisc.ac.uk> mobile: 07468 727040
