### ISSUE TITLE
mod_instance_id is redundant in PK of student on assessment instance

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#128]
since we have assess_instance_id, mod instance id is redundant in the PK for SoAI

Could we remove it from the PK spec please to reduce indexing/joining burden.
(but keep it as an attribute for convenience)

**Comment by wilmTap** [comment]
Sorted, thanks!

**Comment by robwynj** [comment]
You mean deprecate? I am asking if this could be done for UDD 1.3.x please.

Kind Regards

Rob

**Comment by wilmTap** [comment]
I think @arc12 meant that MOD_INSTANCE_ID doesn't need to be part of the composite primary key of the student_on_assessment_instance entity, but that MOD_INSTANCE_ID should still be part of student_on_assessment_instance. Put differently: I just took the '*' off student_on_assessment_instance.MOD_INSTANCE_ID, and that means the PK for student_on_assessment_instance entity is now:

STUDENT_COURSE_MEMBERSHIP_ID [1] *
STUDENT_COURSE_MEMBERSHIP_SEQ [1] *
ASSESS_INSTANCE_ID [1] *
ASSESS_SEQ_ID [1] *

Happy to put the * back against MOD_INSTANCE_ID, and reconsider for v1.3, though!

**Comment by robwynj** [comment]
Yes, it sounded like a removal - agree, remove the * as not relevant for MOD_INSTANCE_ID!

Many Thanks

Rob

**Comment by arc12** [comment]
nail hit on head!
