### ISSUE TITLE
Treatment of missing values

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#13]
At present, the UDD categorical attributes tend to have a code for "not known".

I think leaving not-knowns as empty* would be easier to handle because it avoids the need for knowledge of the per-attribute coding scheme and allows for consistent detection of missing data across all attributes (including numeric). Canvas opinion of others...

* - except where there is a clear concept of indeterminacy, e.g. sex is indeterminate, the student is homeless so has no address. (and these are edge cases I'm not actually expecting to see)

**Comment by robwynj** [comment]
Hi Adam,

I'm afraid I disagree on this - at least we know that institutions (or event students/ staff) have been confirmed that certain data is genuinely "not known" and not be attended to or mapped for example. The distinction here for data collection purposes, for some fields, is useful - and also conforms with HESA standards too.

Kind Regards

Rob

**Comment by arc12** [comment]
Rob - 
I suggest more analyst opinion should be gathered on this one.

BTW I note that use of code 99 for disability is now deprecated by HESA, also that an empty value is permitted for learning difficulty.

Adam

**Comment by robwynj** [comment]
Hi Adam.

Am happy to adapt the model accordingly, but am taking an independent view on this too from my own experience having completed several HESA staff and student returns.

I think I need to clarify that this is not a 1:1 mapping of the HESA staff return in the UDD - there are classifications/ transformation or areas where we won't agree or adhere with HESA on certain items/ mappings. This is to cater for both HE & FE also. Also, whilst loading/ mapping data over at such increased frequency - some information will be categorised and some will be null (genuine nulls).

Happy to accept NULL for LEARN_DIF - and should be updated for UDD 1.2.

Kind Regards

Rob

**Comment by arc12** [comment]
Rob -
just to return the opening, rather than focus on learning difficulties etc...

I think we agree that cases where "not known" is a fact in itself then an explicit code is useful. e.g. information is not knowable, or was not volunteered, etc

My contention about having codes for data which is simply not there in the database remains. It  may be necessary to treat these missing values differently in statistical/data-mining methods and in data-quality assessment as part of our pipeline. This is practically easier (IMO) if they are just left as missing, as opposed to there being several specific codes (field dependant) which I would have to identify or replace with a NULL-equivalent. It is also important to know that there is missing data and to take the appropriate action, rather than allow the fact to be concealed in a non-null. We already have numeric fields with missing data, so why not also for categorical fields?

I think the acid test is, for each field: does using an explicit code here convey any actual information? And the secondary case when using that code in UDD data extracts: is that information actually stored in the SRS? (data extract scripts automatically coercing nulls to the value just messes things up)

Cheers, Adam

**Comment by robwynj** [comment]
Hi Adam,

I think things are getting "lost in translation" on here tbh. 

Each institution is different, and may map/ not map data accordingly. The distinction between stated as "Not Known" vs not touched at all ie. not mapped yet or obtained/ classified, is there purely for flexibility. It's up to the HEI if they want to do it this way. If we do catch a NULL, we can feed-back to them (automatically) so they can clean-up/ cleanse. They could do this locally on ETL, but there you go.

So if a piece of data received is NULL (not admitted/ obtained), you discard in your pipeline anyway, correct?

I found it useful, as "Not Known" is a data-input field in some fields/ systems - non-entry (NULL) doesn't mean "Not Known", as could be a BP/ operational issue or data-input timing issue.

If you want to map to "Not Known" and don't send any NULLs over, no problem.

Cheers

Rob

**Comment by arc12** [comment]
Rob -
you mean you can't read my mind ;-)
I suspect this is one to discuss over audio sometime, to disentangle things. This isn't an urgent matter, but I think it is of practical significance, and one for which gaining the wisdom of others, rather than just agreeing between ourselves, would be sensible, I think.

Re "So if a piece of data received is NULL (not admitted/ obtained), you discard in your pipeline anyway, correct?":
it very much depends... lots of scenarios:
- NULLs reveal something "iffy" about the extract => engagge in a diaglogue about the data extract - is there a bug, or did I misunderstand what the data means
- check correspondance with other fields to verify understanding (e.g. at Exeter, modules with zero credit value always have NULLs for current and completed attempt counts, and marks)
- sometimes drop the instance record
- only use the non-nulls and code-up a binary flag (e.g. I'd expect us to only worry about "has a known learning difficulty")
- omit the value from an aggregate (e.g. the mean module mark for a student ignores in-progress modules)
- quickly determine which attributes are so sparse in real values as to be unlikley to be usable for prediction.
- replace missing values with a substitute value, e.g. mean or median value. (not likely to be common, but this kind of approach is necessary for some machine learning algorithms)

All of these are possible either with, or without, explicit coding of "not known" with a non-NULL, but there are practical implications...

BTW  - I think this issue is also linked to scenarios for selective disclosure, i.e. that a student may wish to exclude certain facts from being used in the learning analytics system. I haven't thought that one through, but it might be considered unethical to do anything other than pretend the data never existed. UDD should probably also accommodate institution-level decisions that certain fields are not in scope, and our data processing pipelines will have to be able to accommodate this with grace and elegance...

Cheers, Adam

**Comment by robwynj** [comment]
I think this piece also relates to instances where a field for an entity is mandatory - however the value is not known at a current point in time (for any of you HESA guru's, MODOUT what a classic case of this for student on module instances). My focus here is around those fields where it could be useful for a customer to have it as NULL, as opposed to a genuinely "Not Known" entry where they genuinely do not know the value after trying to fetch/ identify it, vs having not bothered or had the chance to fetch it at all....

**Comment by wilmTap** [comment]
Stepping back a bit, it seems that the question comes down down to when/where and how much normalisation you'd want to do.

On one extreme, you could say that we'd set mandatory attribute constraints on anything that comes in the LRW, and we treat NULLs exclusively as diagnostic values at the extraction stage. They should be transformed before loading. Which ought to give a nice, clean and uniform dataset that could also be quite incomplete and maybe even misleading in some cases.

The other extreme is to dump institutional datasets into the LRW more or less straight, and deal with quirks and present or absent data in the querying or analytics...

**Comment by wilmTap** [comment]
Since we have to resolve the issue before the 1.2 release, and since we haven't quite got consensus, I propose to do the following:

1. Follow HESA and simplify the more complex unknown vocabularies (e.g. DISABILITY: 'Information refused', 'Information not sought', 'Not known')
2. Allow NULL

1. does not quite standardise the treatment of missing values across the UDD, because some attributes appear to have useful specific values such as 'no known x' as well as 'unknown'. The resulting lack of uniformity seems a price worth paying.

I'll create a patch and merge it in with the 1.2 milestone unless there's a counter proposal with a majority by then.

**Comment by arc12** [comment]
WIlbert -
one thing that would, I think, make life easier is a consistent approach.

Differentiating different "not knowns" is a respecable thing to do and I wouldn't worry too much about simplifying e.g. the disability values. i.e. where there is an active recording process. e.g. "information refused" is informative (even if we doubt this fact would be useful for LA). OTOH I'm struggling to work out anything informative about the difference between "not sought" and "not known".

What I would like to see is the case of NULLs in the database being propagated in a consistent way rather than guesswork and automation replacing them with explicit values. Actually, I don't think it matters whether these come through as genuine missing values or whether folks want to have a code for "missing for reasons unknown", but if there is a code, it would be neat to use the same code across all of UDD.

Numerical values which are not yet known (e.g. assessment marks) will, I presume, continue to be left missing, so being consistent with categoricals would be neatest, I think.

Adam

**Comment by wilmTap** [comment]
I see your point about consistency, and I've tried to address that by defining NULL as an acceptable value meaning "no data" for each attribute that already supported "unknown" values. Would it help if NULL gets added to all attributes (including ones that don't have anything in the way of 'unknown' in their value spaces now)?

**Comment by arc12** [comment]
@wilmTap 
OK, good. Lets go with the approach you've pieced together so far. Get it in v1.2 and road test it...

Cheers, Adam
