### ISSUE TITLE
Proposed UDD 1.2.7 - DIFFLEARN1/2 - Should be left until UDD 1.3.x?

### ISSUE THREAD

**Issue by robwynj** [jiscdev/analytics-udd#130]
Hia,

This has been raised by UNICON/ Marist meeting today with Jisc - what is the key needs (predictive requirement?) around DIFFLEARN being in the datasets for current HEIs in the 1.2.x UDD version strand?

Should this actually go into UDD 1.3.0?

Kind Regards

Rob

**Comment by wilmTap** [comment]
When we discussed it during the last call, the rationale for including DIFFLEARN in v1.2.7 was to enable longitudinal analysis of learning difficulties, in view of the fact that there are already inconsistencies and discontinuities between the 2015 - 2016 and the 2016 - 2017 academic years.  These problems are outlined in issue #114, and concern changes in institutions' source data that require a change in the UDD datamodel in any case.

During the discussion, it was felt that the addition of new properties could take place before v1.3, also in view of the fact that the old ones (LEARN_DIF, DISABILITY1/2) were retained.

Having said that, we could defer until v1.3.

**Comment by robwynj** [comment]
Hi Wilbert,

Many Thanks for this - and clarification. However, I am somewhat viewing this as a "breaking" change, and with 1.3.0 becoming imminent soon anyway, can we schedule this for 1.3.0 instead please (I just want to get any data refreshes for 1.2.x over the line now, avoid anymore data refreshes for this tree. @arc12 are you happy with this?

FYI @huwrobertsjisc 

Kind Regards

Rob

**Comment by arc12** [comment]
This new [duple] field is a bit of clean up, saving trying to shoehorn 16/17 HESA changes into the existing structure. I would be happy with 1.2.7 proceeeding without it so long as 1.2.7 doesn't try to cover the new HESA. The new field also helps us to deal with FE and HE more consistently.

The new field will save us from quality and maintenance issues down the line. The sooner we can put it in place the better. I had thought that by leaving the old fields in, and having the new one optional that there would be no issue. Users of the old one can carry on as before. People who want to write ETL to the new one can get on with it.

There are, however, a series of changes which I think we really need to put in place SOON, which fall into 1.3 because they are definitely breaking. So, it we can get a move on with 1.3 then we can live with deferral of DIFFLEARN (so long as HESA 16/17 changes don;t muddy the coding).

**Comment by robwynj** [comment]
Hi Adam,

That sounds like a good move to me - the aim will be to release (hard validation version first - covering UDD 1.2.x and 1.3.x) of @huwrobertsjisc 's UDD validator to customers sometime in November, so they can start validating for 1.3.0 ahead of time.

@wilmTap - can we make this so for 1.3.0 instead of 1.2.7 please - many thanks.

Rob

**Comment by wilmTap** [comment]
I've removed DIFFLEARN1/2 from v1.2.7, and reinstated the mapping from v1.2.6, but with a number of differences:

1. The headings have been clarified to state that the mapping only pertains to HESA 2015/2016 and FE ILR prior to 2014.
2. The NULL code has been removed as per issue #131 
3. The UDD code for "Moderate learning difficulty" has been changed from "1" to "50", and "1" has replaced "99" as a UDD code for "Not known / information not provided"

The latter is prompted by the fact that, as far as I can see, _all_ student records in https://jiscv2.learninglocker.net/api/jisc/v1.2.5/ have been coded with "1", which, according to HESA learndif and the UDD prior to v1.2.6, should mean "Moderate learning difficulty". That every student would have such a challenge seems a little unlikely. More likely is that all these records were marked as "1" to get past the LEARN_DIF required constraint.

The solution in 3. is decidedly suboptimal, but the alternatives are worse:

- No change means that you can't know what '1' means, and nearly all data has it.
- Relying on the fact that the real HESA value for "Moderate learning difficulty" is "01" (not "1") would have been nice, except that the UDD v1.2.6 format is int, so you can't tell the difference.

DIFFLEARN would have allowed us to sidestep the problem by copying the value from legacy LEARN_DIF data verbatim, and move on, but, alas...

Note that the HESA - UDD code swap from 3 will have to be replicated in ETL for v1.3 on for UDD LEARN_DIF

**Comment by alanepaull** [comment]
We now have DIFFLEARN1, DIFFLEARN2, LEARN_DIF, DISABILITY1 and DISABILITY2 implemented in Student, as initially done in 1.2.7 and subsequently rolled back.  These properties cover various HESA and FE ILR fields for learning difficulties and disabilities.  We can now record the source data values as well as the UDD coded values.

Subject to final confirmation, we should be able to close this issue.

**Comment by alanepaull** [comment]
From Monday 5 Dec call:

Interested parties to check, confirm it's OK here, then Alan to close.

**Comment by arc12** [comment]
I think we can work with it. 

Some comments, though:
1. I'm unconvinced that we need to have both a "1" and a "2" field.
The data Ive seen makes use of only one
We have a "multiple" category
The numbers of students concerned is very small in a single institution and I'm certain we'll only use one field as a predictive feature.
Propose: a single DIFFLEARN attribute

2. I remain unconvinced that the greater detail of DISABILITY and LEARN_DIFF is warranted
(for predictive analytics)
The numbers of students are just so small we'll probably be within the noise. I can see these might be used for reporting, but as an edge case.
Propose: the UDD spec emphasises DIFFLEARN as the preferred field and down-plays DISABILITY and LEARN_DIFF as "may be used if required".
The point here is to avoid putting burden on cistomers in the ETL for data we're unlikely to use, and directing them towards data we are likely to use

**Comment by alanepaull** [comment]
Monday 19 Dec:
General consensus was that it could be used if needed by some, ignored by others.  Agreed to close.
