### ISSUE TITLE
Adding JACS3 subject vocabulary

### ISSUE THREAD

**Issue by wilmTap** [jiscdev/analytics-udd#131]
So far, JACS3 has been referenced in the UDD documentation, but not included. Because of its size, it was decided that we would include it as a linked CSV. The CSV is a copy taken from HESA, but stored here.

Warning: some institutions may try to include values of the form "B000" as a code for groupings such as "B - Subjects Allied to Medicine". These are not valid codes, or concepts to code with. I've checked the https://jiscv2.learninglocker.net/api/jisc/v1.2.5/ LRW, and have not found any codes of that type being used so far, however.

**Comment by alanepaull** [comment]
I've checked the HESA data that we had as part of the HECoS project, and records do contain codes of the form "B000", so they're valid for HESA purposes.  I mentioned yesterday that I didn't think they were valid (as they're not in the main JACS3 HTML listing on HESA), but they're in the CSV and the HESA data.

Are they valid for our purposes here?  I suspect they should be.

**Comment by robwynj** [comment]
Many Thanks for this.

I would agree that they are indeed valid – and I am getting HEIs providing these codes too.

Kind Regards

Rob

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; APMG PRINCE2 & APMG AGILE Certified Practitioner

Consultant – JISC Special Projects

email/ skype: rob.jones@jisc.ac.uk<mailto:rob.jones@jisc.ac.uk> mobile: 07468 727040

**Comment by wilmTap** [comment]
I did agree with you fully, then checked on the HESA website in various places and could only find CSV and HTML that did _not_ have any subject area codes. Checked again just now and they _did_ have them. So where that older CSV came from... ¯\_(ツ)_/¯ 

Anyway- thanks for the correction, all fixed now.
