### ISSUE TITLE
Datasets should indicate UDD version

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#138]
Although I think we should generally move OFF old versions of UDD as quickly as possible as new ones come on stream, once have moved to 1.3, it will be clear that there are incompatible data definitions IN USE for client data.

Hence: problems if we can't have a pretty good idea which version is in play.

I think it is important to get this into the automation/process as early as possible, ideally at the point of SRS-UDD mapping.

Suggestion: make the UDD self-declaring of its version, with a mandatory requirement for ETL to disclose what it thinks the version is via the CSV/TSVs sent for loading to the LRW. Additionally disclose this to clients of the LRW. Although this is not really an attribute of institution, a convenient place to put the schema version identifier would be in the INSTITUTION entity. Its a small uncomplicated thing to fetch/check before diving into the real stuff.

**Comment by alanepaull** [comment]
I suggest that we do something like this for 1.3.

**Comment by alanepaull** [comment]
Suggestion now in institution.md
