### ISSUE TITLE
Gender vs Sex - CHANGE GENDER fieldname to SEXID - APPROVED (UDD 1.2)

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#14]
Clarify whether UDD covers gender or sex. Current label is gender but the x-ref to HESA is actually sex.

**Comment by robwynj** [comment]
Hi Adam,

The field referred to is SEXID. We are calling this GENDER in the UDD - it covers GENDER and SEXID.

Kind Regards

Rob

**Comment by arc12** [comment]
Rob -
 I don't think a single field can cover both; they are different concepts.
See: http://style.ons.gov.uk/language-and-spelling/gender-and-sex/

Sex is more simple to deal with as a code list and would be preferable, I think.
See also:
https://www.hesa.ac.uk/component/content/article?id=2301?

Adam

**Comment by robwynj** [comment]
Hi Adam,

If renaming our field to SEXID or SEX is what your getting to, that's not a problem. What are you looking for specifically here....

Kind Regards

Rob

**Comment by arc12** [comment]
Yes, my point is that UDD should enshrine conceptual pedantry ;-)
Given such pedantry, a field is either sex or gender. In our case, I suppose sex is preferable.

Adam

**Comment by robwynj** [comment]
Happy to change, but classifications do not change. GENDERID can go into the UDD in future if required :)

Cheers

Rob
