### ISSUE TITLE
MOD_START_DATE notes "align" is not right

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#141]
The notes in S o M I
"The start and end date of a module_instance MUST align with the start and end date of a course_instance."

This is not true; a module may start during a course instance.

Maybe "align" should be replaced with "be consistent"

**Comment by alanepaull** [comment]
Do we need this sentence at all?  Is there any practical checking going on in relation to this - will it be implemented as a business rule, for example?  If not, then I suggest that we simply delete the sentence.  It's implied that module start and end date are included within the start and end date of a course_instance.  If it needs stating, then: "The start and end dates of a module_instance MUST fall at or between the start and end dates of a course_instance."
