### ISSUE TITLE
Student Course Membership - ID and SEQ

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#144]
To be cleaned-up.
Talk to Craig Petch @ Tribal

**Comment by alanepaull** [comment]
This is (at least) a SITS issue.  Is the suggestion that we concatenate these for v1.3 or v2.0.  Time scale may be important for this one, especially as it's a breaker.

Alan

**Comment by alanepaull** [comment]
From Monday 16 Jan call:

To be implemented for v1.3.

**Comment by arc12** [comment]
I move to include in v1.3.0

I think we are in agreement.

**Comment by alanepaull** [comment]
Agreed proposal is, when we create versions 1.3.0 and 1.3.1 in Github, to remove the property STUDENT_COURSE_MEMBERSHIP_SEQ from the following 4 entities in the v1.3 series:

- student_course_membership
- student_on_a_module_instance
- student_on_assessment_instance
- student_on_course_instance

In each case, STUDENT_COURSE_MEMBERSHIP_SEQ will not be present in the data, so will not be part of the primary key.

**Comment by alanepaull** [comment]
Now completed.
