### ISSUE TITLE
Descriptions of UDD entities

### ISSUE THREAD

**Issue by alanepaull** [jiscdev/analytics-udd#146]
Links to #145.

There is a description of assessment_instance in its .md file.  Other entitites don't have descriptions, and perhaps should have as an aid to understanding.  Unless I've missed the location of these, or it's been discussed and rejected, I'll have a crack at those (brief) descriptions.
Alan

**Comment by arc12** [comment]
@alanepaull Yes I am very much in favour of there being an explanation of the entities. The labels are liable to mis-interpretation and require too  much inference. I think this will be particularly important if UDD is to be adoptable across different sectors, where a functional description will be much more likely to be accurately interpreted than a label with roots in HESA returns.

**Comment by robwynj** [comment]
Agreed

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; APMG PRINCE2 & APMG AGILE Certified Practitioner

Consultant – JISC Special Projects

email/ skype: rob.jones@jisc.ac.uk<mailto:rob.jones@jisc.ac.uk> mobile: 07468 727040

**Comment by alanepaull** [comment]
I think there is a conflict (or at least potential conflict) over course and course_instance as currently implemented in the UDD.  This issue has been discussed earlier - looking back at closed issues, eg #55 - and may have been partly resolved or perhaps not resolved prior to github repository start.

As described in the UDD the course entity looks like an overarching programme validated for a period of several years, and course_instance looks like a 'course delivery' (in new HESA Data Language parlance), namely a particular presentation of a course with a specific start and end date that a student enrols on.  Then it follows that student_on_course_instance is data about a student taking a particular 'run' of a whole course.  This is how the current University of Jisc test data implements these entities, so for example we have a course_instance with a start date in 2014 and end date in 2017.

However, this is not how these entities are implemented for other institutions - although I've not yet seen the data, I believe that some (at least) of the SITS implementations use course as 'course delivery' and use course_instance as a stage of a course, typically an academic year.

I strongly suspect that there will be (or perhaps are already?) some problems with the meaning of other entities, if these differences are perpetuated.  I'm finding it difficult to describe entities adequately in the light of the potential differences here.

If there was a general adherence to the definition of course_instance as a stage of a course, then many difficulties of understanding would disappear, I believe.  There might remain a bit of naming issue, because UDD course_instance might be more properly labelled course_session, in line with the HEDIIP Data Language, and course might become course_delivery to make it all clear.

If there is a genuine difference in implementations in the data, then there is likely to be a problem with analysis and visualisations.

**Comment by alanepaull** [comment]
Monday 19 December:
There was a general belief, supported by SITS and other evidence, that there **is** general adherence to the definition of course_instance as a stage of a course.  Therefore, descriptions of entities should follow that line, which is generally the same approach as the HEDIIP Data Language documentation.  However, there was no appetite for changing the names of entities, but rather to make their meaning clear.

Roughly: 
course = course delivery (though it could be used for programme without much difficulty)
student_course_membership = student on a particular course delivery
course_instance = course session (stage of a course)
student_on_course_instance = student taking a particular stage / academic year, reported on and assessed / progressed from.

**Comment by robwynj** [comment]
Perfect

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; APMG PRINCE2 & APMG AGILE Certified Practitioner

Consultant – JISC Special Projects

email/ skype: rob.jones@jisc.ac.uk<mailto:rob.jones@jisc.ac.uk> mobile: 07468 727040

**Comment by alanepaull** [comment]
I have drafted UDD entity descriptions and put them in the main analytics-udd folder.  I envisage that, once agreed, they can be dropped into each MD file.  Each description has a "description" section and some have an additional "notes"section.

Question for @huwrobertsjisc : will this affect the validation tool?

Further question for those interested: do we need to retain a centralised file of these descriptions?  Pro: easier to look up. Con: descriptions would have to be maintained in 2 places.

Alan

**Comment by arc12** [comment]
Alan - 
great.... I'll take a close look at some point fairly soon.

Re the further question: one place feels better, to avoid problems of differing interpretation if things get out of sync. It would be neat if some automated method of generating monolithic documents for releases could pick and mix sections from the markdown. Consistent and distinct headings in the markdown should keep that option open. I think Wilbert and I both vaguely looked at Pandoc, but not enough to form a firm view. It might be quick enough to write some python to extract and combine elements from the various MD files and generate some MD output for running through a MD->PDF engine. We already have some python to extract the code lists, both Welsh and English variants.
