### ISSUE TITLE
VLE - UDD module/course identifier mapping

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#147]
This is really an issue which covers both UDD and the implementation of xAPI plugins generating the vle_mod_id extension value. It may be the resolution is a combination of UDD spec and which data is being picked up in the plugins.
(example: "http://xapi.jisc.ac.uk/extensions/vle_mod_id": "G9RR45 (F91511, F91611, F91711)" is from DumGal but is _prima facie_ tricky to resolve.)

The current state of affairs is "this was our best guess in advance of much real data"

We should review the reality in the light of more real data, including representation of different academic/qualification regimes (e.g. HE vs FE against QCF structures).

This is tricky!

**Comment by alanepaull** [comment]
Are we wishing to resolve this issue for v1.3?  It strikes me that if it is going to be (or *is*) a tricky problem, then we should consider it for v1.3.  That would be particularly important if it is likely to make v1.3 more difficult, and even more so if it will also make xAPI v1.0 more difficult.

So, time scale for 1.3 or 2.0?

**Comment by alanepaull** [comment]
Monday 30 January 2017: largely resolved in practice.  Close.
