### ISSUE TITLE
Add "Role of Field" in UDD Staff

### ISSUE THREAD

**Issue by amason** [jiscdev/analytics-udd#149]
Currently, the admin role is not accounted for in the UDD. Here at Unicon, we do have a work around to do a side load for admin users, but after talking to Michael, we do need to add a "Role of Field" in UDD Staff.

**Comment by alanepaull** [comment]
Monday 19 December:
There was considerable discussion.  The general feeling was that we should put Role (role of staff) on the staff_on_course_instance and staff_on_module_instance entities, as the role might be different in different circumstances.  The data might consist of a, hopefully small, vocabulary, for example, administrator, personal tutor, academic, and so on.  However, there might well be significant bespoke terms by individual institutions, which might be a problem.  We need ideas and example of usage.
For further discussion:  presumably this property would be for use within analytics; but can this purpose - "What is it for?" - be fleshed out?

**Comment by amason** [comment]
Hi - thanks for your explanation. I can provide you the 1 specific example/use case of what our need is and what our process is today and hopefully that will explain why we need the role of administrator associated to staff.

**Use Case**
This use case is specific for adding an administrator to SSP (Student Success Plan) at the institution level. At this time, only the SSP Student and SSP Coach (Tutor/Staff) roles are automatically loaded from JISC's UDD. To assist in manually loading other roles, SSP has a *stored procedure. Current SSP Roles for JISC are: Student, Coach, and Administrator. SSP Students and SSP Coach (Tutor/Staff) get loaded automatically based on the role coming over in the UDD, but since administrator is not a supported role, we must add each institution's administrators to the DB manually so they can manage SSP at their institution. 

**Manual Work Around Process**
To run the stored procedure, we must have primary identifying information for the person(s) needing to be added and access to the SSP database.

The steps to manually add a user to SSP (speaking specifically today about an administrator role) are as follows:

- The added user(s) must be in Shibboleth, which SSP uses for authentication. This step only sets up authorization which occurs locally in SSP's database.
- Then a user with DB rights has to log into the database through the bastion server.
- They then pull up a SQL query tool or run psql commands from the command line (SSP uses Postgres).
- They must then run the *stored procedure (below), substituting a user's details.
- Log out of the query tool and database.
- Use "Manage Users" and search for the user(s) and impersonate, or otherwise have the added user(s) login to SSP to verify success.


*Stored Procedure
--Copy to the sql query and substitute values in lower case:
SELECT addOrUpdateJiscUsersToPlatform('eppn', null, 'first', 'middle', 'last', 'phone', 'emailaddress', 'title', 'department', 'office', (TIMESTAMP 'dob'), 'photourl_link', 'role', 'jiscId', false);
--ROLE SHOULD BE ONE OF: "COACH, FACULTY, MANAGER, SUPPORT, or DEVELOPER"
 
--Example with minimum required data:
SELECT addOrUpdateJiscUsersToPlatform('duns', null, 'Duns', '', 'Johnson', '', 'duns@test.ukfederation.org.uk', '', '', '', null, '', 'ADMIN', '4000', false);


As you can see, this is a multi-step process that we (eventually Jisc will have to do once we transition in July 2017) have to do to add an administrator to SSP at the institution level. If the role of "administrator" were added to the UDD, we could bypass this process completely.

Let me know if this helps or of you need more details/further information.

@pspaude 
@alanepaull

**Comment by arc12** [comment]
We have no plans to undertake staff analytics or to account for staff role in student-centred learning analytics. So... the utility of role for us in managing authorisation, much as Amanda describes.
I can imagine that this would apply at multiple levels: STAFF and STAFF_ON_

The practical issue is likely to be that the info we might desire is not in the SRS.

As a matter of "good practice" I think UDD data extracts should avoid emitting STAFF who would not have access to learning analytics results (e.g. Teaching assistants), rather than rely on the downstream systems using exported role codes to exclude people.

**Comment by alanepaull** [comment]
Closed after discussions between Amanda and Michael.
