### ISSUE TITLE
COURSE tenant_id mandatory

### ISSUE THREAD

**Issue by alanepaull** [jiscdev/analytics-udd#151]
Current documentation says  0..1, but I think this must be mandatory [1] as it is foreign key for link to  INSTITUTION.

**Comment by arc12** [comment]
logically, yes, but in practice this is redundant since the LRW authorisation is partitioned by tenant, so authenitcating and fetching all courses will only ever fetch the courses from the same tenant as is identified in the INSTITUTION data acquired with the same LRW auth credentials.

**Comment by alanepaull** [comment]
Thanks, Adam.
