### ISSUE TITLE
Entity naming

### ISSUE THREAD

**Issue by alanepaull** [jiscdev/analytics-udd#153]
Consider consistency of UDD entity naming in relation to HESA and HEDIIP Data Language.

**Comment by arc12** [comment]
I'm not keen on the implication of changed names for the data handling code and LRW API. Being able to rely on the same names for API end-points and the CSV/JSON/TSV files which get passed around between institutions/Jisc/us.

I am keen on notes in the UDD which make potentially-qualified reference to the lexicons in use with funding and statistics functions in HE and FE.

**Comment by alanepaull** [comment]
I agree @arc12!  I wanted to note somewhere that there is an issue, which, I think, may be important for new entrants.  If they see naming that's potentially confusing in relation to terminology used elsewhere (and increasingly) in HE, we need a good way of making them aware of the UDD meanings.  I've put this as a 2.0 issue.  It's one of those things that, I suspect, won't go away, and we'll have to think of a good way to address it down the line.

**Comment by robwynj** [comment]
I would prefer consistent naming for the entities, as per the endpoints, in the UDD documentation from now on – always been an issue for me, and converting into the (in my view!) correct naming eg.

Studentassessmentinstance
Studentcourseinstance
Studentmoduleinstance

Etc

RWJ

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; APMG PRINCE2 & APMG AGILE Certified Practitioner

Consultant – JISC Special Projects

email/ skype: rob.jones@jisc.ac.uk<mailto:rob.jones@jisc.ac.uk> mobile: 07468 727040

**Comment by alanepaull** [comment]
@robwynj: if the naming in the implementation is different from the naming in the UDD documentation (which it is), then I can't see any reason why we shouldn't change the UDD documentation to match.

In case capitalisation is important, and for readability, I suggest EXACTLY like the live implementation, as returned from University of Jisc - this is all I have.  That would give us the following entity labels:

assessmentInstance
course
courseInstance
institution
module
moduleInstance
moduleVleMap
staff
staffCourseInstance
staffModuleInstance
student
studentAssessmentInstance
studentCourseInstance
studentCourseMembership
studentModuleInstance

We would need to add 'period'.

If this is going to be helpful, can anyone think of any reason why this change shouldn't happen?

Alan

**Comment by robwynj** [comment]
Hi Alan,

Looks good for me – drop the casing ideally – we have scripts to pick these up on the back-end ☺

Many Thanks

Rob

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; APMG PRINCE2 & APMG AGILE Certified Practitioner

Consultant – JISC Special Projects

email/ skype: rob.jones@jisc.ac.uk<mailto:rob.jones@jisc.ac.uk> mobile: 07468 727040

**Comment by arc12** [comment]
Chaps -
we have (I estimate) hundreds of references to the existing entity names in code and documentation, from initial ETL to data preparation. I'm sure other folks who have ETLs written will prefer stability too.

I'd rather not divert time to changing! TOO much else presses...

So long as there is no ambiguity between the LRW URL endpoint names and the documented entity names, I cant agree the tidyness of identical naming between API and documention warrants the pain of change. Devs are used to the API names differing from the documented/normal names for things; no problem if no ambiguity.

Also recall that some of the attribute names embed the entity name they FK to. And there are the markdown file names.

Earlier in UDD development, Wilbert made edits to ensure that we used consistent naming for entities, i.e. that the titles were canonical entity names.

I strongly propose:
- we retain the existing UDD entity names as the canonical entity names
- CSV/TSV/JSON file handling uses these entity names as file names (as preferred practice)
- LRW API endpoints remain as is
- the LRW UDD API documentation is amended to explicity list the available endpoints and the canonical UDD entitiy names they relate to

In relation to the last point, the answer is (I think):
 
>         'INSTITUTION': '/institution',
>         'COURSE': '/course',
>         'MODULE': '/module',
>         'MODULE_INSTANCE': '/moduleinstance',
>         'COURSE_INSTANCE': '/courseinstance',
>         'ASSESSMENT_INSTANCE': '/assessmentinstance',
>         'STUDENT': '/student',
>         'STAFF': '/staff',
>         'STAFF_ON_MOD_INSTANCE': '/staffmoduleinstance',
>         'STAFF_ON_COURSE_INSTANCE': '/staffcourseinstance',
>         'STUDENT_COURSE_MEMBERSHIP': '/studentcoursemembership',
>         'STUDENT_ON_COURSE_INSTANCE': '/studentcourseinstance',
>         'STUDENT_ON_A_MODULE_INSTANCE': '/studentmoduleinstance',
>         'STUDENT_ON_ASSESSMENT_INSTANCE': '/studentassessmentinstance',
>         'MODULE_VLE_MAP': '/modulevlemap'

**Comment by robwynj** [comment]
Looking good to me Adam ☺

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; APMG PRINCE2 & APMG AGILE Certified Practitioner

Consultant – JISC Special Projects

email/ skype: rob.jones@jisc.ac.uk<mailto:rob.jones@jisc.ac.uk> mobile: 07468 727040

**Comment by alanepaull** [comment]
Good.  That's very clear.  I don't think that we need to take any action in respect of the UDD documentation for this issue, unless I should be recording the endpoints there?

@robwynj: who is responsible for the LRW UDD API documentation?

Alan

**Comment by robwynj** [comment]
Hi Alan,

The UDD API documentation – good question – the API itself has been provided/ maintained by HT2. We need to implore to institutions that the entities provided for us in JSON/ XML format follow those naming conventions, because it avoids me having to rename them all the time when they come in! So we need to document and specify this information on github for our customers to note this.

Kind Regards

Rob


--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; APMG PRINCE2 & APMG AGILE Certified Practitioner

Consultant – JISC Special Projects

email/ skype: rob.jones@jisc.ac.uk<mailto:rob.jones@jisc.ac.uk> mobile: 07468 727040
