### ISSUE TITLE
Add DASH_SHIB_ID and default UK Test Fed users for blue UDD Staff

### ISSUE THREAD

**Issue by pspaude** [jiscdev/analytics-udd#154]
Amanda to continue testing, needs the UK Test Fed users (beth and duns) added to the current blue UDD data as Staff entities. 

She also needs the DASH_SHIB_ID to be filled out for the existing Staff entities in the blue data in order to test student assignments. The DASH_SHIB_ID for entities other than beth and duns can be anything or perhaps match username since they won't be able to login.

**Comment by michaelwebbjisc** [comment]
I've moved this one to: https://github.com/jiscdev/uoj/issues/3 as it's really about the UoJ set rather than UDD

**Comment by pspaude** [comment]
The beth UK Test Fed user has disappeared from the data list, this is the main user needed for Tutor testing.

**Comment by pspaude** [comment]
User id is beth@test.ukfederation.org.uk

**Comment by michaelwebbjisc** [comment]
Moved to https://github.com/jiscdev/uoj/issues/3
