### ISSUE TITLE
FE diversity of qualifications

### ISSUE THREAD

**Issue by alanepaull** [jiscdev/analytics-udd#157]
This issue is relevant to FE use of the UDD.  The issue describe here is part of our review of the potential use of the UDD in the FE context.  We invite everyone to comment.  Please use the filters, if you wish to skip FE issues.

Learners in FE study for a very diverse range of qualifications with highly varied structures for grading assessments and final results.

Current UDD structures cover what have become 'traditional' modularised HE provision. Students study courses that are made up of a specified pattern of distinct modules, where modules are Pass/Fail, with agreed grades or marks that are derived from an aggregation of weighted assessments.  Regulations prescribe the patterns of required grades or marks, as well as the passed modules required, for results at course level.

Many FE courses may be difficult to fit into this structure.  For example, for a unit in a BTEC course, the learner may have the opportunity for assessment at pass, merit or distinction level for performance criteria, where there might be 6 Pass level criteria, 3 Merits and 2 Distinctions.  Overall performance on this type of unit depends on fulfilling all the criteria at the achievement level, for example successfully completing all Pass level, all Merit level and only 1 Distinction level criteria, might earn a Merit overall.

There are other different patterns too, for example under the Apprenticeships banner that may not be easy to mold to the UDD structures.

However, we need to carry out more analysis to discover whether these FE structures are incompatible with UDD structures, and also whether these differences would impact on the LA results.  I don't think that the UDD and other Jisc LA functionality attempts to model the business rules for aggregating assessments nor for calculating final course results.  The UDD in this area is limited to recording assessments, overall module results, course stage progression and final course results, and this may be sufficient, as long as these different elements can be identified and used in analytics, both statistically and through detailed xAPI activity statements and recipes.

I think we'll need to carry out some testing in detail to measure the likely impact on the UDD of the diversity of FE qualifications.  This is work to be done.

**Comment by alanepaull** [comment]
Some FE college folk have expressed a desire to include awarding body changes to the learning analytics material.  This information would help to determine questions such as whether a change to an awarding body (for example from Edexcel to City & Guilds) results in changes to progression or achievement in the learning analytics.  In the current UDD, there is no explicit record of an awarding body, presumably because in the HE context the qualification associated with the course is awarded by the institution supplying the data.

In addition, a number of FE courses can lead to multiple qualifications, that is, on successful completion an individual student gains more than one qualification, sometimes at different levels.  The current UDD structure does not enable us to take this into account - multiple qualifications are much rarer in HE than in FE.

It would be possible to add an awarding_body property to the existing course entity.  In association with the existing course_aim property, this would give us some relevant information about the qualification to be awarded on successful completion.  In effect, we would be continuing the current practice of concatenating the concepts of course and qualification into the course entity.  However, this approach does not enable us to show multiple qualifications against a single course.  If this is considered to be important (particularly for FE users of the UDD), we would probably need to introduce a qualification entity - see attached diagram, also referred to in #156 Programmes of learning.

![udddiagram_fe_draft](https://cloud.githubusercontent.com/assets/17160871/22590641/098dc53c-ea08-11e6-8ad5-fd69b2157309.png)

**Comment by arc12** [comment]
1. Awarding body seems OK

2. Re multiple qualifications, we need to ask What would be done with the information?
There is a risk here that we deal with complexity which is not useful in practice.
For the HE cases, we generally resolve the detail of the HESA course aims down to something like "certificate", "masters", "hons". If we source data can be mapped, I suggest we'd get enough by differentiating vocational from academic and by level of the highest level qual.

3. I think we should investigate a lot more before adding programme to the entities. They add significant overhead for downstream processing.
In HE, the UDD Course probably IS a programme.

**Comment by alanepaull** [comment]
Re 2.:  It really depends what FE wants to get out of the analytics.  I haven't got a clear picture of this yet.  You may well be right, that we don't need the extra detail that a qualification entity would give us, especially as it would call into question the placing of 'course_aim' in course - it looks more like a qual_aim really, so if we had a qualification entity, it would more properly go there.  However, we're not trying to model provision, it must be a model of what's useful for analytics.  We (and FE folks too) would have to recognise the limitation here though.  If we added awarding_body to course, that would be a good addition, and I suspect, relatively pain free, even in the current master.  Mapping highest level qualification sounds like a good solution also.

Re 3.: This is the big one, and my proto-solution certainly looks like a major thing, because it's adding 2 new entities and linking to course in a way that may not fit with the current master.  I agree that we need more investigation.  I would just note that an HE "programme" is not equivalent to an FE "programme of learning".  An HE student usually takes only one course (and the UDD reflects that), whereas an FE student takes a panoply of different courses (typically one leading to a main qualification, another for English, another for Maths, sometimes a secondary or company-specific qualification too; and a range of non-course-like activities, that would be covered probably by xAPI statements).  In HE, the UDD course *could* be equivalent to an HE programme, but it could be other things instead (like a pathway or a subject option or a combined subject option).

We've tried to map programme of learning to the existing course structure.  You might get either:

(A) programme of learning == course; then FE course == course_instance (stage); but then your 2 year FE course cannot be broken down into its own stages or academic years, which looks important for progression by academic year (which seems to be how it's done conventionally).

Or alternatively:
(B) programme of learning == course; then academic year of an FE course == course_instance (stage); but then a 2 year FE course cannot be addressed as an entity at all, so progression on a course is more difficult to analyse.

If I had to choose, I'd probably go for (B).  FE college data that I've seen uses academic year as the main building block (like in HE), so we could map an academic year of an FE course to course_instance, which would be semantically correct.  Then we could reserve programme of learning to our course entity.  We could perhaps mark any course_instance that's in the main qualification as such.  For the final result of an FE course longer than 1 year, you could look at the latest (by academic year) course_instance.  In this model, course_instances would not necessarily be sequential - a student would have several live student_on_course_instance records in parallel, representing the current components of the programme.

We should check on the viability of these approaches by looking at more data.   Does the EBS stuff help here?

**Comment by craig-petch** [comment]
We do have access to some test ebs data now to use, but we need to find some time and look at how we best model such scenarios. From discussion the hierarchy of course structure may vary from site to site, so we need to get a handle on what that means in practice.  Understanding the outputs required for Analytics also seems to be important. We started the HE version with a relatively clear view of what such outputs needed to be, and agree I'm not sure we have a clear picture of that yet.

**Comment by arc12** [comment]
I move to include awarding body in v1.3.0
But to exclude other aspects of this issue.

**Comment by alanepaull** [comment]
Positioning of awarding_body depends on the mapping of programme of learning, FE course and FE course stage to the existing structure.  Programme of learning has no single awarding body, because it is made up of several courses.  If we adopt programme of learning == course, and academic year of an FE course == course_instance, then awarding_body sits with course_instance.  Other mapping suggestions might position awarding_body in the UDD course entity instead.

I currently favour putting it in course_instance.

**Comment by alanepaull** [comment]
The continuing discussion of this issue relates to #156.

As a result of mapping some real data to the proposed UDD course and course_instance structural mappings, we've identified a major difficulty.  We're using the idea that programme of learning == course, and academic year of an FE course == course_instance.  The difficulty is that we will not have enough data about the FE course in the LRW to enable us to know what it is.

For example, consider this type of question:  "How does students' current performance on GCSE English affect their performance on their main qualification?"  To look at this question, we'll need to identify the GCSE English and the main qualification.  These are both represented by course_instance records and their associated student_on_course_instance records.  The data items there do not contain the title of the course or its subject, so we don't know what they are - we only have their ID, start and end date, and the academic year.  Neither do they contain information that's important for FE analytics, such as level or credit value, so we don't have context for the data.  In HE usage, course_instance picks up the relevant title and subject from the course entity.  However, for FE, the course_instance can only pick up the title of the programme of learning, which doesn't enable the identification of a GCSE in English or a main FE qualification, such as a BTEC diploma.

A potential solution would be to add some more properties to course_instance.  These could be specifically for FE usage, or for use by everyone else too.  Relevant properties might be:

**title** - human readable identification of the course_instance, eg GCSE English, Animal Management BTEC Level 3 Extended Diploma, Year 1 - BSc (Hons) Mathematics

**level** - type of course in relation to a framework of courses and qualifications, eg "1", "2", "Entry 3".  Level _could_ have a sector-specific meaning, so "1" in HE means a credit level of 1, whereas "1" in FE means a level 1 qualification.

**credit_value** - number of credits awarded on successful completion, eg "90", "120".  The meaning of the credits (effectively the credit framework they come from) would be picked up from the course title or the level or both.  If the service needs more explicit reference to a credit framework, we would need a credit_scheme property.

**awarding_body** - discussed elsewhere.

**subject** - the topic of the course_instance (use same codes as course.subject?)

I would be interested in views on this one, because we need a solution before v1.3.0 is finished.

**Comment by arc12** [comment]
I don't like the idea of inflating course instance and distinctly changing its semantics.

Also I don't agree that " we need a solution before v1.3.0 is finished"; I think v1.3 IS the roll-up of (1.2 version-) breaking issues we can agree on now. More radical changes, especially ones which have not been exercised "in anger" and which would not be compatible with 1.3 should become 1.4 IMO.

Having said that, I accept that there is a use case here. We should question the premise that FE programme = UDD course, at least question its universality (it may be true in some cases). I recall I was a person who said that in general UDD course is a programme in HE, and I was not comfortable with the initial ideas for a programme entity which appeared to duplicate a lot of the aspects of course.
We should question the premise because it appears to be taking us into some deep water!

OK: crudely, what is the problem with students having more than one course going on at the same time. i.e. >1 SCM record active which refers to a different course? Each has a course-instance, but only one for a 1 year course.

**Comment by arc12** [comment]
Actually - I'm not convinced we need any treatment of programme-as-a-course-umbrella in order to make useful progress. In general, I think it is the smaller units (not being used in a technical sense) which are the most relevant to learning analytics, because they relate best to action-taking. Yes, the smaller parts contibute to the greater but if GCSE English is where the problem is then that is where to act. Ideally, we'd go down to topic level but that is beyond the data granularity. In HE, the final degree class is so far from knowing what action to take, it is pretty much irrelevant for LA. Much more relevant is module level success or failing to continue to the next stage.

**Comment by alanepaull** [comment]
Re "we need a solution before v1.3.0 is finished": I meant that, as things stand at the moment after trying to use the suggested solution to the issue of how to map FE courses into the UDD, it doesn't seem to work. So if we're trying to include FE in the ambit of v1.3.0, that may be tricky.

**Comment by alanepaull** [comment]
Sorry about the length of this comment.

The GCSE English was a simple use case to illustrate a point - it was intended to be a type of use case, rather than an overriding problem.

I don't think that we've given serious consideration (mapping data and so on) to NOT including the programme of learning somewhere.  FE colleagues that I've spoken to have all been very keen to include programme of learning.  Paraphrasing the reasoning: (i) much of the information relevant to value-added is currently viewed by FE through the lens of students on particular programmes of learning; it provides the holistic context of the analytics data; (ii) there are "non-course-like" entities, such as work experience, tutorials, enhancements, additional support, that are highly relevant to performance and value-added, but they're not directly related to a single course, but to the student on the programme of learning; (iii) it's a qualitative difference between HE and FE that FE colleagues might expect to see; (iv) bench-marking and initial assessments in English and Maths and other functional skills don't necessarily relate to a specific course.  As an example of (iv), a student may be assessed as having a high level of Maths ability, so doesn't need a Maths course - if we skip programme of learning, we may find that we have no data on this, so we don't know whether or not it's significant, when we analyse the data.

So, I certainly agree that we should "question the premise that FE programme = UDD course".  When I suggested that potential solution (and the corresponding FE course == course_instance), I very much had in mind that there were conceptual difficulties with this - they're not really semantically equivalent.

I suspect that you are correct that we could make useful progress without mapping in the programme of learning to the UDD structure - it would make it easier as well.  I would be interested in the views of FE colleagues on this.

In answer to your crude question above :), "what is the problem with students having more than one course going on at the same time":  At least from a theoretical stance, the UDD supports a student having multiple student_course_membership records.  The intention of this was, I think, to support students changing courses, and I guess, progressing from one course to another course.  In these cases, they are consecutive student_course_membership records, and we have the ACTIVE_MEMBERSHIP property to determine which course a student is actively studying on, the others .  I don't know if there are practical reasons why a student couldn't or shouldn't have multiple active student_course_membership records.  It's certainly implied that this is OK, because the Notes on student_course_membership state: "When updating student_course_membership records, the ACTIVE_MEMBERSHIP property may need to be updated on all records associated with one STUDENT_ID, not just one. The exception would be those cases where a student pursues more than one course simultaneously."

I think we need to map some data to check this would work.  It should give us a starting point.  Incidentally, it would also resolve a slightly smaller problem that we encountered: if we have programme of learning == course, then course_aim (a property of course) makes no sense, because it's only the individual courses that have course_aim.

If we can agree on this, then you're right, and v1.3.0 is a roll-up of the breaking issues we can agree on now.  Can I get out of the deep water now!?

**Comment by arc12** [comment]
I'm not sure getting out of the water is allowed, but catching hold of some passing bouyant material is, to keep us afloat while we work out which way to swim to get to where the land is.

**Comment by craig-petch** [comment]
Ideally if we can finalise 1.3.0 imminently that would help us greatly with existing users and then give us a bit more clear space to evaluate this without impacting existing work and ,as you suggest, model what is required and workable with some real data. Also if we could agree the extension methodology for 1.3.0 onwards that would give us sufficient flexibility to include programme level attributes where necessary, albeit not  the longer term solution.  

From memory the UDD quickly moved forward from a HE perspective when we started to try to utilise the original conceptual model with STUDENT_COURSE_MEMBERSHIP quickly being identified and added. It feels like we are in a similar place at the moment for FE. I think we can handle multiple SCM records, in the UDD at least, so for example an Student on AS/A2 quals would have multiple SCM records plus any other activity that we could bundle in as a "course".  The over-arching programme could be described by using an INST_TIERx value or the Cohort_ID attribute. This would be somewhat disjointed and just a label, and any additional FE attributes that don't comfortably fit into the existing entities would need to be extensions and may not perfectly align with existing UDD entities.

So for 1.3.0 I think we can get something that would function and provide the "passing buoyant material" and then we can better "locate the land" post 1.3.0 to poorly continue the above analogy.

**Comment by arc12** [comment]
+1
One thing I am not clear about is the number of distinct FE Programme titles there would be at a typical FEI, Also the extent to which these are stereotypical route-types (e.g. NVQ3, A-levels, Apprenticeship) or named after the principal course (e.g. NVQ2 Motor Vehicle).

In either case, we should be able to use some lightweight additional attributes on SCM to clarify how multiple courses should be viewed in a FE Programme setting, but the way of doing it depends on which way they are viewed (or another)

**Comment by alanepaull** [comment]
I'll move on with getting v1.3.0 in a state where we've recorded our previous areas of agreement, so that we can, in theory, have a stable version.

**Comment by alanepaull** [comment]
This comment also applies to #156, but I've put it here, as much of the discussion has been held in this issue.

For v1.3.0, we will map FE course to the UDD course entity, and FE course stage (usually academic year) to the UDD course_instance entity.  This means that we amend the proposed FE additional optional properties to:

course
    AWARDING_BODY

student
    PRIOR_ATTAINMENT_ENGLISH
    PRIOR_ATTAINMENT_MATHEMATICS
    INITIAL_ASSESSMENT_ENGLISH
    INITIAL_ASSESSMENT_MATHEMATICS

student_course_membership
    PREDICTED_OUTCOME
    ATTAINMENT_TARGET

I will add these properties to the MD files for review.

Any additional properties can be handled via extensions in the first instance.

**Comment by alanepaull** [comment]
These have now been amended as follows (see #171 and #170 for rationale):

course
AWARDING_BODY

student_course_membership
PREDICTED_OUTCOME_GRADE
ATTAINMENT_TARGET_GRADE
PREDICTED_OUTCOME_MARK
ATTAINMENT_TARGET_MARK
PRIOR_GRADE_ENGLISH
PRIOR_GRADE_MATHEMATICS
INITIAL_ASSESSMENT_ENGLISH
INITIAL_ASSESSMENT_MATHEMATICS

See the relevant MD files for details.
