### ISSUE TITLE
Student on Module Instance - MOD_AGREED_GRADE, MOD_ACTUAL_GRADE etc. - TBC (for UDD 1.2)

### ISSUE THREAD

**Issue by robwynj** [jiscdev/analytics-udd#16]
As per recent discussions (Craig Petch, Basecamp, Nov 2015) - we need to have potentially 2 changes to the UDD within SOM.

https://basecamp.com/2737506/projects/10136653/messages/51489581

Therefore:

MOD_AGREED_GRADE
MOD_ACTUAL_GRADE (supercedes our current StudentOnModule.MOD_GRADE)

Also, possible requirement for the following (Tribal, let me know your views on these too):

MOD_AGREED_MARKS
MOD_ACTUAL_MARKS

With the above proposed MARKS fields, I assume we would also need a MAX_MARKS field?

Let me know what you think?

Kind Regards

Rob

**Comment by arc12** [comment]
I'm currently using both marks and grades, and the actual/agreed is potentially useful. I don't need max marks.

We also look at attempt counts, and (although I'm not using it at the moment) access the first attempt mark. More on those when we've discussed our proposals.

Adam

**Comment by robwynj** [comment]
Thanks Adam. Ideally want to get this change into UDD 1.2. Feel free to feed your collective high-priority items into this list, so we can discuss and get those in too if feasible.

Kind Regards

Rob

**Comment by wilmTap** [comment]
Shall I add the following to Student on a module Instance, then?

MOD_AGREED_GRADE
MOD_ACTUAL_GRADE (supercedes MOD_GRADE)
MOD_AGREED_MARKS
MOD_ACTUAL_MARKS

**Comment by robwynj** [comment]
Hi Wilbert,

Yes, I would say so. Adam?

The more I think about it, we will also need this for GRADE entity too. Wilbert, I think we need to review and revise the GRADE entity too in any case - it's too vague IMHO.

Let me know what you think.

Kind Regards

Rob

**Comment by arc12** [comment]
Yes, that matches what we've been working on, including the revision of GRADE (which might benefit from a renaming with its make-over),

This will be covered in the forthcoming doc from Tribal...

Adam

**Comment by robwynj** [comment]
Thanks Adam. Wilbert - let's touch-base on the GRADE entity and go through it in alignment with Tribal feedback too.

Kind Regards

Rob

**Comment by wilmTap** [comment]
OK, I'll do the #17 merge, and then wait for the Tribal pull request.

**Comment by wilmTap** [comment]
Refactoring proposed by Tribal:

> The GRADE entity requires more detail adding to allow us to effectively analyse the Assessment component detail that an institution may store in their SRS. We propose decomposing the existing GRADE entity into two new entities:
> ASSESSMENT_INSTANCE - stores details of assessment at the module instance. STUDENT_ON_ASSESSMENT_INSTANCE - stores details of a student's assessment marks and grades for a module instance, a student can have multiple records for an assessment instance depending if they have had to resit that assessment.
> Assessment Instance will provide details of the type of assessment component used (exam, course work etc), the weight/percentage that the assessment component counts to the overall Module mark. and also brief detail of the assessment that provides a bit more explanation of what the assessment was (e.g. Lab report 3000 words).

**Comment by wilmTap** [comment]
student_on_assessment_instance.ASSESS_DUE_DATE; is that the due date initially planned and agreed, or the last known due date (after cross-module or student specific extensions)? It seems worth clarifying in the definition.

**Comment by robwynj** [comment]
Hi Wilbert,

RE: your comments:

On "Student On Assessment Instance" Detail - correct, thus field should be indicated as ASSESS_INSTANCE_ID (currently can only see ASSESS_ID in there) - so just a naming issue!?!

ASSESS_DUE_DATE = optional field - use if HEI/ FEI has it;

ASSESS_ACTUAL_MARK = first mark given.

@arc12 - Adam can you clarify for ASSESSMENT_CURRENT/COMPLETED_ATTEMPT?

Kind Regards

Rob

**Comment by craig-petch** [comment]
Hi All, 
The current and completed attempts are counters of the how many attempts a student takes on an assessment instance. The current is included to capture the number attempts whilst the assessment instance is still in progress as the completed will be set to 0 at that stage. So would/could be valuable when we start to take incremental updates and this data is still being completed by the institution.  Admittedly this is still early days with this so we will find out how useful this one is (or not) in due course but for the moment we will be collecting it.
Regards
Craig

**Comment by wilmTap** [comment]
I think  assessment_instance.ASSESS_INSTANCE_ID v.  assessment_instance.ASSESS_ID is indeed just a naming issue. I've changed them all to ASSESS_INSTANCE_ID now

I've changed student_on_assessment_instance.ASSESS_DUE_DATE to be optional now. I've left it ambiguous enough for an institution to decide exactly what due date they mean.

Changed student_on_assessment_instance.ASSESS_ACTUAL_MARK definition to "The initial mark given for the assessment attempt."

I'm wondering whether student_on_assessment_instance.COMPLETED_ATTEMPT could be turned into an assessment outcome attribute, since 
student_on_assessment_instance.ASSESSMENT_CURRENT_ATTEMPT=5 && student_on_assessment_instance.ASSESS_OUTCOME=pass 

is the same as 
student_on_assessment_instance.COMPLETED_ATTEMPT=5 && student_on_assessment_instance.ASSESSMENT_CURRENT_ATTEMPT=5

But it doesn't matter a great deal at this point, so I've left it as is.

**Comment by wilmTap** [comment]
Will currently leave student_on_assessment_instance.COMPLETED_ATTEMPT #28 but make a proposal for student_on_assessment_instance.COMPLETED_OUTCOME

We know DUE_DATE (Due Date, Entered Data, Actual Date) will have to be expanded, but we'll leave it as is for now. 

Same for mark history

**Comment by robwynj** [comment]
Wilbert - as an aside, in the UDD ASSESS_DETAIL is in there twice - can you remove, Cheers :)

**Comment by wilmTap** [comment]
Fixed now
Thanks for catching that slip-up. Feel free to hit the 'edit' button on the document and stick the fix in your own branch if you think that's more convenient!

**Comment by wilmTap** [comment]
Tribal to report back on ASSESSMENT_RESULT

**Comment by craig-petch** [comment]
Hi Wilbert - Sorry, some belated feedback on the proposal to remove Completed_Attempt from SoMI so we can close off UDD 1.2. In short I think we can and agree that it will fit better with other SRSs. I also recognise that it will be consistent with the configuration for SoAI and the addition of the Assessment_Result attribute. For both entities using the x_RESULT and the addition of code 3 (not completed yet) along with x_CURRENT_ATTEMPT should work well.
