### ISSUE TITLE
removal of deprecated attributes in v1.3

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#162]
There are a few depecated attributes in 1.2

Propose these be removed from 1.3

From memory:
YEAR_COM
MOD_GRADE
WITHDRAWAL_DATE

**Comment by arc12** [comment]
Also check the code lists for deprecated codes.

**Comment by alanepaull** [comment]
@arc12 I'll sort these as I prepare for v1.3.0...

**Comment by alanepaull** [comment]
Removed and will be committed with other changes to MD files.
