### ISSUE TITLE
Denormalise ACADEMIC_YEAR into SoCI

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#164]
I think this may have been discussed, but maybe not.

In the interest of efficient data joining, it would be helpful to have the academic year on SoCI as well as CI
If, for example we are only interested in the current academic year, we end up having to load SoCI for all AYs in the data.

**Comment by alanepaull** [comment]
ACADEMIC_YEAR added to SoCI.  Will be committed when other changes to MD files are committed.

**Comment by alanepaull** [comment]
In addition, as requested on Monday 13 Feb meeting, X_MOD_ACADEMIC_YEAR in SoaMI has been amended to MOD_ACADEMIC_YEAR, so it matches module_instance.md#MOD_ACADEMIC_YEAR. Will be committed when other changes to MD files are committed.
