### ISSUE TITLE
Suggested added notes for MOD_CREDITS

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#165]
Suggest to amend the notes with:
"If modules have  credit value, that should be used. In cases where no credit value is available but where some modules are either for-credit or not-for-credit, then MOD_CREDITS may be set to 1, or 0, respectively."

**Comment by alanepaull** [comment]
I can see the logic of MOD_CREDITS = 0 meaning not-for-credit, but isn't MOD_CREDITS = 1 meaning 'unknown credit value' slightly misleading?  If MOD_CREDITS is used for calculation, the '1' value will give wrong results; presuming that somebody won't check the spec :).  I suggest that it might be better to leave it blank if the value is not known.

**Comment by arc12** [comment]
@alanepaull I'll try to be more clear...
In situations where it is known that some modules are "for credit" and others are "not for credit", but the actual credit value is not known, MOD_CREDITS may be treated as a binary value, but this must be done consinstently; credit-value and binary values should not be mixed.

The issue here is to allow the use of this attribute to be either a binary OR a credit-value.

**Comment by alanepaull** [comment]
Is it safe to mix the meanings of this property?

It might be better to have another property CREDIT_BEARING with these values: 

0 - not for credit
1 - for credit, see MOD_CREDITS and MOD_LEVEL for details.
2 - for credit, but credit value unknown.

**Comment by arc12** [comment]
I'm easy and TBH, this has not emerged in data we've been handling.

**Comment by alanepaull** [comment]
Monday 13 March: we agreed that for v1.3.0, we would have just Clearing or not Clearing.  Any more sophisticated stuff can be considered for v1.3.1.

**Comment by alanepaull** [comment]
Sorry  - wrong issue!  Will post in the proper place.

**Comment by alanepaull** [comment]
Monday 13 March: agreed to implement CREDIT_BEARING, as above.
