### ISSUE TITLE
Dealing with Course Changes

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#167]
Being able to understand a history of course changes is potentially useful as an indicator of future success/risk.

Student Course Membership accommodates this but there are two imperfections:

1. Documentation.
a) entity scope
The current entity description is "A student_course_membership describes a student's enrolment on a course. It is designed to deal with the fact that some students are enrolled on more than one course in their time at an institution."
Propose: it should clarify that SCM accommodates simultaneous enrolments and a history of course changing. More than this: that the historical record of course changes should be transferred via UDD.
b) Propose that the documentation should indicate that the appropriate WITHDRAWAL_REASON code for internal transfer must be used for course changes (with the COURSE_END_DATE set accordingly)

2. Attribute
In the scenario where there may be more than 1 course active at  given time, and there has been a course change in one of them,the current data structure on SCM does not allow us to determine in a reliable way which one the change relates to.
Propose: SCM be amended to include an optional attribute to indicate the STUDENT_COURSE_MEMBERSHIP_ID *from which* the student transferred.

**Comment by arc12** [comment]
re 2, we might want to consider whether transferred-from COURSE_ID is better here.
For example, there may be some lower-significance changes in route or some administrative aspect which still leaves the student on the same titled course, but some other changes which are real course changes (e.g. Maths to Land Studies) and hence more likely indicative of outcomes...

**Comment by alanepaull** [comment]
Can we set a priority for consideration for this?  Is this a v1.3.1 issue?

**Comment by arc12** [comment]
no 2 is 1.3.1 or higher. The issue arose from our data processing work; there is real basis, but some investigation into actual data available is needed before propagating to documentation.

i think the documentation changes could go in 1.3.0

**Comment by alanepaull** [comment]
The relevant issue in relation to v1.3.1 is:

In the scenario where there may be more than 1 course active at given time, and there has been a course change in one of them,the current data structure on SCM does not allow us to determine in a reliable way which one the change relates to.
**Proposal**: SCM be amended to include an optional attribute to indicate the STUDENT_COURSE_MEMBERSHIP_ID from which the student transferred.

to be discussed

**Comment by alanepaull** [comment]
Monday 24 April: Agreed to add an optional attribute to SCM, but this attribute to contain COURSE_ID identifying the course from which the student transferred, not STUDENT_COURSE_MEMBERSHIP_ID.

**Comment by alanepaull** [comment]
Monday 5 June 17: Agreed to add into v1.3.1 (inadvertently missed out). Slight change to Purpose for clarity to: 

"This property indicates that a student has transferred from 1 course to another, by identifying the course from which the student transferred."
