### ISSUE TITLE
Compound keys as unique identifiers for URLs

### ISSUE THREAD

**Issue by ht2** [jiscdev/analytics-udd#169]
Hi all,

We've been keeping an eye on the discussions in #74 which all looks really good - we're on board and are starting to build this into the new 1.3.0 UDD which will be built on top of an RDB. I like the idea of using the tilde `~` as a reserved character to resolve to a unique entity... which made us have some thoughts about if we could use this to reference the entities across the board, specifically when GETng or POST/PATCHng to a specific model.

The main need for this is that we will no longer be creating arbitrary database IDs for each model, therefore when making an API call we need a way to reference the models. Therefore, we could use this compound key as part of the URL:

So, to borrow @alanepaull's example from #74, in the case of a `STUDENT_ON_COURSE_INSTANCE_ID` with `xxxxx` as the `STUDENT_COURSE_MEMBERSHIP_ID` and `yyyyyy` is the `COURSE_INSTANCE_ID`, we would expect RESTful urls of...

```
GET /api/jisc/1.3.0/studentcoursemembership/xxxxx~yyyyyy
PATCH /api/jisc/1.3.0/studentcoursemembership/xxxxx~yyyyyy
DELETE /api/jisc/1.3.0/studentcoursemembership/xxxxx~yyyyyy 
```

This has the added benefit of us being able to use this key to create foreign relations between the `extensions` table and the models, where an extension is inserted with [`REF_KEY`](https://github.com/jiscdev/analytics-udd/blob/v1.3/extension.md#ref_key).

The only thing that even puts this up for debate in my mind is the choice of the tilde `~`, specifically as it would require URL encoding, meaning that our `xxxxx~yyyyyy` ID would actually need to be encoded to `xxxxx%7eyyyyyy`; not quite as human readable, but by no means an issue.

(As a complete side issue, I did some light research into the need to encode the tilde in URLs, it seems to be a mixed bag, with some systems happy to accept it without encoding, but [RFC 1738](http://ftp.funet.fi/pub/doc/rfc/rfc1738.txt) is quite explicit about it being an "unsafe" character, and as such I would propose it was treated as such.)

If there was appetite to use a URL friendly delimiter, then choices are pretty much limited to `_` and `-` which I can only presume could well conflict with values allowed in some of our UDD primary fields?

How do people feel with this as a way forward for the API?

**Comment by craig-petch** [comment]
Hi James, I like the proposal it would certainly make the process of patching the data an easier process.  The use of tilde was something  that we've used before as a delimiter, but not more from a db perspective rather than a URL use case. The option of _ or - could be risky in terms of they could slip into codes but maybe we can investigate that in the data we have and review that.

A further possible issue of the concatenation is some of the coding conventions in the SITS student records system. For example the Student Course Membership ID will be Student_Code/Course Sequence so a code of 123456/1 would the use of the slash in the code cause issues or would URL encoding handle that ok? If not would we need agree some rulings to what that characters are allowed in that concatenated key for use in the URL?

**Comment by ht2** [comment]
@craig-petch Any `/` in an ID value would need to be URL encode, so for your example, if the STUDENT_COURSE_MEMBERSHIP_ID was `123456/1` and the COURSE_INSTANCE_ID was 45678, we'd expect to see a GET url of....

```
GET /api/jisc/1.3.0/studentcoursemembership/123456%2f1%7e45678
```

**Comment by arc12** [comment]
I am a little cautious about these ids getting meaningful structure. I think there is risk of error if people end up compsing identifiers by string operations, in order to retrieve or relate instances of data. Also that we risk painting ourselves into a corner if UDD needs to change.

It may be that, at some point, a surrogate PK is created by delimited contcatenation, but once it is created, I think we're safer treating it as an opaque identifier for the record. By the same token, so long as the source can manage it reliably, these may not be formed by concat but just be an auto-increment integer. in a PUT scenario, it really shouldn't matter so long as the URL encoding implications for GETing are understood.

In terms of overcoming the URL encoding issue: maybe the use of base64 encoding or an MD5 hash of a tilde-separated concatenation would solve the problem.

**Comment by craig-petch** [comment]
We generate a surrogate PK that's (Big) integer based in the source data for SITS sites and for all UDD entities so that could be passed. Using base64 encoding could work nicely too.

**Comment by alanepaull** [comment]
For clarity: are we suggesting that the source can produce an auto-incremented integer as the PK for entities with composite unique constraints?  If it is OK that, where desired, the source produces (effectively) any suitable single field PK, then I should amend the README to cover this.

It seems (to me at least) that this may be overly confusing to the uninitiated.  Wouldn't it be preferable to have the PK generated EITHER by the source OR by the loading process?  And perhaps it ought to be EITHER composed of the unique constraints OR not. I'm content with this complexity, if (i) there's a good rationale, (ii) it won't get in the way of practicalities, and (iii) I can describe it simply in the documentation.

Current text in README:

###Primary keys
Some entities have uniqueness constraints across multiple properties; for example student_on_course_instance has STUDENT_COURSE_MEMBERSHIP_ID plus COURSE_INSTANCE_ID. The MD files for these entities contain a note to this effect. For ease of processing and to enable field-level extensibility, these entities have a primary key that consists of a concatenation of the components of the composite key separated by a tilde (~).  **The tilde (~) is therefore a reserved character and must not be used elsewhere in these values.**

Where this type of primary key is not provided by the data supplier, the LRW loading mechanism will create it. For example: the student_on_course_instance entity's primary key consists of:
'''xxxxxx~yyyyyy
where xxxxxx is the STUDENT_COURSE_MEMBERSHIP_ID, ~ is the tilde reserved character, and yyyyyy is the COURSE_INSTANCE_ID.

Other entities have a conventional primary key.

**Comment by ryansmith94** [comment]
Hey @craig-petch @arc12.

### RE: URL Encoding
It's probably useful for the IDs to be human readable.

### RE: The Actual Problem
Requirements:
1. A solution that allows primary keys to be added later.
2. A solution that doesn't require tracking of IDs generated by the LRW.
3. A solution that allows extensions to reference a model.

Assumptions:
1. Extensions will not be created before the model itself or the model could be created upon creation of the extensions.

Proposed solution:
1. The LRW generates IDs for models and uses this internally to reference extensions.
2. The LRW exposes an API to retrieve the first model matching a query.
    `GET api/jisc/1.3.0/studentcoursemembership/first`

**Comment by alanepaull** [comment]
Would have put the tilde character in my comment above, but it seems that it's a reserved character in markdown :).
'''~

**Comment by arc12** [comment]
@ryansmith94 - "human readable" = can be read out over the phone and reliably transcribed? It doesn't have to mean anything, be intelligable... just like my high entropy passwords.

There is advantage in having PUT as well as POST semantics on id creation because it makes it easier for a source data system which is capable of doing its own book-keeping about what needs to be added/updated.

Adam

**Comment by ht2** [comment]
@arc12 I think what Ryan meant by "human readable" was that by looking at the URL you could establish which model was being referenced without having to do any form of decoding on the fly

So...
`GET api/jisc/v1.3.0/studentcoursemembership/XXX%7eYYY`
vs (if using base64)
`GET api/jisc/v1.3.0/studentcoursemembership/WFhYfllZWQ==`

**Comment by ryansmith94** [comment]
Looking at the [current state of the v1.3 branch](0bc59fcfc4fcb6e45bd6ac1ef16bb05ad1f3c94d) with the exception of the [student_id_map model](https://github.com/jiscdev/analytics-udd/blob/ae66f93/udd/student_id_map.md) every model seems to have a single primary key.

Therefore, if we can add a single primary key for the student_id_map model, each model could have an API like `example.com/api/jisc/v1.3.0/{model}/{primaryKey}` in the LRW. For example, for the [assessmentInstance model](https://github.com/jiscdev/analytics-udd/blob/ccb9bd4/udd/assessment_instance.md) where the primary key is `ASSESS_INSTANCE_ID`, the API endpoint would be `example.com/api/jisc/v1.3.0/assessment_instance/{ASSESS_INSTANCE_ID}`.

Additionally, the primary key can be used as the foreign key referencing the model in the LRW's extensions table.

### Questions
1. Are these primary keys going to be generated outside of the LRW?
2. Can we add a primary key to the student_id_map model?
3. Is it ok to use the primary key as the foreign key referencing the model in the LRW's extensions table?
4. Is it ok for each model could have an API like `api/jisc/v1.3.0/{model}/{primaryKey}`?

If the answers to the last 3 questions are yes, this issue can be closed and I can start implementing that. If the answer to question 2 is yes we may need to create a new issue.

**Comment by alanepaull** [comment]
My understanding of the proposed plan is as follows:

1. The single unique identifiers where we have a composite primary key (like in student_course_instance) **may** be supplied by the data provider.  If not, they **will** be generated by the LRW as part of the loading process.  Other primary keys **must** be supplied by the data provider.

2. If it's needed, I don't see why we couldn't have a single unique identifier for the student_id_map.  Logically, that should have the same supply/generation as in 1.

3. A major reason for having these primary keys was for referencing the extensions.

4. I don't see why this shouldn't be implemented; it strikes me as an obvious addition.

**Comment by ryansmith94** [comment]
Awesome thanks @alanepaull! 👍

**Comment by ryansmith94** [comment]
To be clear

1. We can also construct the unique identifiers (like: `STUDENT_COURSE_MEMBERSHIP_ID` and `COURSE_INSTANCE_ID`) from the primary keys (like `STUDENT_ON_COURSE_INSTANCE_ID`) once we understand how they can be constructed.
2. Yeah it's needed in order for the API in question 4 to work for that model.
3. Awesome, we'll use that as the foreign key then.
4. We'll add the API I proposed in question 4.

Note: By "we" I mean the LRW.

**Comment by ht2** [comment]
Hi all,

So just to level the field, I initially didn't realise you had implemented _named and defined_ primary keys for these compound values that would be stored, hence I wanted to be sure on the formatting! I can now see that field names such as `STUDENT_ON_A_MODULE_INSTANCE_ID` exist so that sounds absolutely fine. We were initially going to store these as just `ID` on each table as a hidden field that we would use to map the extensions to, so this works out fine now that they are a defined and exposed field!

@alanepaull: 
* I like the idea of the LRW auto generating these values on input if not already passed by the data provider, however we would ensure that the LRW would also validate them if passed in to ensure they matched the construction rule.
* Yes, if we could have an ID on student_id_map that followed the same rules as the others that would be great. 

As such I think we can close this off - @ryansmith94 and I feel confident enough to move forward and finish up the last bit of work on the relational UDD implementation and get you guys in and playing with it before too long!

**Comment by alanepaull** [comment]
Have a look at the further comments on #172.  It may not be as clear cut.  My understanding from @arc12 is that these single unique identifiers might not have to follow the construction rules - Tribal wanted some flexibility, for example maybe to implement auto-numbered PKs.  Also, there is value in having an opaque primary key; or rather, there is danger in having a PK with an ostensible meaning, over and above the indexing.

It would be very important to get @arc12 and @craig-petch views on this.

**Comment by arc12** [comment]
"validate them if passed in to ensure they matched the construction rule."

Could you outline the rationale for this?
Is it not "just an identifier"?

Adam

**Comment by craig-petch** [comment]
We will be generating some pretty ugly single primary keys from the SRS/SITS system for example on STUDENT_ON_ASSESSMENT_INSTANCE we'll get something like - "12345678/1~MODULE101*A*ABC*2016/7*SEM1*ASMTCODE101*0.600000*002~1".  Whilst usable there is an argument that a surrogate numeric primary key could be easier to manage.  If we were to use surrogate keys however we I would assume we need to enable a surrogate key for the current single primary key based entities too so maybe that's more complexity?

**Comment by ht2** [comment]
@arc12  - I was still under the impression of the concatenated values being taken together to make the single primary via a rule enforced by the UDD. If thats not the case (@alanepaull has mentioned you might want to set your _own_ primary key values) then I'm absolutely happy that this value isn't validated to a particular rule.

However, I am a bit confused right now as to what everyone wants this value to be. @arc12 are you saying that _you_ (Tribal) want to be able to set this value, but only sometimes? And when you don't set it, that the LRW comes up with its own unique (incrementing perhaps) value for that primary key? 

One thing to note that @ryansmith94 has just noticed; the char limits on all these primary keys is 255, which clearly wouldn't be enough to concat multiple instances of other char limited 255 keys together. At that point, a fixed length hash starts to make sense to ensure we can limit to a sensible field size, base64 less so as it still has the ability to go far beyond 255 chars available.

**Comment by alanepaull** [comment]
Monday 13 March proposal: Concatenated IDs are going to be horribly big and ugly, and probably not easily human readable; they may also cause maintenance issues for institutions.  The proposal now is that, for entities with composite primary keys, EITHER the data provider creates a single unique STRING (255) primary key in their own store and supplies it, OR the LRW will create the single unique STRING (255) primary key.

The primary key should be used as an opaque ID, regardless of any implied content.

We need to check with HT2 colleagues about any unforeseen practical implications.  @ryansmith94 or @ht2 : please comment!

**Comment by ht2** [comment]
Hi @alanepaull - completely on board with this. We'll move to implement right away. 

For the record, we will look to generate [UUID (v4)](https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_4_.28random.29) identifiers when required e.g. `00c29fdc-08a7-11e7-93ae-92361f002671`.

**Comment by alanepaull** [comment]
I've changed the note in the README to:

"**Primary keys**
Some entities have uniqueness constraints across multiple properties; for example student_on_course_instance has STUDENT_COURSE_MEMBERSHIP_ID plus COURSE_INSTANCE_ID. The MD files for these entities contain a note to this effect. These entities have a single primary key for ease of processing and to enable field-level extensibility. The data supplier may choose to provide the single primary key, or may choose to leave it blank, in which case it will be generated by the LRW loading mechanism."

I am amending the description on the primary key property on each entity of this type to read:

"Primary key. Where not supplied by data provider, the primary key will be generated by the LRW loading mechanism."

**Comment by ryansmith94** [comment]
I think this can be closed now @alanepaull
