### ISSUE TITLE
v1.3.0 "Primary Keys"

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#172]
I have some residual discomfort with the current wording around the single-field keys we have identified as being in scope for v1.3.0. I think we should keep the idea but amend the documentation.

Minor nit: "the primary key will be UDD generated." should refer to the LRW (the software system) rather than UDD (the specification).

I think it would be prudent to remove reference to identifier concatenation from the "Format" section, to avoid us being hostage to fortune. It MAY be the case that the autogeneration follows the rules in the current draft, but I think that is not necessarily going to be the way... and I think it should not be enforced on data providers.

If we want to keep options open for using tilde characters then the documentation of all IDs which could be part of a compound key should have a note to say tilde is not a permitted character.

For those entities which have had a surrogate PK added, it wouldn't harm to expand the description of its purpose as to uniquely identify the record by a single identifier as an alternative to {... list the unique identifiers...} to ease data management. I mean to make clear the relationship between it and the more natural keys.

**Comment by arc12** [comment]
Futher...

these surrogate PKs are indicated as being mandatory by [1] but they are described with "where not supplied by the data provider".

These appear to be incompatible.
I think it will cause less confusion if denoted [0..1]. Specifically, Jisc's ingestion-stage validation will treat this as [0..1].

**Comment by alanepaull** [comment]
Hmm.  I understand what you mean.  However, it looks very odd to have a PK as [0..1].  If the UDD is, in fact, a specification for the import of the UDD data from a source, rather than a specification of the UDD content in the LRW, then I can see that meaning.  I think I would prefer a form of words that covers both cases clearly, because the UDD spec might well be referenced by different groups.

Alongside the [1] meaning mandatory, the current wording is: "Primary key. Where not supplied by data provider, the primary key will be UDD generated."  Is this confusing?

The alternative would be: [0..1] "Primary key. Where not supplied by data provider, the primary key will be UDD generated."  If we had this shown as optional (for example in our list of mandatory fields), might there be the chance that this could be overlooked by someone reviewing the UDD content in the LRW?

Happy to revise the documentation with standard text as follows, using student_on_course_instance as an example:

```
* [STUDENT_ON_COURSE_INSTANCE_ID](#student_on_course_instance_id) **
* [STUDENT_COURSE_MEMBERSHIP_ID](student_course_membership.md#student_course_membership_id) [1] *
* [COURSE_INSTANCE_ID](course_instance.md#course_instance_id) [1] *

\** Unique identifier to simplify LRW functions and data management, as an alternative to the multiple uniqueness constraint properties shown by *. Where not supplied by data provider, this identifier will be generated by the LRW.
\* indicates that the property is part of a uniqueness constraint for this entity.

##STUDENT_ON_COURSE_INSTANCE_ID
###Description
Unique identifier. Where not supplied by data provider, this property will be generated by the LRW.
```

Is that better?
I'll also have a look at the README section on this.

**Comment by alanepaull** [comment]
Current README section:

###Primary keys
Some entities have uniqueness constraints across multiple properties; for example student_on_course_instance has STUDENT_COURSE_MEMBERSHIP_ID plus COURSE_INSTANCE_ID. The MD files for these entities contain a note to this effect. For ease of processing and to enable field-level extensibility, these entities have a primary key that consists of a concatenation of the components of the composite key separated by a tilde (~).  **The tilde (~) is therefore a reserved character and must not be used elsewhere in these values.**

Where this type of primary key is not provided by the data supplier, the LRW loading mechanism will create it. For example: the student_on_course_instance entity's primary key consists of:
'''xxxxxx~yyyyyy
where xxxxxx is the STUDENT_COURSE_MEMBERSHIP_ID, ~ is the tilde reserved character, and yyyyyy is the COURSE_INSTANCE_ID.

Suggested revision:

###Multiple property uniqueness constraints
Some entities have uniqueness constraints across multiple properties; for example student_on_course_instance has STUDENT_COURSE_MEMBERSHIP_ID plus COURSE_INSTANCE_ID. The MD files for these entities contain a note to this effect. To simplify LRW functions and data management, and to enable field-level extensibility, these entities have a single unique identifier that can either be supplied by the data provider, or generated by the LRW when data is loaded.  As concatenation of the composite key properties is a possible solution to generating the single unique identifier, the tilde character (\~) is reserved for the purposes of splitting these properties and MUST NOT be used in the composite key properties.

Where the single unique identifier is not provided by the data supplier, the LRW loading mechanism will create it.


Also I would note that I'll remove the concatenation reference from the Format section of the entities and make them simply String (255).

**Comment by alanepaull** [comment]
As a result of discussion on Monday 13 March, final revision of above text:

"**Primary keys**
Some entities have uniqueness constraints across multiple properties; for example student_on_course_instance has STUDENT_COURSE_MEMBERSHIP_ID plus COURSE_INSTANCE_ID. The MD files for these entities contain a note to this effect. These entities have a single primary key for ease of processing and to enable field-level extensibility. The data supplier may choose to provide the single primary key, or may choose to leave it blank, in which case it will be generated by the LRW loading mechanism."
