### ISSUE TITLE
v1.3.0 ASSESS_SEQ_ID

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#173]
I think the current wording is ambiguous.

I understood this to refer to the sequcence of attempts at a given opportunity (identified as an assessment instance)

I think it could  be misunderstood to refer to the sequence of assessments overall (wording under Description, Purpose and Notes)

Could be clarified (assuming my interpretation is correct) by replacing "assessment" with "attempt at a given assessment" (or something like that). So.. we get e.g. the "order of attempts..."

I would add that the record for first attempt has ASSESS_SEQ_ID = 1. Also that, where records are created for assessments which have not yet been either submitted or graded, the ASSESS_SEQ_ID has the same value as it will gave after marking/grading. This is a logical consequence of its role as a unique identifier. It might actually be more clear to say it refers to an assessment opportunity, rather than an attempt, at this stage.

**Comment by michaelwebbjisc** [comment]
This-> It might actually be more clear to say it refers to an assessment opportunity, rather than an attempt, at this stage

**Comment by alanepaull** [comment]
Documentation revised.
