### ISSUE TITLE
v1.3.0 SCM PREDICTED_OUTCOME & ATTAINMENT_TARGET

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#177]
Both of these say "mark or grade".
Treatment of mark (numeric) vs grade (ordered category) is likely to be different.

It would help if the semantics of data elements were either mark or grade, not both.

Suggest: add attributes for BOTH mark and grade, named with "MARK" and "GRADE" as per convention elsewhere, and typed as numerical or string. Then people can use one/both according to the data they have.

I suspect it will mostly be grade in target-setting systems but potentially a mark also available for predictions. It might be that some translation from grade to a mark threshold could be made at source, which would help us to quantify distance-to-travel in performance. That is something to discuss with sites as needed; having MARK and GRADE gives us scope to do so without confusion.

**Comment by michaelwebbjisc** [comment]
Agreed - matches use of MARK and GRADE elsewhere.
