### ISSUE TITLE
v1.3.0 VLE_ID [0..1]

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#178]
This was discussed on a call and I thought agreed: that VLE_ID (in STUDENT) could be re-documented from [0..*] to [0..1].

I understood no-one had used >1 VLE_ID.
Having a singleton on STUDENT will save us from coding in support for something which we know is broken (because we don't know which VLE each ident refers to)

Should also cross-reference the new student id lookup entity.

**Comment by alanepaull** [comment]
Done early morning - had been awaiting a commit.

Alan
