### ISSUE TITLE
Add new field HESA_ID (as optional) - TBC (for UDD 1.2)

### ISSUE THREAD

**Issue by robwynj** [jiscdev/analytics-udd#18]
Would be useful for reference/ linkage to HESA records (or HESA continuity file) if required - and will further support our proposed strategic collaboration(s) with HESA and their student return.

Should refer to HUSID in HESA student return docs.

Kind Regards

Rob

**Comment by wilmTap** [comment]
Were you thinking of adding that to Student?

**Comment by robwynj** [comment]
Yes to student please - optional field - will support any linkage potentially in HEIDI Lab / future Analytics Lab proposed projects, supporting further collaboration between Jisc & HESA.

Kind Regards

Rob

**Comment by wilmTap** [comment]
Added in #28
