### ISSUE TITLE
MOD_ONLINE Format

### ISSUE THREAD

**Issue by ryansmith94** [jiscdev/analytics-udd#181]
Hey, the format of [`MOD_ONLINE`](https://github.com/jiscdev/analytics-udd/blob/v1.3/udd/module_instance.md#format-2) should be `Integer` not `String (255)` since the valid values are `1` and `2`.

**Comment by alanepaull** [comment]
I'm loathe to make unnecessary changes.  If this is a problem, I can change the format to integer, but there may be no problem with holding '1' and '2' as strings rather than integers.  Are they processed somewhere as integers?

**Comment by ryansmith94** [comment]
Before 1.3 they were always sent to the LRW as integers and validated by the LRW as integers. If this isn't changed everyone needs to start sending them as strings, probably less collective effort to correct the spec.

**Comment by alanepaull** [comment]
You are right.  If I recall correctly, for v1.3 we agreed to standardise all the UDD codes as String (255).
From my perspective, I'm happy to shift MOD_OPTIONAL and MOD_ONLINE back to Int, if we all agree to that; it certainly might reduce effort.

**Comment by arc12** [comment]
I am very keen that all UDD attributes which are codes are typed as string.
Consistency is an asset.
Granted there a a few cases whee the current values are digits and  it is highly unlikely we would ever want to extend the code list to non-digit codes, but these are the exception.

So for mod-online, the codes are the characters '1' and '2'

**Comment by ryansmith94** [comment]
So for the record, this will remain as `String (255)`?

**Comment by michaelwebbjisc** [comment]
Yes, agree with @arc12  - codes should be strings.

**Comment by ryansmith94** [comment]
Ok
