### ISSUE TITLE
MOD_SUBJECT format

### ISSUE THREAD

**Issue by ryansmith94** [jiscdev/analytics-udd#182]
The format of [Module MOD_SUBJECT](https://github.com/jiscdev/analytics-udd/blob/v1.3/udd/module.md#mod_subject) should be `String (10)` not `String (255)` to be consistent with [Course SUBJECT](https://github.com/jiscdev/analytics-udd/blob/v1.3/udd/course.md#subject)

**Comment by alanepaull** [comment]
Consistency would be better :).  However, I'm wondering if we should make both String (255).  This would give us more flexibility, if we decided to do something different with Subject for FE purposes.

What do folks think?

**Comment by ryansmith94** [comment]
Yeah consistency would be better 😄

**Comment by arc12** [comment]
+1 for consistency. I don't care about length. Seems OK to go for 10 chars. Can always extend later.

**Comment by ryansmith94** [comment]
Ok so to confirm, the format will be changed to `String (10)`?

**Comment by michaelwebbjisc** [comment]
Yes, fine with me.

**Comment by alanepaull** [comment]
Now done.
