### ISSUE TITLE
MOD_OPTIONAL format

### ISSUE THREAD

**Issue by ryansmith94** [jiscdev/analytics-udd#183]
The format of [`MOD_OPTIONAL`](https://github.com/jiscdev/analytics-udd/blob/v1.3/udd/module_instance.md#mod_optional) should be `Integer` not `String (255)` because the valid values are `1` and `2`.

**Comment by alanepaull** [comment]
Same comment as in #181.

**Comment by ryansmith94** [comment]
Before 1.3 they were always sent to the LRW as integers and validated by the LRW as integers. If this isn't changed everyone needs to start sending them as strings, probably less collective effort to correct the spec.

**Comment by michaelwebbjisc** [comment]
As for others, my take is codes should be strings.
