### ISSUE TITLE
v1.3.0 MOD_SUBJECT missing in code lists

### ISSUE THREAD

**Issue by ryansmith94** [jiscdev/analytics-udd#185]
https://github.com/jiscdev/analytics-udd/blob/v1.3/udd/udd_codelists_en.json

**Comment by arc12** [comment]
JACS3 codes are here: https://www.hesa.ac.uk/support/documentation/jacs/jacs3-detailed

**Comment by ryansmith94** [comment]
Can't something similar be said for some of the other codes that are also in the code lists file?

**Comment by alanepaull** [comment]
These JSON files have been output from the MD files and created by the "Extract Code Lists from MD.py" utility.  If there are omissions or additions that anyone would like to make to this utility, I would suggest a quick email to @arc12.  As the utility has been put "in the public domain" with no warranties, and so on, anyone can take it and run with it, if they would like to make it more useful.  The utility and its outputs are not a formal part of the UDD.
