### ISSUE TITLE
ORGANISATION is a reserved property name in the LRW

### ISSUE THREAD

**Issue by ryansmith94** [jiscdev/analytics-udd#188]
Can we please change the name of the [`ORGANISATION` property in the extensions](https://github.com/jiscdev/analytics-udd/blob/v1.3.0/extension.md#organisation)? That is a reserved property name in the LRW as we use it to filter your data by the authenticated Learning Locker organisation.

I'd perhaps recommend `AGENT` as a replacement.

**Comment by arc12** [comment]
Agent overlaps with xAPI terminology. I prefer CONTROLLER, which is a term used in the description.

**Comment by ryansmith94** [comment]
`CONTROLLER` is good 👍

**Comment by ht2** [comment]
Gets my vote
