### ISSUE TITLE
TUTOR_STAFF_ID rather than COACH_SCHOOL_ID in Student (additional)

### ISSUE THREAD

**Issue by wilmTap** [jiscdev/analytics-udd#19]
Because it's better understood in the UK

**Comment by robwynj** [comment]
Agreed - guidance should refer to this as typically being the unique staff id as held within their HR/ Payroll system (this may be in anyway I think!). 

**Could also add in their HESA staff ID in here, into this entity, for future use (optional field again, as per student identity purpose).
**

Kind Regards

Rob
