### ISSUE TITLE
Denorm of MOD_ACADEMIC_YEAR - missed off ASSESSMENT_INSTANCE ?

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#191]
Since this entity has a FK to MODULE_INSTANCE, it could logically have  MOD_ACADEMIC_YEAR, and this would make for uniformity as well as achieving the same ease of processing which motivated the denorm elsewhere.

**Comment by alanepaull** [comment]
I don't see this as a problem.  Is it OK with everyone else, particularly HT2?

**Comment by ht2** [comment]
Hi @alanepaull, as long as there is no onus on the LRW to validate this value between the models then it doesn't bother us that this field is in both places.  

Is this just a quick way around not being able to query between related models? Is it that you would actually want to filter all `ASSESSMENT_INSTANCE`s that match a current year, then currently that would be done through 2 API requests:

`GET /models/moduleInstance?query={"MOD_ACADEMIC_YEAR":"2017"}`

`GET /models/assessmentInstance?query={"MOD_INSTANCE_ID": { "$in": [//IDs pulled from first query] }}`

However looking forward I could for see the ability to query through related models in the new LRW-API (e.g. `query={"moduleInstance.MOD_ACADEMIC_YEAR":"2017"}`) but that would need a bit more definition and work. On our side its just a JOIN, so it shouldn't be too awkward

**Comment by alanepaull** [comment]
It's for ease of processing, so avoiding having to query across 2 entities.

**Comment by ht2** [comment]
OK, I'd say proceed on this one, but if its becoming evident that the need to query across entities is a core requirement, then adding in the ability to do that via the API itself probably jumps up the list :)

**Comment by alanepaull** [comment]
Now done.  Will close at Monday 27th March meeting, if no problems.
