### ISSUE TITLE
Additional (optional) field - STUDENT.SECONDARY_EMAIL_ADDRESS

### ISSUE THREAD

**Issue by robwynj** [jiscdev/analytics-udd#192]
Maybe useful, in addition to their PRIMARY_EMAIL_ADDRESS - could contain their personal email address, useful for reference/ comms/ other purposes?

Cheers

Rob

**Comment by alanepaull** [comment]
Not sure about this. Wouldn't this potentially result in doubt about which one to use, or always using both? It might be better to have 1 definitive one?

Alan

**Comment by arc12** [comment]
I imagine most universities have one email address on record which they expect students to monitor, for official communications.

**Comment by alanepaull** [comment]
Monday 27 March: agreed to leave this out for v1.3.0.  In the event that it might be needed by a data supplier, an extension could be used; then we can make a decision later on whether it is worth adding.

Non-breaking change, so I've left this open for v1.3.1 for now.

**Comment by alanepaull** [comment]
Monday 24 April: review at a later date.

**Comment by alanepaull** [comment]
Monday 8 January: agreed to drop this for now, as there is no active demand.
