### ISSUE TITLE
filename conventions is not up to date with 1.3

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#195]
missing 
'period',
'studentidmap'

**Comment by alanepaull** [comment]
Darn. I had a feeling I'd missed one of the connections :).  Will correct that shortly.
Thanks, Adam.
Alan

**Comment by alanepaull** [comment]
Any preference for the order of these items? Noticing that they're not alpha.
Alan

**Comment by arc12** [comment]
none here.
TBH I try to avoid looking at these because they are so horrible without underscores or camel case. The convention is not IMO a good one.
