### ISSUE TITLE
Reference data: INST_TIER and COURSE_LOCATION

### ISSUE THREAD

**Issue by alanepaull** [jiscdev/analytics-udd#196]
These potential new pieces of reference data were considered for inclusion in v1.3.0 and rejected. We also agree to re-consider them for v1.3.1. Closed issue #105 refers.

INST_TIER: The need was to identify the hierarchical structure of institutional sub-units, at least for naming purposes in outputs, rather than displaying codes - for human readability. 

COURSE_LOCATION: The need was to identify the name of campuses, and so on, for labelling and human readability.

There may be other ways of handling this issue outside the UDD. It is worth considering inclusion of the data in the UDD as a solution.

**Comment by alanepaull** [comment]
Monday 5 June 17: we agreed to leave the issue open for occasional review, but not to include in the regular fortnightly call.

**Comment by alanepaull** [comment]
Monday 19 March 2018: agreed to add in reference data for inst_tier (faculty, dept, school, etc) and for campus.
See: https://github.com/jiscdev/analytics-udd/blob/v1.4/udd/inst_tier.md
and: https://github.com/jiscdev/analytics-udd/blob/v1.4/udd/course_location.md

**Comment by alanepaull** [comment]
Monday 9 April 2019: agreed to draft and consider a generic entity for reference data, generalising from period, inst_tier and course_location.

**Comment by alanepaull** [comment]
I've done some work on this. However, there's a significant problem with validation, I believe. If we have a set of generic properties with no way of knowing in advance what valid values will be (eg date? int? Any string?), then the web validator won't validate the entries. We *could* allow any values through, but non-validated reference data is not a good idea.

Records would look a bit like this (Property Name followed by value; asterisks indicate primary key and uniqueness constraint):

<table>
<tr><td>REFERENCE_DATA_ID</td><td>**</td><td>1</td></tr>
<tr><td>REFERENCE_DATA_TYPE</td><td>*</td><td>PERIOD</td></tr>
<tr><td>CODE</td><td>*</td><td>ACADYR</td></tr>
<tr><td>NAME</td><td>*</td><td>Academic Year</td></tr>
<tr><td>PROPERTY_1_NAME</td><td>*</td><td>PERIOD_START_DATE</td></tr>
<tr><td>PROPERTY_1_VALUE</td><td>*</td><td>2018-10-01</td></tr>
<tr><td>PROPERTY_2_NAME</td><td>*</td><td>PERIOD_END_DATE</td></tr>
<tr><td>PROPERTY_2_VALUE</td><td>*</td><td>2019-07-31</td></tr>
<tr><td>PROPERTY_3_NAME</td><td>*</tr>
<tr><td>PROPERTY_3_VALUE</td><td>*</tr>
</table>

<table>
<tr><td>REFERENCE_DATA_ID</td><td>**</td><td>2</td></tr>
<tr><td>REFERENCE_DATA_TYPE</td><td>*</td><td>INST_TIER</td></tr>
<tr><td>CODE</td><td>*</td><td>BUSINESS</td></tr>
<tr><td>NAME</td><td>*</td><td>The Business School</td></tr>
<tr><td>PROPERTY_1_NAME</td><td>*</td><td>LEVEL</td></tr>
<tr><td>PROPERTY_1_VALUE</td><td>*</td><td>Faculty</td></tr>
<tr><td>PROPERTY_2_NAME</td><td>*</td><td></td></tr>
<tr><td>PROPERTY_2_VALUE</td><td>*</td><td></td></tr>
<tr><td>PROPERTY_3_NAME</td><td>*</tr>
<tr><td>PROPERTY_3_VALUE</td><td>*</tr>
</table>

<table>
<tr><td>REFERENCE_DATA_ID</td><td>**</td><td>3</td></tr>
<tr><td>REFERENCE_DATA_TYPE</td><td>*</td><td>COURSE_LOCATION</td></tr>
<tr><td>CODE</td><td>*</td><td>MAIN</td></tr>
<tr><td>NAME</td><td>*</td><td>Bloomsbury Campus</td></tr>
<tr><td>PROPERTY_1_NAME</td><td>*</td><td></td></tr>
<tr><td>PROPERTY_1_VALUE</td><td>*</td><td></td></tr>
<tr><td>PROPERTY_2_NAME</td><td>*</td><td></td></tr>
<tr><td>PROPERTY_2_VALUE</td><td>*</td><td></td></tr>
<tr><td>PROPERTY_3_NAME</td><td>*</tr>
<tr><td>PROPERTY_3_VALUE</td><td>*</tr>
</table>

I've thought about specifying the valid values within the generic table. While this would probably work, it would certainly require some development of the validator. This may be problematic.

I'd be very happy to receive some bright ideas at this stage!

Alan

**Comment by arc12** [comment]
A couple of thoughts and some follow-on.
1. I'd rather we didnt touch PERIOD. We have working code using the current scheme and I'd rather avoid rework to get back to the same place unless there is a problem for which this is a compelling solution.
2. I think the answer depends on the requirements ;-) If we're just after some code-label lookup (which we already do using JSON files) then there is no problem, The problem seems to arise with adding properties as well.

Re no 2:
- one kind of property could be a "validity period". I can see this is useful in systems where people are presented with pick-lists, but I'm not convinced it is helpful when using this reference info as a look-up. 
- another, which might be useful is geolocation coordinates. I don;t expect we need this anytime soon. One solution here would be to have one/two optional properties which are explicitly geolocation, and just omit values when not required.

I have another challenge:
What about when the name/label should be "localisable"? For example, the names of departments in Welsh institutions will be in Welsh and English.

I also have another idea:
consider abandoning the idea that ref data should look like a relational database table and think JSON.

**Comment by alanepaull** [comment]
We currently have new inst_tier and course_location entities in v1.4. I suspect that these need more discussion, though I know that Rob would like to finish this off quickly, so we can effectively release v1.4 shortly.

The key decision here is 1 of the following:

1. Revert to the v1.3 approach (just retain period; remove inst_tier and course_location).
2. Leave the minimal inst_tier and course_location ref data entities in v1.4 as now; implement new ref data tables as and when they arise, or a more generic solution at a later date.
3. Remove inst_tier and course_location entities (leave in period) and implement a simple code-label reference data table, accepting the limitations this has.
4. A. N. Other solution.

Views?

**Comment by arc12** [comment]
Considering the validation requirement:
A. in that case, I think some kind of change control is necessary. In concrete terms, I think this means, if this kind of info were to be part of UDD, it should not be subject to live-updating.

B. First-line validation is likely (I think) to be pre-LDH, so a parallel (e.g. JSON) exchange mechanism is likely not to be an issue from a technical workflow pov.

**Comment by alanepaull** [comment]
8 May 2018: Concern was expressed about growth in numbers of entities. These ref data entities not seen as vital, so should be removed until we have specific well-expressed requirements for them. In the meantime, providers can supply these labels as needed.
