### ISSUE TITLE
1.4 or 2.0?

### ISSUE THREAD

**Issue by alanepaull** [jiscdev/analytics-udd#197]
We've been talking about 1.4, rather than 2.0 for breaking changes. I recommend that we change all 2.0 labels to 1.4, so we can avoid confusion.

**Comment by arc12** [comment]
Happy to see 1.4 for incremental breaking changes and 2.0 for wholly new features

**Comment by alanepaull** [comment]
Thanks, @arc12. I'll review and see if we can split on that basis with our current issues...

**Comment by alanepaull** [comment]
Quick review shows the following:
There are no 1.4 issues (though I've changed #156 from 1.4 to 2.0, because that one reflects a wholly new feature). There are 6 open 2.0 issues.

However, #100 (SUBJECT), #58 (MAX_POINTS), #75 (code lists) and #160 (multiple personal tutors) could all be considered incremental breaking changes, because we have the data now, we're suggesting changes to the location and structure of the data.  Wholly new features are probably our suggestions for #156 FE programmes of learning and #48 Sensible way to generate documentation.

I should probably simply re-label #100, #58, #75 and #160 as v1.4.

**Comment by ht2** [comment]
Happy that there could be a split between 1.4 and 2.0.

Now we've moved to an RDS for the 1.3+ systems, I am interested to know your feelings about how we would tranistion to deploy a new version of the UDD.

Obviously it would need to be available via a slightly different URL as with 1.2.x (/stable, /1.3.0, /1.4.x etc) but how would we deal with data consistency between the versions?

We'd be looking to create a new schema with every new version, so its whether we need the ability to "migrate" the data between versions, allowing us to copy an entire schema and then run the migration to include the new fields. This could of course be destruvtive (removing fields) or could create data by way of new fields. This in turn is problematic as including a new "required" field would require us to insert a sensible default or risk invalidating the entire data set.

The nuclear option (and certainly easiest from our point of view) is that the dataset is reinserted for the new breaking version by external parties, ensuring that the data being inserted is valid to the current version being deployed. 

This may need its own issue, happy to split out if required

**Comment by arc12** [comment]
Within 1.3.x I would hope we can just extend the schema and leave NULLs on existing data
Indeed, that could be considered a criterion for a 1.3.x

For major changes, I think the nuclear option is sensible.
I am actually in favour of periodic wholesale repopulation even if there is no version change:
1. I don't entirely trust incremental changes will either always get through or be correctly processed
2. This is possibly the most robust way of ensuring aged-out data (according to data processing agreements) is removed

**Comment by ht2** [comment]
Agreed on both - where possible we'd love to see wholesale repopulation, as you say it just negates any issues as a result of migration patterns and allows you to be confident of what is actually present in the db.

**Comment by michaelwebbjisc** [comment]
Hi, yes, anything that goes through our standard load process (ie institutions providing whole data sets in TSV, JSON or XML) will be completely reloaded.

In general, we don't want institutions providing incremental data for the reasons that Adam says, so we have a strong preference that institutions follow us standard process.  I also don't trust institutions incremental updates.   Whilst our process is processor heavy at our end, I'd rather we take the deal with it.

We do have the option of mandating that all institutions follow our standard process rather than allow direct maintenance of UDD data, but at the moment we're just taking the line that we don't recommended it.
