### ISSUE TITLE
Need VLE_ID - APPROVED (for UDD 1.2)

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/analytics-udd#2]
This is the ID that the VLE uses for the student, so we can match activity data to the student.

**Comment by arc12** [comment]
See proposal for a generalised approach to this and AIM_ID on Basecamp:
https://basecamp.com/2737506/projects/10136653/messages/52823183

**Comment by michaelwebbjisc** [comment]
At the moment I want to keep it as simple as possible for institutions and devs.  I can see roughly what you are proposing, but I thing we need to a worked example - ie what putting data in looks like, and what getting data out looks like in terms of code.

**Comment by robwynj** [comment]
Will this be denoted as NULL if the student id actually exists in the VLE data (and thus we use student id if it's NULL, otherwise we use it this field). Hope this makes sense!

**Comment by robwynj** [comment]
Will add this into UDD 1.2

**Comment by arc12** [comment]
@michaelwebbjisc - there is an example at the bottom of the basecamp post (2nd post)
My POV is one of having a sustainable/scalable and flexible approach, but I accept that some simplification could be achieved if we separately addressed: 1) person id mapping and 2) the VLE course-area to other entity mapping (and disregared the likelihood of other mappings being required)

Re #1: I think opting for vle_id and aim_id won't cut it. We'll find more application types and multiple applications of the same type. Bring LTI tools into the fold and who knows...
So I think the minimum would be to cut down my original proposal to, for example:
EXTERNAL_APP = "https://courses.alpha.jisc.ac.uk/moodle"
EXTERNAL_STUDENT_ID = "130"
MASTER_STUDENT_ID = "70314"

Re 2: I think we will find a need to match vle course areas to a range of entities, not be bound to e.g. a module instance. But this is the topic of https://github.com/jiscdev/analytics-udd/issues/8

On "simple as possible for institutions and devs": I would expect the mappings we are talking about here to be the kind of thing people used to wrangling databases would be involved with creating, so we don't need to be hard line on simplicity. After all, the complexity of determining some of the HESA fields in the UDD is relatively substantial. I don;t think we'll be able to get away without all of the 5 fields I outlined either being explicit in the data or explicit in a the UDD specification (and implicit in the data). My contention is that being explicit in the data will make it easier to check data quality and the sustainability and flexibility will be a big plus.

**Comment by michaelwebbjisc** [comment]
I guess I just need to know what specific aspect of Insights won't work if provide AIM_ID and VLE_ID as I'm suggesting, given the data sets we are currently using.

**Comment by arc12** [comment]
in the short term, if that is the limit of the data, I would not expect it to stop things from working, but there might be niggles. For example, lets assume I want to find LRS records for a given student: for which subset of statements should I match the VLE_ID and for which should I match the AIM_ID? (or should I assume there are no collisions).

In the medium to long term I'm confident it will cause some difficulty, as the number of data sources in the architecture expands. This seems to be avoidable without excessive complexity.

I'd be interested in the comments of other stakeholders...

**Comment by michaelwebbjisc** [comment]
AIM_ID is to help institutions using Shib/UK Access federation to match users to their data after users login. So the user logins into the student app using the Shib to JWT gateway we are creating.  The AIM_ID is returned in the JWT token, and the app can then use this to look up the student name etc.

VLE_ID is used to match VLE Activity data collected by the Moodle or Blackboard to the student.  So I'd anticipate Tribal would use this, but not AIM_ID.

In the student app example, the app could retrieve the VLE_ID at the same time as getting then name, and then query Learning Locker to get student activity data.

I agree, we'll need a more general approach in the medium to long term, but I think we can iterate to get there when we've got concrete example datasets.

**Comment by robwynj** [comment]
Michael - this will primarily assist Strathclyde in the first instance, with VLE ID's rotating on a per academic year basis?

**Comment by wilmTap** [comment]
I've included an addition of VLE_ID to my branch, and it's part of a pull request #15 .

More generally, my sense of the ID issue is that we might get away with resolving IDs by applying domain knowledge in queries for now, but that is unsustainable and unlikely to scale. We probably need an ID mapping object of the sort Adam describes sooner rather than later. Wouldn't HS2's announced ID reconciliation service help?
