### ISSUE TITLE
Adding organisational hierarchy

### ISSUE THREAD

**Issue by wilmTap** [jiscdev/analytics-udd#20]
Attributes added to store information about how a course is related to the institution departmental hierarchy.

**Comment by robwynj** [comment]
Maybe useful to increase this number to 5 - 3 typically not enough in some instances, but will leave this up to you guys. What is the max in the typical organisation management side in SITS?

Might be useful to provide same TIER_X levels for STAFF entity too - would potentially be useful for staff wanting to view data/ dashboards on students within higher/ encompassing organisational levels ie. school/ divisional level etc?!

Kind Regards

Rob

**Comment by wilmTap** [comment]
Left at three levels for now, but we may revisit later of there is a need.
