### ISSUE TITLE
ACADEMIC_YEAR and MOD_ACADEMIC_YEAR formats

### ISSUE THREAD

**Issue by alanepaull** [jiscdev/analytics-udd#200]
There's a practical problem in validating with the Web Validator and also processing in LRW of ACADEMIC_YEAR (in course_instance) and MOD_ACADEMIC_YEAR (in module_instance) properties, because the format is specified as String in ISO 8601 format, and the Valid Values also mentions ISO 8601. While this is strictly correct, the Web Validator and LRW assume that ISO 8601 requires a full yyyy-dd-mm syntax.

In addition, ACADEMIC_YEAR in period and MOD_ACADEMIC_YEAR in student_on_assessment_instance should refer to the property in course_instance and module_instance respectively, rather than be re-defined in period.

Proposed solution:
(1) Change the format to Int (as it was in 1.2.7).
(2) Add to the Description that the property should represent the year as a YYYY, from 1900 onwards.
(3) Change the Valid Values to YYYY.
(4) Remove ACADEMIC_YEAR and MOD_ACADEMIC_YEAR details from period and student_on_assessment_instance. Reference course_instance and module_instance instead (note: the property remains in the entities; it's only the reference that's changing).

**Comment by alanepaull** [comment]
Noting what was in the Valid Values in 1.2.7, would this be OK and still work in the validator?

**Valid Values**
Year as four digits - year that the academic year starts in, with valid values being from 1900 onwards.

**Comment by huwrobertsjisc** [comment]
Happy with steps 1-3 of the proposed solution. I don't know enough to comment on step 4.

It's the same issue in the Period entity when looking at the Academic_Year field:
https://github.com/jiscdev/analytics-udd/blob/v1.3.0/udd/period.md#academic_year

If this field can be changed too, that would be appreciated.

**Comment by craig-petch** [comment]
steps 1-3 work for us too.  We wouldn't want to go as far as option 4 as both attributes are now collected and used. Academic_year is needed in Period for uniqueness and the aim of adding mod_academic_year was to make filtering the entity by year simpler so it wasn't required to go to Module_instance.

**Comment by alanepaull** [comment]
The suggestion for Point 4 is specifically NOT to remove the properties from period and student_on_assessment_instance. The properties stay; it's simply that the explicit definition of them in the period and student_on_assessment_instance files should be replaced by a reference to course_instance#ACADEMIC_YEAR and module_instance#MOD_ACADEMIC_YEAR.

**Comment by craig-petch** [comment]
Apologies Alan, I misinterpreted that. I thought it was a bit extreme!

**Comment by alanepaull** [comment]
These 4 small points have now been committed. Huw and Craig: please let me know if there's any further issues with this.
Alan

**Comment by alanepaull** [comment]
Monday 3 July 2017: agreed to check and close.
