### ISSUE TITLE
1.3.0 Student Entity MD file missing codes (LEARN_DIF, DISABILITY1 & DISABILITY2)

### ISSUE THREAD

**Issue by craig-petch** [jiscdev/analytics-udd#201]
Hi @alanepaull , 

The valid codes in the codelist table for LEARN_DIF, DISABILITY1 & DISABILITY2 are empty in the 1.3.0 version of the MD file. They are there for master. Could you update the file to include them as it's causing issues downstream.

Cheers 

Craig

**Comment by alanepaull** [comment]
That's baffling. I wonder how long they've been absent? And indeed how they got to be absent. I'll correct that asap.

**Comment by alanepaull** [comment]
For the LEARN_DIF codes, I am presuming that we should be using the HESA 2016 versions as the basis of the UDD codes rather than v1.2.7, because the v1.2.7 codes were keyed more directly to the old and now clashing HESA 2015.

**Comment by robwynj** [comment]
Correct.

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; APMG PRINCE2 & APMG AGILE Certified Practitioner

Senior Data & Analytics Integrator - Jisc UK Learning Analytics
Cluster Lead – Jisc Data & Analytics Service

email/ skype: rob.jones@jisc.ac.uk<mailto:rob.jones@jisc.ac.uk> mobile: 07468 727040  web: www.jisc.ac.uk<http://www.jisc.ac.uk>

**Comment by alanepaull** [comment]
Hmm. It looks like we never completed LEARN_DIF, even though we signed it all off both in terms of the issues raised and for version 1.3.0.

I'm now creating a LEARN_DIF in off-line Github file and will post in this issue for checking before committing to v1.3.0.

**Comment by alanepaull** [comment]
There are 2 entries that I need suggestions about.

"Profound complex disabilities" (value = 7) is a new entry in HESA (and also in the FE). It doesn't specify that it's learning difficulties; in fact, I've not found a definition of this item. Do we need to include it here, because this property is for learning difficulties specifically? I suspect 'yes' is the correct answer, so we cover the possibility that it's relevant.

"Multiple learning difficulties" (value = 90 in v1.2.7) is an old term that is not in the HESA 2016. Should we remove this term, or will that have issues with historic data? There seems to be no matching term in the new system - unless "profound complex disabilities" covers it?

**Comment by alanepaull** [comment]
LEARN_DIF for checking (may need to scroll right for last column).
Queries:
"Profound complex disabilities" - should this be added?
"Multiple learning difficulties" - should this be deleted?
"Speech, Language and Communication Needs" - added because it looks relevant to learning difficulties. Is this correct?

<table>
    <tr>
	<td>LEARN_DIF</td>
        <td>DESCRIPTION (ENGLISH)</td>
        <td>DESCRIPTION (WELSH)</td>
        <td>HESA 2015 (LEARNDIF)</td>
        <td>HESA 2016 (LLDDHEALTHPROB)</td>
        <td>FEILR 2014 (LLDDCAT)</td>
        <td>FEILR 2016 (LLDDCAT)</td>
    </tr>
    <tr>
	<td>10</td>
        <td>Moderate learning difficulty</td>
        <td></td>
        <td>01</td>
        <td>10</td>
        <td>01</td>
        <td>10</td>
    </tr>
    <tr>
	<td>11</td>
        <td>Severe learning difficulty</td>
        <td></td>
        <td>02</td>
        <td>11</td>
        <td>02</td>
        <td>11</td>
    </tr>
    <tr>
	<td>12</td>
        <td>Dyslexia</td>
        <td></td>
        <td>10</td>
        <td>12</td>
        <td>10</td>
        <td>12</td>
    </tr>
    <tr>
	<td>13</td>
        <td>Dyscalculia</td>
        <td></td>
        <td>11</td>
        <td>13</td>
        <td>11</td>
        <td>13</td>
    </tr>
    <tr>
	<td>14</td>
        <td>Autism spectrum disorder</td>
        <td></td>
        <td>20</td>
        <td>14</td>
        <td>20</td>
        <td>14</td>
    </tr>
    <tr>
	<td>15</td>
        <td>Asperger's syndrome</td>
        <td></td>
        <td>N/A</td>
        <td>15</td>
        <td>N/A</td>
        <td>15</td>
    </tr>
    <tr>
	<td>17</td>
        <td>Speech, Language and Communication Needs</td>
        <td></td>
        <td>N/A</td>
        <td>17</td>
        <td>N/A</td>
        <td>17</td>
    </tr>
    <tr>
	<td>94</td>
        <td>Other specific learning difficulty</td>
        <td></td>
        <td>19</td>
        <td>94</td>
        <td>19</td>
        <td>94</td>
    </tr>
    <tr>
	<td>90</td>
        <td>Multiple learning difficulties</td>
        <td></td>
        <td>90</td>
        <td>N/A</td>
        <td>90</td>
        <td>N/A</td>
    </tr>
    <tr>
	<td>96</td>
        <td>Other learning difficulty</td>
        <td></td>
        <td>97</td>
        <td>96</td>
        <td>97</td>
        <td>N/A</td>
    </tr>
    <tr>
	<td>0</td>
        <td>No learning difficulty</td>
        <td></td>
        <td>98</td>
        <td>0</td>
        <td>N/A</td>
        <td>N/A</td>
    </tr>
    <tr>
	<td>99</td>
        <td>Not provided</td>
        <td></td>
        <td>99</td>
        <td>99</td>
        <td>99</td>
        <td>99</td>
    </tr>
    <tr>
	<td>98</td>
        <td>prefer not to say</td>
        <td></td>
        <td>N/A</td>
        <td>98</td>
        <td>N/A</td>
        <td>98</td>
    </tr>                      
</table>

**Comment by craig-petch** [comment]
It looks like we have those values coded/mapped in the DIFFLEARN1/2. I would definitely continue with 90 (Multiple learning difficulties). I can't quite recall if we were looking to keep LEARN_DIF to support with older coding structures and the DIFFLEARNx attributes to cope with the newer HESA/FE fields.  From our perspective I think we use the DIFFLEARN attributes now rather than the LEARN_DIF and DISABILITY as these handle the newer codes.

**Comment by alanepaull** [comment]
DISABILITY1 and DISABILITY2 for checking (only change for DISABILITY2 is the '2' in the label):

<table>
    <tr>
	<td>DISABILITY1</td>
        <td>DESCRIPTION (ENGLISH)</td>
        <td>DESCRIPTION (WELSH)</td>
        <td>HESA 2015 (DISABLE)</td>
        <td>HESA 2016 (DISABLE)</td>
        <td>FEILR (LLDDCat) </td>
    </tr>
    <tr>
	<td>0</td>
        <td>No known disability</td>
        <td>Dim Anabledd</td>
        <td>00</td>
        <td>00</td>
        <td>N/A </td>
    </tr>
    <tr>
	<td>5</td>
        <td>Personal care support</td>
        <td></td>
        <td>05</td>
        <td>N/A</td>
        <td>N/A </td>
    </tr>
    <tr>
	<td>7</td>
        <td>An unseen disability, e.g. diabetes, epilepsy, asthma</td>
        <td></td>
        <td>07</td>
        <td>N/A</td>
        <td>95</td>
    </tr>
    <tr>
	<td>8</td>
<td>Two or more impairments and/or disabling medical conditions</td>
        <td></td>
        <td>08</td>
        <td>08</td>
        <td>2</td>
    </tr>
    <tr>
	<td>51</td>
        <td>A specific learning difficulty such as dyslexia dyspraxia or AD(H)D</td>
        <td></td>
        <td>11, 51</td>
        <td>51</td>
        <td>12, 13</td>
    </tr>
    <tr>
	<td>53</td>
        <td>A social/communication impairment such as Asperger's syndrome/other autistic
            spectrum disorder</td>
        <td></td>
        <td>53</td>
        <td>53</td>
        <td>1, 14, 15, 17</td>
    </tr>
    <tr>
	<td>54</td>
        <td>A long standing illness or health condition such as cancer, HIV, diabetes, chronic
            heart disease or epilepsy</td>
        <td></td>
        <td>54</td>
        <td>54</td>
        <td>N/A</td>
    </tr>
    <tr>
	<td>55</td>
        <td>A mental health condition such as depression schizophrenia or anxiety
            disorder</td>
        <td></td>
        <td>06, 55</td>
        <td>55</td>
        <td>9</td>
    </tr>
    <tr>
	<td>56</td>
        <td>A physical impairment or mobility issues such as difficulty using arms or using
            a wheelchair or crutches</td>
        <td></td>
        <td>4, 56</td>
        <td>56</td>
        <td>6, 93</td>
    </tr>
    <tr>
	<td>57</td>
        <td>Deaf or a serious hearing impairment</td>
        <td></td>
        <td>03, 57</td>
        <td>57</td>
        <td>5</td>
    </tr>
    <tr>
	<td>58</td>
        <td>Blind or a serious visual impairment uncorrected by glasses</td>
        <td></td>
        <td>02, 58</td>
        <td>58</td>
        <td>4</td>
    </tr>
    <tr>
	<td>96</td>
        <td>A disability impairment or medical condition that is not listed above</td>
        <td></td>
        <td>96</td>
        <td>96</td>
        <td>7, 8, 16, 97</td>
    </tr>
    <tr>
	<td>97</td>
        <td>Information refused</td>
        <td></td>
        <td>97</td>
        <td>N/A</td>
        <td>98 </td>
    </tr>
    <tr>
	<td>98</td>
        <td>Information not sought</td>
        <td></td>
        <td>98</td>
        <td>N/A</td>
        <td>N/A</td>
    </tr>
    <tr>
	<td>99</td>
        <td>Not known / not provided</td>
        <td>Anhysbys</td>
        <td>99</td>
        <td>N/A</td>
        <td>99 </td>
    </tr>
</table>

**Comment by alanepaull** [comment]
Craig: is it possible that we've missed the issue here because these properties are not used?

**Comment by craig-petch** [comment]
There's been quite a lot of historic discussion around these fields see issues #114 and #130.  I think the final outcome appears to be "General consensus was that it could be used if needed by some, ignored by others." Possibly a 4:55 discussion point?  

Perhaps we make sure the codes for LEARN_DIF and DISABILITY are the same as 1.2.7 for now as this will help us move forward with the validator and we just review the consensus at the next meeting. They are in 1.3.0 so they I assume they should accept and validate entries in the UDD. The data we have includes them for some. Adam's on leave this week so can't check with him for his views at the moment.

**Comment by alanepaull** [comment]
I recall a lot of the discussion, and I've had a quick refresher.

Unfortunately, we can't necessarily just use the v1.2.7 codes, because the purpose of the update was to cover off the new HESA 2016 (and corresponding FE 2016) changes. If these are not necessary, because new stuff will always go into DIFFLEARN1 and DIFFLEARN2, then we can use the codes from master / v1.2.7 and the problem will go away.

I'd like steer from Rob and / or Mike on that one, please.

**Comment by alanepaull** [comment]
As Craig suggests, I will revert LEARN_DIF, DISABILITY1 and DISABILITY2 to the master (v1.2.7) versions, so that for now they will work for the validator, while the new codes are discussed.

**Comment by alanepaull** [comment]
Monday 5 June 17: we agreed to mark LEARN_DIF, DISABILITY1 and DISABILITY2 as deprecated.

**Comment by ryansmith94** [comment]
Any action required on the LRW?

**Comment by alanepaull** [comment]
Ryan: I don't think so. The current codes in v1.3.0 are the same as for the master (v1.2.7).

**Comment by ryansmith94** [comment]
Awesome thanks @alanepaull 👍

**Comment by ryansmith94** [comment]
The LEARN_DIF codes here are different to the codes listed in master by the way.

**Comment by ryansmith94** [comment]
Which codes should be used? The codes here or the codes in master?

**Comment by alanepaull** [comment]
The codes above are not for use; they were proposed changes. Please use the ones in the MD files, as per usual. v1.3.0 codes are the same as master in this instance.

**Comment by ryansmith94** [comment]
Awesome thanks @alanepaull 👍
