### ISSUE TITLE
Student on Course Instance -> Mode -> Values check

### ISSUE THREAD

**Issue by huwrobertsjisc** [jiscdev/analytics-udd#202]
Hi @alanepaull,

Just to check, looking at the list of value values in Student On Course Instance's Mode field, the value associated with the description "FE students continuous delivery day/daytime", should this be 6 or 65? All other values in this table match the HESA values.

Please see here:
https://github.com/jiscdev/analytics-udd/blob/v1.3.0/udd/student_on_course_instance.md#mode

Thanks,

Huw

**Comment by alanepaull** [comment]
That particular code seems to have been '6' for a long time. It's like that in the current master. It looks to me like it should be '65', as you've suggested. Are there any non-positive implications to changing that?

Alan

**Comment by robwynj** [comment]
Yes, fix for 1.2.7 and 1.3.0

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; APMG PRINCE2 & APMG AGILE Certified Practitioner

Senior Data & Analytics Integrator - Jisc UK Learning Analytics
Cluster Lead – Jisc Data & Analytics Service

email/ skype: rob.jones@jisc.ac.uk<mailto:rob.jones@jisc.ac.uk> mobile: 07468 727040  web: www.jisc.ac.uk<http://www.jisc.ac.uk>

**Comment by alanepaull** [comment]
Committed to master, v1.2.7 and 1.3.0.
Alan
