### ISSUE TITLE
Representing percentages in the UDD

### ISSUE THREAD

**Issue by alanepaull** [jiscdev/analytics-udd#206]
We have a number of properties that contain figures that are percentages. It would be helpful if these were presented in such a way that 'percentage' was explicit. Issue #199 refers.

Proposal: Use the following method to represent a percentage value

Valid Values
0-100

Format
Decimal

Notes
The value represents a percentage.

This has the advantage of maintaining what we already have and simply clarifying it in Notes.

**Comment by arc12** [comment]
Thing to avoid is "decimal" being interpreted to mean that 45% is represented as 0.45

**Comment by alanepaull** [comment]
Good point. An example should do it.

Notes
The value represents a percentage; for example, a value of "63.75" means 63.75%, a value of "50" means 50%.

Alan

**Comment by alanepaull** [comment]
Amended as noted.

**Comment by craig-petch** [comment]
Hi Alan, 

I'm just working on data for one of our sites their marks are actually grade points so the format works fine but I wonder if the notes suggest that this cannot be supported as they read as it's percentage only?

Craig

**Comment by alanepaull** [comment]
This is covered in detail in #199, I think. I've made the changes to v1.3.1 files, as I'm reluctant to change the "live" v1.3.0.

The main changes are in student_on_assessment_instance:

ASSESS_ACTUAL_MARK and ASSESS_AGREED_MARK are percentages (0-100 range, but can be fully decimal, so 63.75 is fine). RAW_ACTUAL_MARK and RAW_AGREED_MARK are decimal, but not percentages, so 175.6 is fine.

**Comment by craig-petch** [comment]
Ok, in this instance Grade Points are used for both Modules and Assessment. I read #199 as SoAI related only, so would we need RAW in module too?  RAW and ASSESS will always be the same for grade scores from SITS anyway, there's no conversion from RAW to Assess or Module.

**Comment by alanepaull** [comment]
Monday 3 July 2017: Agreed to add RAW_ACTUAL_MARK and RAW_AGREED_MARK properties to student_on_a_module_instance, as in student_on_assessment_instance.
@craig-petch: are you content with this addition?

**Comment by craig-petch** [comment]
Just looking at adding the RAW_ACTUAL_MARK and RAW_AGREED_MARK attributes to our data extracts (they currently won't be used), I noticed we do not have the RAW value equivalent MOD_FIRST_MARK, so perhaps we should have that for consistency?  We don't have a "first" value at SOAI level just on SOMI?
