### ISSUE TITLE
Categories for fields in the UDD mandatory field guide

### ISSUE THREAD

**Issue by alanepaull** [jiscdev/analytics-udd#209]
Many fields currently do not have a Category in the UDD mandatory field guide file. It would be worth indicating these, I think.

Preferably, this is a job for someone who knows about the importance of fields in the learning analytics model. Currently some field simply have a "TBC" value in Category 4. If someone would like to indicate to me an appropriate category for each of these, I can update the file.

Alan

**Comment by leebaylis** [comment]
https://github.com/jiscdev/analytics-udd/tree/v1.3.1/media

**Comment by alanepaull** [comment]
Monday 17 July: Agreed that @alanepaull would create a template for vendor product, based on the spreadsheet. As a test, @michaelwebbjisc agreed to fill in one of these for Study Goal to check that it works. Then can be extended to other vendor products.

**Comment by alanepaull** [comment]
@michaelwebbjisc: I've drafted a template in an Excel spreadsheet. It's in https://github.com/jiscdev/analytics-udd/blob/v1.3.1/media and it's called UDD_FieldGuide_template.xls. Please take a copy and have a play around to see if it works. Probably easiest to post any comments here, or in the template itself.
Alan

**Comment by alanepaull** [comment]
Monday 21 August 2017: Agreed to use the template as is. Vendors and services to complete their own version of the template. This work shouldn't hold up release of v1.3.1.
