### ISSUE TITLE
Student course membership

### ISSUE THREAD

**Issue by wilmTap** [jiscdev/analytics-udd#21]
From Tribal:

> This is a suggested new Entity that allows data to be stored about the student and their course on their full life-cycle from entry to exit. It contains some attributes from the UDD 1.1 Student on Course Instance that we felt better mapped to course level rather than the course instance. In time this would allow us to add more information about the student on that course, items such as the offer type they were made could be useful.
> In student record systems STUDENT_ID is not always a unique id for a student on a course. To allow a unique id to be provided and to facilitate the unique joining of records between the various 'instance' entities, we have added a new attribute called STUDENT_COURSE_MEMBERSHIP which stores a unique ID for a student and the course on which they are enrolled. This allows us to handle students who enrol on multiple courses. We also need a sequence ID to allow the records to handle movements within in a course due to transfers, study breaks etc. In order to do this we have added a new attribute called STUDENT_COURSE_MEMBERSHIP_SEQ.
> For the moment we would like to collect more information about the final outcome of a student on a course. We have added a number of new attributes to collect information about the outcome of the course these include:
> COURSE_MARK - which is the final mark of the course as calculated and stored by the SRS. COURSE_AIM_ACTUAL - the Course Aim the student achieved, this allows the analysis of whether a student achieved the award/aim associated with the course they are a member of.
> We have also added fields about when a student ended and was expected to end a course. This allows the identification of students who are taking longer to complete the course than anticipated by the institution. In addition a column has been added that allows us to group students together into cohorts that can be analysed and displayed
>      
>   together in Student Insight. The addition of the COHORT_ID is a means for an institution to create a custom cohort to trace. This could potentially be expanded to a number of attributes to allow a student to appear in multiple cohorts.
> Finally, some columns have been moved from Student on Course Instance to this entity as they are associated with the student's course membership, rather than a particular course instance.

See also: [the original thread on basecamp](https://basecamp.com/2737506/projects/10136653/messages/54963139)

**Comment by wilmTap** [comment]
In what way is student_course_membership.COURSE_AIM_ACTUAL different from looking at the course.COURSE_AIM of the latest student_course_membership.STUDENT_COURSE_MEMBERSHIP_SEQ?

**Comment by craig-petch** [comment]
Hi Wilbert,  The aim of this attribute is to capture the Course Aim Code the student left their course/study with. So they begin working towards course aim XYZ (COURSE_AIM) but left with ABC (COURSE_AIM_ACTUAL). 
Regards
Craig

**Comment by arc12** [comment]
Might it help to change the label from _AIM_ACTUAL to _ATTAINED?

In fact, I understand these are referring to the qualitication aim, and maybe QUAL_AIM and QUAL_ATTAINED would be more clear.

Example: student leaves with an ordinary rather than an hons degree from an hons course.

Adam

**Comment by craig-petch** [comment]
No problem with that at all. Whatever makes it clearest.  

Craig

**Comment by wilmTap** [comment]
Happy to change the label; it does clarify things.

My original question, though, was to confirm that the value you get from the course.COURSE_AIM associated with the latest student_course_membership.STUDENT_COURSE_MEMBERSHIP_SEQ is the same value as you'd get from student_course_membership.COURSE_AIM_ACTUAL/ATTAINED?

Put differently: is student_course_membership.COURSE_AIM_ACTUAL/ATTAINED – strictly speaking – redundant, but considerably easier to query?

**Comment by wilmTap** [comment]
student_course_membership.COURSE_AIM_ATTAINED is scoped to one degree programme,  student_course_membership.STUDENT_COURSE_MEMBERSHIP_SEQ can span several programmes
