### ISSUE TITLE
Module.subject and Course.subject have different Formats

### ISSUE THREAD

**Issue by alanepaull** [jiscdev/analytics-udd#210]
Module.subject has "String (255)".
Course.subject has "String (10) - Usually 4 characters, number followed by three digits".

I propose to change Module.subject to "String (10) - Usually 4 characters, number followed by three digits" for consistency.

Any objections? Particularly @huwrobertsjisc for validation purposes.

**Comment by alanepaull** [comment]
However, as I recall, all code values are supposed to be String (255), so in point of fact, the Module.subject is correct, and it's the Course.subject that's wrong.

So, Course.subject should be changed to String (255).

Huw/Rob/Michael: please confirm!

**Comment by huwrobertsjisc** [comment]
In this particular case both fields would be ok with a String (10) as all codes are only 4 characters in length. 

However, as we're dealing with a list of Valid Values in both fields, we should standardise these fields as suggested to use String (255) instead.

**Comment by robwynj** [comment]
For consistency and correctness, yes.

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; APMG PRINCE2 & APMG AGILE Certified Practitioner

Senior Data & Analytics Integrator - Jisc UK Learning Analytics
Cluster Lead – Jisc Data & Analytics Service

email/ skype: rob.jones@jisc.ac.uk<mailto:rob.jones@jisc.ac.uk> mobile: 07468 727040  web: www.jisc.ac.uk<http://www.jisc.ac.uk/>

**Comment by alanepaull** [comment]
Now done.
