### ISSUE TITLE
Term Time Accommodation should be on STUDENT_ON_COURSE_INSTANCE

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#212]
Since students often change, we have problem with keeping this on STUDENT. Doing it as at present means that historical data gets messed up; we loose the original Yr1 accommodation type, which is needed for computing risk for y1 students.

COURSE_INSTANCE level would capture year-to-year changes

Propose:
- add TTA to COURSE_INSTANCE as soon as possible
- flag TTA on STUDENT as being to-be-deprecated, and remove in a future version

**Comment by alanepaull** [comment]
I agree. If there's time, I'd like to get this move this to student_on_course_instance on v1.3.1. However, is this a breaking change from anyone's perspective? We have already got historical data with it on student. I guess this would mean revising historic data?

I've labelled this as v1.3.1, but that's a BIG question mark at the moment.

**Comment by arc12** [comment]
my rationale for having it on both entities in the short term is to allow for it to be non-breaking.

**Comment by alanepaull** [comment]
Sounds good to me.
Alan

**Comment by arc12** [comment]
I should maybe add that this issue came up in a client meeting today which was looking at anomalies between the truth according to their BI team and the truth according to our UDD extract. 

I expect we will put an extension in place, and supporting "best effort" code in our data pipeline in anticipation of change.

i.e. this is a real need we'll address somehow asap, as well as being a data model anomaly which should be changed in the interest of The Truth!

**Comment by alanepaull** [comment]
I'm tempted to say that "we can't handle The Truth", but I'll resist it.

Thanks for this, Adam. You're right that it could be handled by an extension. But, if I don't get an adverse reaction, I'll stick this change into v1.3.1 tomorrow morning, and reference this discussion. It would be optional on SoCI, and still on student, so shouldn't be a difficulty.

**Comment by alanepaull** [comment]
Added Term Time Accommodation to student_on_course_instance.
Flagged Term Time Accommodation on student as deprecated.
