### ISSUE TITLE
Should the Master branch be updated to 1.3.0?

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#214]
master is still v1.2.7
risk of customers using the wrong version

**Comment by alanepaull** [comment]
My understanding was that the current master is still valid for import, as well as v1.3.0. I expect that we'll update to v1.3.1 on or about 3 August.

I would prefer to have v1.3.0 as the new master, but this may not be possible yet. Perhaps @michaelwebbjisc can clarify?

**Comment by robwynj** [comment]
I would agree on 1.3.0 for now (immediately) with 1.3.1 to follow imminently

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; APMG PRINCE2 & APMG AGILE Certified Practitioner

Senior Data & Analytics Integrator - Jisc UK Learning Analytics
Cluster Lead – Jisc Data & Analytics Service

email/ skype: rob.jones@jisc.ac.uk<mailto:rob.jones@jisc.ac.uk> mobile: 07468 727040  web: www.jisc.ac.uk<http://www.jisc.ac.uk>

**Comment by alanepaull** [comment]
OK. I will do that this afternoon, saving both old branches appropriately.

**Comment by alanepaull** [comment]
v1.3.0 is now the new master branch.

**Comment by alanepaull** [comment]
See #216 for further details about versions, branches and tagged releases.
