### ISSUE TITLE
UDD version handling, branches and tags

### ISSUE THREAD

**Issue by alanepaull** [jiscdev/analytics-udd#216]
Sorry for any confusion. After some external emails, there seems to be some confusion about how we might / should handle versions, branches and tagged code releases for the UDD.

Currently, I've merged v1.3.0 branch into the master branch, so that v1.3.0 = master. There's no branch labelled v1.3.0, though there can be, if we like (and we seem to!). While we make the change-over to the new master version, I've copied the old master to master-2017-07-18, and the old v1.3.0 to v1.3.0-2017-07-18. This is temporary.

I propose to make a new Release code version, tagged as v1.3.0. Release code versions are GitHubs way of supplying releases to users - effectively, you can take the code and use it locally. We've been using this as a method of "archiving off" stuff that doesn't need a branch.

Note that Wilbert created similar tagged Releases for most of the 1.2 series, so I will adopt the same policy for the 1.3 series. I don't know if these Release versions are used - Huw might use them for validation, and it would be useful to have that confirmed. Institutions or vendors may use them; I'm unsure of that.

In respect of branches, I propose that we should have the following:

- 1.0 (very old legacy version)
- gh-pages (somebody’s old pages)
- v1.2.7
- v1.2.7a (the old master branch with the tweaks after 1.2.7 became the master)
- master (which = v1.3.0 now)
- v1.3.0 (which is the same as master)
- v1.3.1 (development version, compatible with 1.3.0)
- v1.4 (development version, with breaking changes)

I hope this isn't too confusing. Any questions, please ask, and myself or David will try to answer.

Alan

**Comment by arc12** [comment]
I am in agreement that tagging releases should be the preferred method of identifying a release.

Keeping recently completed in addition to current development branches feels "right".

I'd be inclined to drop very old branches, esp 1.0 since we will have a v1.0 xAPI soon, which might confuse

**Comment by alanepaull** [comment]
I've re-created the v1.3.0 branch and deleted the v1.3.0-2017-07-18.
I'll make the tagged release of v1.3.0 shortly.

**Comment by alanepaull** [comment]
Tagged release for v1.3.0 created.

**Comment by alanepaull** [comment]
Monday 31 July 2017: agreed to scrap branch 1.0, gh-pages.
