### ISSUE TITLE
Referential problem SoAI-SoMI

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#218]
We have a problem in the way the SoMI uniquness constraint is defined, when taken alongside the SoAI mandatory fields.

SoMI uniqueness includes course instance id but this id is not present on SoAI.

Consequently we would have to associate SoMI with SoAI on the basis of student course membership id and module instance id alone. This might (under current SoMI constraints) associate one SoAI record with multiple SoMI records. This is clearly INCORRECT.

We *think* the CI ID was put on SoMI as a convenient way of joining. If so, it should be required but not part of the uniqueness constraing.

We are in a cleft stick, from which I see two escapes:

1. remove CI Id from the SoMI uniquness constraint.
This would require the LRW to change, and checking that historical data does not violate a less restrictive constraint (we don;t think it will). Also validator change

2. add CI id to SoAI as a required field
This would require rework of existing data and LRW/validator. This may not be a big deal

Unless I missed something, leaving things as they are is not an option; the SoAI data is not rubustly linkable to SoMI, and we're at risk of something breaking in production if we dont act. It only takes one record to break things, and it might not even be real!

@michaelwebbjisc in particular - Did I miss something?

Adam

**Comment by michaelwebbjisc** [comment]
Yes, you're right as far as I can see. I don't think the CI constraint should be there and that 1) is the correct way forward.

**Comment by alanepaull** [comment]
CI id constraint looks like an error. There's no need for it for the SoCI > SoMI relationship either, I believe.

Shall I remove the CI id constraint on SoMI for v1.3.1? This would make it mandatory but not part of the PK:

```
* [STUDENT_ON_A_MODULE_INSTANCE_ID](#student_on_a_module_instance_id) **
* [STUDENT_COURSE_MEMBERSHIP_ID](student_course_membership.md#student_course_membership_id) [1] *
* [MOD_INSTANCE_ID](module_instance.md#mod_instance_id) [1] *
* [COURSE_INSTANCE_ID](course_instance.md#course_instance_id) [1]
...
\** indicates that the property is the primary key for this entity; if not provided by data supplier, will be LRW generated.   
\* indicates that the property is part of a uniqueness constraint for this entity.

```

**Comment by alanepaull** [comment]
Done. To be confirmed at fortnightly call.
