### ISSUE TITLE
Entry_quals grade and percentage for non-UCAS entry to university, for analytics, widening participation and added value indicators in FE

### ISSUE THREAD

**Issue by Josh-Ring-jisc** [jiscdev/analytics-udd#219]
Adam Cooper raised a good point in #217 

> is there other data which is available which might help to quantify on-entry academic ability/potential, either at HE or FE, both for cases where UCAS points are/are-not availble

A good question and yes is the answer. For non-traditional entry_quals we can record their grade and or percentage, so we can better understand within that entry_qual how well did they do.

This is a good compliment to GCSE grades and for HE gives a more recent indicator of ability, for FE gives a value added indicator and gives information about the student's learning journey, helpful for multiple reasons in widening participation and analytics.

**Comment by alanepaull** [comment]
Closed, as now covered in #217.
