### ISSUE TITLE
RAW marks - attribute naming convention

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#220]
At present, the convention in UDD is for names to be contextually-unique. e.g. we have MOD_ACADEMIC_YEAR and ACADEMIC_YEAR, we have MOD_ACTUAL_MARK and ASSESS_ACTUAL_MARK

The new RAW mark attributes do not follow this convention in the v1.3.1 draft.

I suggest they are modified to fall into line.

**Comment by alanepaull** [comment]
I had missed that convention. @arc12 is correct. I'll change the SoAI ones to:

ASSESS_RAW_ACTUAL_MARK and ASSESS_RAW_AGREED_MARK to bring them into line in v1.3.1.

**Comment by arc12** [comment]
@alanepaull - maybe also MOD_RAW... too
It does make these rather long names but I think the clarity is worth the visual clumsiness!

**Comment by alanepaull** [comment]
Both done. Thanks for pointing that out!
