### ISSUE TITLE
UDD 1.3 entity diagram only contains ID in student table

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/analytics-udd#222]
it's looking a bit bare! At one point I wondered if it had been converted to *only* show the primary and foreign keys so as to bring out the relations between entities (although, if so, I think that limits the usefulness of the diagram), but I see module.mod_period and module.mod_academic year in there so that can't be the case?

**Comment by joshring** [comment]
Agreed. It would be helpful if it was as in 1.2.7 but obviously updated.

**Comment by alanepaull** [comment]
Discussion at foot of #152 refers.
Intended to show PKs and FKs. However, I included module.mod_period and module.mod_academic year because they were for looking up stuff in the period entity, so like FKs.
It's not difficult to stick all the properties back in, if that would help.

I think we either need consensus on the detail in the 1 diagram, or conceivably 2 diagrams? It might be helpful to point to verbose and sparse E-R diagrams.

Any views on this?

Alan

**Comment by joshring** [comment]
If there's a demand, two separate diagrams, one for keys and one for details. 
Having a diagram containing the details is important though since it's a complicated structure.

**Comment by alanepaull** [comment]
Monday 31 July 2017: agreed to add a FK symbol to existing diagram for clarity.

**Comment by alanepaull** [comment]
Putting all the fields into the E-R diagram is problematic. Could be done, but may not be very useful. For example, student entity has 32 properties; student_course_membership has 27. I don't think that this would help to show structure. It strikes me that it might be better to look at the E-R diagram with PKs, constraints and FKs (now done), alongside the MD files or the field guide for the details.

If there's demand for a large diagram, we can do that, but only if it is useful - I envisage we'd use an A2 canvas for convenience or the font size will be too small; not important for screens.

**Comment by joshring** [comment]
From the point of view of someone who has to frequently navigate the UDD, massive diagrams would be helpful. We can move it around on our screen without issue and would be very helpful.

**Comment by leebaylis** [comment]
agreed even more so from the point of view of someone who has to *infrequently* navigate it -- I don't know it like the back of my hand, and having to toggle between the doc tables and the diagram is cumbersome...

**Comment by alanepaull** [comment]
Point taken! We'll produce a full E-R shortly.
Alan

**Comment by alanepaull** [comment]
Now done. We have both a brief and a full diagram.
