### ISSUE TITLE
ULN change in status requested, to an optional field

### ISSUE THREAD

**Issue by joshring** [jiscdev/analytics-udd#223]
The *Unique learning number* ULN is an important key which allows us to link to other governmental databases (if-and-when suitable data agreements can be made). Changing the descriptor and preparing on our end is the first part of this process.

For instance this could allow us to determine the A-level grades a student attained where that information was originally missing, so we could accurately determine a student's prior achievement.
* The long term goal would be to greatly improve the data integrity of our existing data
* The very long term could be consulting on additional information we could add from these databases which is of interest to analytics or for other users.

The ULN as currently described is:

> Unique Learner Number. For initial trial and data model development for the predictive model, this field should be left out.
https://github.com/jiscdev/analytics-udd/blob/v1.4/udd/student.md#uln

It would be helpful if we could make this instead an optional field, and avoid actively discouraging it's use.

**Comment by alanepaull** [comment]
Monday 21 August 2017: Agreed to make ULN a normal optional field. Note changed to: "The ULN should be provided as an additional point of reference. However, the STUDENT_ID will always take precedence as the unique learner / student identifier."

**Comment by arc12** [comment]
at the risk of word-smithing...
how about:
 "The ULN should be provided as an additional point of reference for integration of other data sources with UDD. However, the STUDENT_ID will always take precedence as the unique learner / student identifier within the UDD."

**Comment by alanepaull** [comment]
@arc12 No problem. Consider it done!
