### ISSUE TITLE
missing link on UDD diagrams

### ISSUE THREAD

**Issue by timstratton** [jiscdev/analytics-udd#228]
The pastoral care link between Student and Staff entities, via Tutor_Staff_ID doesn't seem to appear, even on the full UDD diagram. May have missed a subtlety here but it's puzzled me for a while.

**Comment by alanepaull** [comment]
As far as I am aware, a UDD relationship of this type between student and staff entities has not been made explicit. Some of the "old hands" might have more of an awareness of this though.

tutor_staff_id is not defined in the same way as staff_id, so they are different properties. The staff entity is wider than tutors. tutor_staff_id is also not mandatory. I think that a direct relationship here might be problematic.

**Comment by craig-petch** [comment]
To date when we have been able to collect TUTOR_STAFF_ID that relationship has been assumed and I have made sure we have a matching entry in Staff with the assumption that will be needed and that's the only place for it to go. But I don't think it's enforced in the model.  Issue #160 also raised the issues of pastoral relationships, multiple personal tutors and various questions about how this issue should be handled in the UDD.

**Comment by arc12** [comment]
In terms of the dashboard, TUTOR_STAFF_ID is useless unless it refers to an entry in STAFF.
Its how we manage authorisation of staff to see student information.
STAFF may, of course, contain additional members, but I don't think that affects the notion that TUTOR_STAFF_ID is a FK to STAFF

**Comment by alanepaull** [comment]
@arc12: I agree. However, does this mean it needs to be a formal relationship in the UDD? If so, it could be added, even if with caveats.

**Comment by timstratton** [comment]
I believe that Data Explorer assumes the link when it displays  "My students" (students for which the tutor has pastoral care responsibility)

**Comment by alanepaull** [comment]
Link added, and TUTOR_STAFF_ID made FK in student, for master, v1.3.1 and v1.3.2.
