### ISSUE TITLE
Move MOD_OPTIONAL from MODULE INSTANCE To STUDENT_ON_MODULE_INSTANCE?

### ISSUE THREAD

**Issue by craig-petch** [jiscdev/analytics-udd#229]
As many instances of modules are run with both students who attend them as core and optional. Having MOD_OPTIONAL on the MODULE_INSTANCE requires us to split a module instance into 2 for uniqueness . We have had feedback from one user so far to suggest this doesn't work well on the various dashboards (DE/Student Insight) as staff would like to see a module instance as a single instances rather broken into two instance.   This seems sensible, and is also more in line with many VLE_MOD_ID structures.  Therefore the proposal is to move this to STUDENT_ON_MODULE_INSTANCE to allow this to work and still collect an important feature.

Regards  

Craig

**Comment by alanepaull** [comment]
That does seem to be a problem. The UDD shouldn't really require this type of fudge.

Understanding that your suggestion is a valid correction, can I just check that there isn't a wider issue that may come up? MOD_OPTIONAL could be considered a property of student_on_a_module_instance, as you've suggested. On the other hand, the issue could be a symptom of the lack of a direct relationship between course_instance and module_instance. That may well be a can of worms we want to keep a lid on, but it may be worth checking out. The MOD_OPTIONAL cardinality could be seen as a property of a (currently fictional) course_module_instance entity that would link course_instance and module_instance, and allow us to specify things about a module_instance in relation to its host course(s), without having to go via student_on_a_module_instance.

I'm happy for this idea to be rejected in horror :). In which case, it does look as if the transfer that you suggest would be appropriate.

I would think that MOD_OPTIONAL would be causing this type of problem quite widely, if used?

**Comment by craig-petch** [comment]
For me - I think that's a can of worms to keep a lid on for the moment!  

We will see this issue for most, if not all, SITS users.  From a SITS perspective the data required to generate MOD_OPTIONAL is stored on the equivalent to the SOMI entity so in-essence it fits better from a selfish SITS view.

**Comment by robwynj** [comment]
Seems to make sense to me to move it (or have it on both entities, as optional, to cater for all) - surprised we haven't come across this before (maybe some HEIs don't use this marker or push out in their ETL - it's not a mandatory field anyway in the UDD).

Rob

**Comment by alanepaull** [comment]
Proposal 1: Move MOD_OPTIONAL from MODULE INSTANCE To STUDENT_ON_MODULE_INSTANCE.

Proposal 2: Add MOD_OPTIONAL to STUDENT_ON_MODULE_INSTANCE (repeat it).

To be discussed and agreed.

**Comment by alanepaull** [comment]
Monday 2 Oct 17: Agreed Proposal 2; also deprecated MOD_OPTIONAL on MODULE_INSTANCE.

**Comment by ht2** [comment]
Hi all, can I confirm if HT2 is expected to migrate existing `MOD_OPTIONAL` data from `Module` models into the respective `student_on_module_instance` models when the new field is added?

**Comment by arc12** [comment]
this is not necessary for us... we can support data in both approaches
