### ISSUE TITLE
Additional UDD mandatory properties: course.TENANT_ID, course_instance.ACADEMIC_YEAR

### ISSUE THREAD

**Issue by alanepaull** [jiscdev/analytics-udd#231]
Review of cardinality of properties in the UDD for the field guide template (#224) presented these 2 properties as potential candidates for changing from optional to mandatory in the UDD.

course.TENANT_ID: I believe we had a discussion a long while ago about this, and I understood then that the LRW has hidden identifiers that record the institution in any case. However, it looks peculiar to have this item as optional, and I suspect it wouldn't be a significant problem to make it mandatory in future.

course_instance.ACADEMIC_YEAR: it looks somewhat strange not to have the ACADEMIC_YEAR carried explicitly as a mandatory part of course_instance, because it's normally this that makes it unique and much processing will rely on it. I strongly suspect that ACADEMIC_YEAR is held in any case.

I recommend that we consider carefully whether to switch both of these from optional to mandatory, and if agreed, whether this should be for v1.3.2 or v1.4. Technically, it should probably be for v1.4 as they are potentially breaking changes. However, if there's no current difficulties with the data, it could be done for v1.3.2.

**Comment by arc12** [comment]
no objections...
tenant id is functionally redundant IMO, since the LRW authorisation is per-tenant, so it will always be the same and identical to the single INSTITUTION record.

**Comment by alanepaull** [comment]
Monday, 16 Oct: made mandatory in v1.4. In v1.3.2, note added that they will be mandatory from v1.4.

Alan
