### ISSUE TITLE
Visa (Tier4)

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#232]
The student's tier 4 visa status has been brought up by sites we're working with, and I would expect there to be general agreement from sites if offered tier 4 marker, based on the recent-ish HESA consultation https://www.hesa.ac.uk/innovation/records/reviews/student-2016-17/outcomes

Propose: add to Student Course Membership an attribute called VISA, optional, with a value space drawn from a code list comprising a single member for "Tier 4".

Code list is to allow scope for extension to other potential "leave to study in the UK" scenarios, or for non-UK clients.

For discussion, with a view to inclusion in the 1.3.x frame, as a non-breaking change.

**Comment by alanepaull** [comment]
Monday 13 Nov 17: Added VISA property to student_course_membership: https://github.com/jiscdev/analytics-udd/blob/v1.3.2/udd/student_course_membership.md
Coded field with currently only one value: "Tier4". Other values can be added to the code list at a later date.
Will close by end of week unless further comments made.
