### ISSUE TITLE
Progression code description field

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/analytics-udd#235]
From USW:
"As good as [having progression codes in the UDD] is, the code itself is not helpful [when displaying] to staff so…
1)      Can we use a description field instead – this is not accommodated in the UDD entity so suggestions please?"

Possibly a candidate for one of those per-institution tables we had discussed previously? Or just a description field in the UDD?

**Comment by arc12** [comment]
I expect there is a code-description lookup in their SRS.

We just use a lookup; same as we do for all those UDD code lists. Progression code isn't the only example. Potentially a longer list...

**Comment by alanepaull** [comment]
We could have an optional PROGRESSION_SOURCE_DESCRIPTION or PROG_SOURCE_DESCRIPTION  in the UDD as a new optional property. I don't see this as causing any particular difficulty. There aren't very many of this type of institutional raw data field that require an institution's lookup. There may be others in extensions however.

**Comment by arc12** [comment]
I suppose I should be less oblique than my last comment:
I think its a bad idea to add counterpart description fields for coded-categorical fields. We'd end up with horrible bloat. I think it is good to have a universal design principle that all categorical UDD fields contain short codes and that translation to readable labels is done using a lookup. Aside from bloat, this allows us to deal with: language localisation; changes in the preferred labels without needing to refresh data (I think it highly likely that someone at ETL time will make a decision which is not in line with what some Big Cheese will say at a later data when shown a dashboard).

**Comment by alanepaull** [comment]
Monday 13 Nov 17: Decision was to control the look up of labels and descriptions at application level for the present time.
