### ISSUE TITLE
MOD_ACADEMIC_YEAR is no longer optional in UDD 1.3.X, and is now a KEY field

### ISSUE THREAD

**Issue by Josh-Ring-jisc** [jiscdev/analytics-udd#237]
`MOD_ACADEMIC_YEAR` is now present in the following tables in UDD 1.3.X
* `student_on_a_module_instance`
* `assessment_instance`
* `student_on_assessment_instance`
* `module_instance`

As such, now it should no longer be optional, and should be described as a key, since it is required to successfully link together these four important tables.

https://github.com/jiscdev/analytics-udd/blob/v1.3.0/udd/module_instance.md#mod_academic_year

**Comment by arc12** [comment]
it really shouldn't be required to form relationships; this worked fine before we denormed the AY in this way.

From my side, the primary motivations for the denorm were: to allow for records from each entity to be filtered-down before performing a join; to avoid the need for form a join to filter on AY

I'm quite happy with this becoming mandatory tho... operationalising either of those motivations requires it to be there and I'd rather not support either/or code paths...

problem with describing it as a "key" is that people will make incorrect assumptions about uniqueness constraints.

**Comment by Josh-Ring-jisc** [comment]
After confirming with Michael Webb it seems:
`MOD_ACADEMIC_YEAR` is equivalent to `ACADEMIC_YEAR`, we should merge these two equivalent attributes in future, eg UDD 1.4.

**Comment by alanepaull** [comment]
The context of these 2 is different. One is in the context of course_instance, the other is in the context of module_instance (see definitions). They have been de-normed from those contexts, so I think it's clearer to keep them separately named, or there might be confusion in some special cases.

We've taken it as a design principle that in this circumstance we use different property names; cf. course_instance.COURSE_SUBJECT and module_instance.MOD_SUBJECT, and various dates, marks and grades in these entities.

Happy to make them mandatory on all 4 of those entities if that is agreed:
- student_on_a_module_instance
- assessment_instance
- student_on_assessment_instance
- module_instance

**Comment by Josh-Ring-jisc** [comment]
> Happy to make them mandatory on all 4 of those entities if that is agreed:

Yes please, having this information is very important.

**Comment by alanepaull** [comment]
Monday 13 Nov 17: Currently MOD_ACADEMIC_YEAR is used synonymously with ACADEMIC_YEAR, and it would be time consuming and possibly error-prone to make a change now. At the present time, it is preferable to leave it, rather than to make a change.

Cetis to assess impact of change for v1.4.

**Comment by Josh-Ring-jisc** [comment]
The cost to data quality from institutions not recognising their equivalence is also of concern. So there is a cost to not merging it also.

**Comment by arc12** [comment]
There is also STUDENT_ON_COURSE_INSTANCE

I suggest this is mandatory in the future as the other entites listed in this issue. i.e. ACADEMIC_YEAR and MOD_ACADEMIC_YEAR are mandatory wherever they appear

**Comment by alanepaull** [comment]
ACADEMIC_YEAR and MOD_ACADEMIC_YEAR are now mandatory wherever they appear in v1.4. I've also noted that they are synonymous.
