### ISSUE TITLE
New/ additional STAFFMODULEINSTANCE for DataX Attendance Register Takers?

### ISSUE THREAD

**Issue by robwynj** [jiscdev/analytics-udd#238]
Hi,

For discussion in our for regular meetings - UoG raised the need to be able to distinguish between academic staff (standard DataX users, who should be allowed to view various student data) and members of staff who are not allowed to see this data (who are predominantly student register takers, using DataX attendance).

So potential (low overhead) solution could be to introduce a new "staffattendancemoduleinstance" entity, and pickup staff from here who should ONLY be able to run and facilitate attendance registers.

Another option, would be to include a "ROLE" field within STAFF too, but this also needs further discussion here.

Kind Regards

Rob

**Comment by arc12** [comment]
I'd be inclined to add a ROLE attribute on the staff-on-mod-instance (and course); adding new entities feels like an unsustainable approach as the use cases expand.

I can see ROLE on staff might meet requirements in the current issue but it feels less controllable

This was talked about in issue #149 

I think a key consideration is that the approach should be fail-safe to missing values. -  see my last comment on #149
