### ISSUE TITLE
ChangeLog possible to show changes between UDD 1.3.x and 1.3.x+1?

### ISSUE THREAD

**Issue by robwynj** [jiscdev/analytics-udd#240]
Comment made by a HEI last week, would be useful to have a one-stop shop/ summary of changes (changelog) to provide with the README on GitHub, between version increments.

Discuss!

Kind Regards

Rob

**Comment by alanepaull** [comment]
Changes are listed with the Release version at https://github.com/jiscdev/analytics-udd/releases; this is where the release code is stored for use by developers.

I will add this link to the README file for greater exposure.

**Comment by alanepaull** [comment]
Just noting that there's already a link in the README:

## Differences between versions

The development of v1.3 has involved a number of additions and changes. This overview page provides a mapped listing of each change between version 1.2.7 and version 1.3.0. For differences between v1.3.0 and v1.3.1, see the [Release Notes](https://github.com/jiscdev/analytics-udd/releases).
