### ISSUE TITLE
Create uXAPI-type entries for each xAPI statement template.

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/analytics-udd#242]
UXAPI translator takes a tab seperate file, and matches it against a JSON file, in order to create xAPI output.  This were documented as part of UXAPI, we agreed this week that this would be more widely useful, so CETIS could take this on and incorporate it into the spec.

Here is an example for attendance:

The Tab Seperated Input File (with format borrowed from UDD:

https://github.com/jiscdev/universal-xapi-translator/blob/master/attendance-input.md

A JSON template, show where in the statement template each field goes:

https://github.com/jiscdev/universal-xapi-translator/blob/master/attendance-template.json

In these, we use and internal Jisc notation:

```**FIELD_NAME**  ```

but we can change that as its a pain to write in MarkDown (two stars being the code for **bold**)

**Comment by ds10** [comment]
moved to https://github.com/jiscdev/xapi/issues/211
