### ISSUE TITLE
Name change: Learning Data Hub (was LRW)

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/analytics-udd#247]
We're changing the name to of the LRW to Learning Data Hub as part of the move to service.

It's to avoid confusing with an enterprise data warehouse, and stop people asking me if it's Kimball or Inmon!  Learning Data Hub seems to be a better description.

We're gradually updating all our documentation - I guess in the short term it might mean a few dead links - let me know if you spot any.

Could we update the references here and on /xapi?

**Comment by alanepaull** [comment]
We have a sub-folder called "LRW Implementation Information", which contains the extension.md and filename_conventions.md files. Are these files read from the branch by anything? If not, then I'll change the folder name to "implementation". This has the merit of matching the other folder names and being one word. All the refs to this folder will need updating (I can do that).

**Comment by alanepaull** [comment]
Unless I get a reply saying "don't", I'll make this change pm today in v1.3.2.
Alan
