### ISSUE TITLE
UDD may need a "timestamp"

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#249]
Although this is not formally data, rather than metadata, I think we have a problem with the current pipeline of data from source system through to sink.

Given the delays which occur between extraction and the completion of ingestion of data into the UDD LDH (LRW), the updated-at datetime on the records is not very helpful. We really need a timestamp which is says what the datetime was when the snapshot was taken. This is similar to the way xAPI distinguishes between timestamp and stored.

Having this doesnt solve all problems, but I think it is the necessary precursor metadata in the source data which allows us to devise effective operational approaches. Other things we will need to consider (but not as part of the UDD spec) include how to deal with a lag period of unknown duration (e.g. due to a process being locked in the LRW load routines held up an update for 1 week recently). I suggest we need some kind of poor-mans transaction logic, such as always updating the INSTITUTION record after all other entities have been processed. We can then query for INSTITUTION and check the timestamp/snapshot date, and then query for the other entities with that as a WHERE inequality. Without something like this, we're in deep water when trying to query the LRW while an update is part processed, or in cases where there is an exceptional lag/delay in processing.

**Comment by michaelwebbjisc** [comment]
I've been thinking about that one too.  Updating institution sounds like a good idea to me - hadn't thought of that one. The way I think I'd do it is via an extension attribute (or rather a set of them).

The timestamp that the incoming file is the simplest date to get for extraction. 

I've also been looking at adding in some extra metadate, eg number of errors in the file, to display in data explore, at an entity level.

I think its best done at the entity level (the files can be written at different times. So we have something like:

insitutions.extensions.jisc.student-extracted-timestamp
insitutions.extensions.jisc.student-update-timestamp
insitutions.extensions.jisc.student-syncerrors-count  (you might well not need that)

Does that work for you?

We can do it at a whole set level too, but the incoming files aren't necessarily created at the same time, or at the same frequency, so I'm not sure what values we could put there that would be useful and not misleading.

**Comment by arc12** [comment]
@michaelwebbjisc probably best if we have a walkthrough of the data processing ops here, to clarify what we think will work

**Comment by Josh-Ring-jisc** [comment]
I would like to discourage the use of extensions in general, let's make this standardised as part of the UDD, with a specific table.

I would be useful to have a versioned history of the UDD, so we can look back in time and get a representative view of what was known at a given time, so we can perform training of models based on what was known at that period of time more easily.

**Comment by michaelwebbjisc** [comment]
I'm proposing we add a value 'PROVIDED_AT' to each entity.  We'll update this via UDD Sync

**Comment by alanepaull** [comment]
Could I clarify please. PROVIDED_AT is the timestamp of the incoming file of data? Or is it the timestamp of extraction specifically from the provider system? Or the timestamp of the import into the Learning Data Hub?

Alan

**Comment by craig-petch** [comment]
Michael, 
For the UDD-Sync process would it be acceptable to optionally pass the "PROVIDED_AT" date/timestamp in the entity files this would supersede the file date/time? 
Generally, the file date should be fine, but there maybe a scenario where a snapshot data has been fixed/altered and then the files regenerated at a later date .  This should give those of us who generate the data outputs a bit more control over the date that's populated and also tie it into to ETL times if needed.

**Comment by alanepaull** [comment]
Monday 8 Jan 18: To be implemented as EITHER time of file, OR optional timestamp of supply, recorded within the file. For v1.3.3, as non-breaking change.

**Comment by alanepaull** [comment]
Just checking that this needs to be added to all UDD MD files as a standard item. Plus extensions.
Please confirm, and I'll get it sorted for v1.3.3.

**Comment by Josh-Ring-jisc** [comment]
If we are going to add timestamps, we could get the ability to "look back in time" and "see what we knew about a student back in time", a very useful feature from a few timestamps, see the attached links on "**Temporal tables**"


https://docs.microsoft.com/en-us/sql/relational-databases/tables/temporal-tables
http://www.timeconsult.com/TemporalData/TemporalDB.html

**Comment by Josh-Ring-jisc** [comment]
This calls for a "Valid from", and a "Valid until" and other attributes about "date added"

**Comment by ryansmith94** [comment]
Hey @alanepaull, I'm not sure about adding this to extensions because I'm not really sure how you'd provide or retrieve the timestamp for specific extensions given that their provided and retrieved as key values pairs in a JSON object.

**Comment by alanepaull** [comment]
Thanks @ryansmith94, I was fishing for such a response. I'll omit in relation to extensions.

**Comment by ryansmith94** [comment]
Ok great thanks @alanepaull 👍

**Comment by alanepaull** [comment]
Completed.

**Comment by arc12** [comment]
@ryansmith94 - there is an implication for the LL indexes too; a key use case for PROVIDED_AT is to use it as a query parameter, as we now do with the updated-at date. Is this "in hand" in HT2?

**Comment by ryansmith94** [comment]
Hi @arc12 yeah that's in hand. We'll be creating those indexes.
