### ISSUE TITLE
Degrees of a student

### ISSUE THREAD

**Issue by xchopin** [jiscdev/analytics-udd#250]
Hi,

I didn't find where the degrees of a student are saved ? the only stuff about this that I've found is the COURSE_AIM attribute in the [course model](https://github.com/jiscdev/analytics-udd/blob/4ac431e2e24ef8a166977cd1399e3f52a85d9584/udd/course.md).

Did I misread or it's not implemented yet ?

Thanks.

**Comment by alanepaull** [comment]
Hi xchopin

Could you clarify your question please? 

Our specification describes the student's prior achievements under the student_course_membership entity.

Alan

**Comment by xchopin** [comment]
Hi Alan,

In fact I would like to have the background of a student; for example I would like to know what are its degrees before it came to our university ; I don't know if you get what I mean

**Comment by alanepaull** [comment]
I understand. This isn't something that the Jisc Learning Analytics Service has. For more information about Jisc's Learning Analytics work, see https://www.jisc.ac.uk/rd/projects/effective-learning-analytics.

For UK degree verification, you might try the Hedd service at: https://hedd.ac.uk/.

**Comment by xchopin** [comment]
Ok thanks for the informations.
