### ISSUE TITLE
Maximum course duration value

### ISSUE THREAD

**Issue by timstratton** [jiscdev/analytics-udd#255]
UEA have hit a problem with the 10 year limitation on student_course_membership.course_duration. They have 4 students who are still current but started over 120 months ago.  The longest duration is 154 months.  
 
They’re requesting that we increase the allowable range to 200-240 months to enable their data to load successfully, "whilst still causing wildly incorrect records to fail".

**Comment by arc12** [comment]
The spec states:
"The expected length of time in months that the student will take to complete the course."

It is not the duration the student has been on the course; that would be calculated.

COURSE_DURATION captures facts like "its a 3 year course" (expressed in months)

**Comment by timstratton** [comment]
Understood - but if a student has already been on a course for 154 months, then they're now going to expect it to take somewhat longer than that. Or are we saying that this is the length of time that it was originally expected that the course would take (and not a current view)?

**Comment by michaelwebbjisc** [comment]
I think the semantics here is that it says:

'The expected length of time in months that the student will take to complete the course'.

 I think we actually meant:

The expected length of time, **at course commencement,** in months that the student would take to complete the course.

What's the exact situation here?  Any course that has an expected complete time of > 10 years should probably have a null value - I don't think any course would have an expected time of > 10.

**Comment by arc12** [comment]
@michaelwebbjisc +1

**Comment by alanepaull** [comment]
I propose to change the definition to @michaelwebbjisc's suggestion. It looks as if this difficulty then disappears.
