### ISSUE TITLE
Student HUSID or HUS_ID

### ISSUE THREAD

**Issue by ryansmith94** [jiscdev/analytics-udd#257]
Hi, can I just check that the [`HUSID` property in the Student entity](https://github.com/jiscdev/analytics-udd/blob/master/udd/student.md#husid) is named correctly. Not sure if it should be `HUS_ID` for consistency. Currently the LDH is accepting `HUS_ID` and I'm planning to correct it to `HUSID` to match the documentation here, just want to check that's correct first.

**Comment by alanepaull** [comment]
HUSID is derived from HESA: https://www.hesa.ac.uk/collection/c16051/a/husid. It's normally referred to as HUSID, so I believe the documentation is correct.

**Comment by ryansmith94** [comment]
Ok great, I'll get that changed. Thanks @alanepaull
