### ISSUE TITLE
UDD Field Guide template: level of priority column

### ISSUE THREAD

**Issue by alanepaull** [jiscdev/analytics-udd#258]
Craig and I have been working on the UDD Field Guide spreadsheet template, using the Tribal SI one as a case. We have 2 slightly conflicting requirements, 1 for validation and 1 for informing consumers about the level of priority of data items.

Validation: for validation purposes, we can use Mandatory and Optional (and straightforward "not used" - these are deleted from the spreadsheet for that product / service). Mandatory means Mandatory.

Informing: there are a number of fields that Tribal would consider "very much preferred", though they're not actually Mandatory for LDH to run. While this type of soft information can be covered in the Comments column, it's likely to be much more useful to the user if we have a Level of Priority column along the lines of the former Categories 1 to 4 that were in the old version. Then the user can filter on the priorities and get much more of a view of what's really required and what's really optional.

A suggestion would be to introduce a Level of Priority column with the following possible values:

Mandatory       Required for LDH to function (as per the validation column)
Important        Absence will cause serious issues with the product / service
Preferred         Likely to be useful, but not always required

This idea would make the spreadsheet much more usable. However, we're unsure of the validation requirement at the moment. Is there an idea that validation might give information back to the user about more than just Mandatory / Optional?

**Comment by alanepaull** [comment]
At yesterday's discussion (Mon 19 Feb 18) we agreed to revise the Field Guide Template to include values of Mandatory, Important, Preferred and Not used against the cardinality/importance column. I've updated the Field Guide Template accordingly.

Craig: would you be able to update the draft Tribal one? I had a look  and found I couldn't definitively interpret your comments into the Mandatory, Important, Preferred and Not used values.

I'm also looking at how we might handle version control of each Field Guide.

**Comment by alanepaull** [comment]
I've committed the draft Tribal Field Guide as at end Jan 2018, so that @gmoger-jisc can have a look at it. Bear in mind that it will be changing to the newly agreed format.

**Comment by craig-petch** [comment]
@alanepaull Please find attached an updated Field guide for discussion. This is still a draft but should give us a view of how it works.  

[Revised_udd_field_guide_v1.3_sits_20180409.xlsx](https://github.com/jiscdev/analytics-udd/files/1889084/Revised_udd_field_guide_v1.3_sits_20180409.xlsx)

**Comment by robwynj** [comment]
This will be good to share with Institutions, but  will not be integrated into the UDD Validator software during this current academic year /until further notice.

Kind Regards

Rob

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; APMG PRINCE2 & APMG AGILE Certified Practitioner

Lead – UK Data & Analytics Services; Senior Data & Analytics Integrator
email: rob.jones@jisc.ac.uk<mailto:rob.jones@jisc.ac.uk> skype: robwynj twitter: @robwynjones
mobile: 07468 727040  web: www.jisc.ac.uk<http://www.jisc.ac.uk>

**Comment by alanepaull** [comment]
Thanks @craig-petch. I wonder if we need all the comments? For Primary and Foreign keys we could just put "Primary Key", "Foreign Key" and leave out the other words. 

I think less words is best, so that what we put in stands out. I suggest the following standard wording for some of the comments:

Primary key
Foreign key
Absence will cause serious issues. Please discuss any data quality issues.
Likely to be useful, but not required.
Uniqueness constraint: Learning Data Hub will generate if not supplied, but supply is preferred.

Also, no comments against Not Used.

Then any product/service specific comments added in as required (as you've done for many).

**Comment by gmoger-jisc** [comment]
Agree with @alanepaull in that it is a little verbose.  For those where 'absence will cause serious issues' are we offering any more information on what?

**Comment by alanepaull** [comment]
8 May 2018: @michaelwebbjisc has 2 more Field Guides in draft - to be supplied to @alanepaull for uploading in due course.
