### ISSUE TITLE
ENTRY_POINTS and changes to the examination structure of A-levels

### ISSUE THREAD

**Issue by Josh-Ring-jisc** [jiscdev/analytics-udd#259]
**A little history:**
**2010**: A* grade introduced
**2017**: new points system introduced and AS levels scrapped

It is possible in future we will have GCSE-style grade boundaries also and other disruptive changes to A-Levels. These large changes will impact how we interpret the ENTRY_POINTS for that student.

So I propose a way to include the `date of qualification` entry so we can determine what UCAS points system applied to them.

**Comment by arc12** [comment]
I understand there are two separate issues:
1. changes in award schemes (grades/levels etc)
2. changes in the UCAS tariff:
 - a) which are backwards compatible, i.e. where the points score doesnt change for historical awards
 - b) which are not backwards compatible

(1) is likely to be accommodated by (2a) as part of business as usual admissions process change

(2b) may also happen, and is the one I think we need to be concerned with. ergo its not so much an award date which matters but a tariff version

**Comment by Josh-Ring-jisc** [comment]
```I think we need to be concerned with. ergo its not so much an award date which matters but a tariff version```
If it's easier and still contains the same information I am all for it. Sold.

**Comment by alanepaull** [comment]
Monday 19 Feb 2018: plenty of discussion on this issue. The key aspect was seen as the need to identify the particular schema used by the institution supplying the data on UCAS tariff for the entry points data. Specifically: whether it was the new tariff, the old version or not known.
Consistency of approach for specific courses and students is vital for usefulness of the analysis.

A possible solution, to form a starting point for discussion, would be to introduce an ENTRY_POINTS_SCHEMA property that would identify the schema as the old or the new one, with an additional "not known" value, so that work by the institution could be minimised. 

We decided to ask pilot institutions what they have in terms of data relating to the schema (can they identify new and old?, what about excluded qualifications?), and to instroduce the possible solution. Alan to do this.

**Comment by alanepaull** [comment]
ENTRY_POINTS_SCHEMA property added to student_course_membership. See: https://github.com/jiscdev/analytics-udd/blob/v1.4/udd/student_course_membership.md#entry_points_schema

**Comment by alanepaull** [comment]
Monday 9 April 2018: Question - do providers have their own way of relating old and new tariffs? For example, own schemas for modelling differences? Agreed that @alanepaull would ask on the Basecamp group.

**Comment by arc12** [comment]
Is this relevant:
https://www.hesa.ac.uk/support/documentation/tariff
?

I've not spent the time to assess it,

**Comment by alanepaull** [comment]
Probably. Thanks for the link.

What this confirms is that HESA is taking the old data and calculating new tariff values from the source, where UCAS has indicated new tariff values for the qualifications. So, not attempting to calculate new tariff from old, but re-calculating from source. That was my expectation from how the new tariff was presented (conceptually different and so on).

**Comment by alanepaull** [comment]
8 May 2018: Generally institutions will need to process this data prior to delivery; no standard converter exists, and it's problematic to create one. While ENTRY_POINTS_SCHEMA may not be operationally useful for learning analytics (@alanepaull to check with @Josh-Ring-jisc), it could supply a label.

**Comment by Josh-Ring-jisc** [comment]
Yes no converter exists, happy to help provide one if needed

I disagree it is not useful, since we need to know what schema they are marked against to know how well they have done. It is also likely they are going to change the A-levels to the GCSE-type system in the future.

**Comment by alanepaull** [comment]
From UCAS: "It is important to emphasise that the methodology behind the new Tariff is entirely different to the version developed in 2001. This means that points under the two systems are not comparable."

For example, AS levels under the new tariff are 40% of the value of an A level, whereas in the old tariff they were 50%. Highers and Advanced Highers have slightly more value under the new than the old tariff. There are many more quals in the new tariff than the old one. For composite quals the new tariff allocates points for components, whereas the old one gave a single total in many instances.

Worth noting also that an AS in the same subject as an A level doesn't count, so you cannot just allocate values and tot them up.

All this means that, if you know the old tariff points held by a student, you cannot accurately state how many the student will have under the new one. For example if I have 240 points in the old system, that could be between 88 and 102 points in the new system, just taking into account A, AS and Scottish quals.

A simple calculation based only on the old tariff would skew the points of those with AS levels or Scottish quals around 10% of the total; AS having an increased value, Scottish qualifications less. If we knew the actual quals held, then we could re-calculate using the new tariff - but this information isn't necessarily available to the provider, and certainly not in the UDD.

It feels dangerous to me to try to calculate an equivalence, even if it feels vaguely correct. For some (a minority), it's bound to be wrong.

**Comment by arc12** [comment]
+1

**Comment by alanepaull** [comment]
ENTRY_POINTS_SCHEMA was added to v1.4 in early March. It's MANDATORY if ENTRY_POINTS is used. Usefulness of these data items noted.
Still open to suggestions on the "common representation" issue. However, our discussions to date have not come up with a workable solution. Perhaps we need to consult HESA and / or UCAS?

**Comment by alanepaull** [comment]
Monday 21 May 2018: Simplified to:

If HEP cannot give schema, don't give points.
Also agreed that we won't attempt a common representation of the 2 tariffs, as it's potentially misleading in many cases, and open to misinterpretation, particularly if the schema is not given, or incorrect.

# Proposal - Amend properties to:

## ENTRY_POINTS
### Description
This property indicates the entry points at Level 3 / SCQF Level 6 gained by the student prior to entry to the institution, using the UCAS Tariff points scheme.

### Purpose
For analytics

### Derivation
UCAS: https://www.ucas.com/advisers/guides-and-resources/information-new-ucas-tariff-advisers

### Valid Values
Any

### Format
Int

### Notes
If this property is used, ENTRY_POINTS_SCHEMA is MANDATORY. If the schema is not known, omit ENTRY_POINTS (leave blank in TSV).
ENTRY_POINTS does not include Level 2 / SCQF Level 5 or lower qualifications.
Omitting this property may hinder the development or use of an effective analytics model.

## ENTRY_POINTS_SCHEMA
### Description
This property specifies the particular UCAS Tariff points scheme used for the data in ENTRY_POINTS. For courses starting in or after 2017 use the 2017 UCAS Tariff points scheme. This replaced the original scheme that ran from 2001 to 2016.

### Purpose
For analytics

### Derivation
UCAS: https://www.ucas.com/advisers/guides-and-resources/information-new-ucas-tariff-advisers

### Valid Values
<table>
<tr><td>ENTRY_POINTS_SCHEMA</td><td>DESCRIPTION (ENGLISH)</td><td>DESCRIPTION (WELSH)</td></tr>
<tr><td>2017</td><td>UCAS Tariff Scheme 2017 (the "new" scheme)</td><td></td></tr>
<tr><td>2001</td><td>UCAS Tariff Scheme 2001-20016 (the "old" scheme)</td><td></td></tr>
</table>  

### Format
String (255)

### Notes
 If using ENTRY_POINTS, this property is MANDATORY. 
If the Tariff scheme is not known: omit ENTRY_POINTS_SCHEMA (leave blank in TSV).

**Comment by Josh-Ring-jisc** [comment]
2017 and 2001 are integers

**Comment by alanepaull** [comment]
We have a policy in the UDD that UDD code frames should be strings.
Is that a problem in this instance?

Alan

**Comment by arc12** [comment]
The schema should be a string, for sure.

Arguably, the permitted values could be alphanumeric.

I think maybe using plain year indicators may cause confusion; I wouldnt put money on no-one ever putting the year of entry in the data ;-).
Suggest "UCAS01" or "U01" ("UCAS17" or "U17")

Linked to this, I am not in favour of documenting ENTRY_POINTS as being strictly UCAS. An earlier definition was more flexible, referring to FE, and I think that it is desirable to allow ENTRY_POINTS to be used in non-UCAS settings. If anything, the facility which the schema affords is a more relaxed definition of what ENTRY_POINTS means.

So:
ENTRY POINTS is just a summative value for on-entry attainment in a recognised scheme
ENTRY POINTS SCHEMA is the identity of the recognised scheme

**Comment by alanepaull** [comment]
Monday 4 June 2018: agreed minimum option above:

- Re-factor the description of ENTRY_POINTS and ENTRY_POINTS_SCHEMA along the lines suggested above.
- Put in place the codes for the 2 UCAS Tariff schemes that are currently in operation.
- Add in any schemas that HEPs/FECs want to use now (maybe none yet)
- Make an explicit Note that the UDD vocab for the schemas will be developed.

Continue to enable use of AVERAGE_GCSE_SCORE (so, leave in).

**Comment by alanepaull** [comment]
For ENTRY_POINTS, I've left the format as INT for now. I suspect INT is more useful for calculations in respect of UCAS tariff points, although other schemas may require Strings. To be addressed when / if we have other schemas that don't use INT values.
