### ISSUE TITLE
New Staff Teaching On Course Instance

### ISSUE THREAD

**Issue by wilmTap** [jiscdev/analytics-udd#26]
From Tribal:

> 
We have not yet implemented this, but there is likely to be a requirement to link staff to courses as well a modules. It would seem worthwhile to have the option to map course leader staff to courses.

Which milestone to go for?

**Comment by robwynj** [comment]
Could be useful for data access purposes, course-wide?

Kind Regards

Rob

**Comment by wilmTap** [comment]
OK, included in v1.2

**Comment by wilmTap** [comment]
Make sure it's in 'additional', not 'core'
