### ISSUE TITLE
Student assessment instance

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/analytics-udd#261]
can we add a 'source' to student assessment instance?  Some institutions are getting the data from multiple sources and want to view the source in datax.

**Comment by alanepaull** [comment]
How about something like this? It could be added to v1.3.3 I believe.

## ASSESSMENT_DATA_SOURCE
(0..1, so optional)

### Description
Provider's label showing the source of the data recorded in ASSESS_RAW_ACTUAL_MARK.

### Purpose
To identify the data source, particularly in cases where providers have multiple sources and need to view the source in LA services.

### Derivation
Provider

### Valid Values
Any
Control of the values of this property rests with the provider and any vendor responsible for data imported into the Learning Data Hub. Consistent values for sources should be maintained.

### Format
String (255)

### Notes

**Comment by alanepaull** [comment]
Monday 9 April 2018: Agreed to implement the above proposal. Now done.
