### ISSUE TITLE
Confirmation of consent

### ISSUE THREAD

**Issue by alanepaull** [jiscdev/analytics-udd#262]
From Rob: would it be useful to indicate whether a student has given, not given, or not been requested (yet) for consent for LA? To be discussed.

**Comment by arc12** [comment]
I think the issue of consent is probably more nuanced than a single yes/no/not-sought "consent for LA"; there is a lot more for-what and using-what detail.

**Comment by alanepaull** [comment]
8 May 2018: to be handled outside the UDD. No action required.
