### ISSUE TITLE
ACTIVE_MEMBERSHIP

### ISSUE THREAD

**Issue by willblenkhorn** [jiscdev/analytics-udd#266]
Hi everyone,

The ACTIVE_MEMBERSHIP field in 'student_course_membership', contains 3 values active, not-active and unknown. We think this should become active and not-active, as it should be clear to a university whether the student is active or not. 

Regards,

Will

**Comment by alanepaull** [comment]
8 May 2018: Agreed to delete 3, not known. "Not active" is inferred from not known or where the data is not supplied; note: mandatory in v1.4, optional in v1.3.
