### ISSUE TITLE
Propose tweak to INITIAL_ english/maths assessment description

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#267]
(on student course membership)

This currently says (for English):
"States a numerical value of the institution's measure of the student's capability in English at the start of their programme of learning."

Proposed amendment:
"States a numerical measure of the student's capability in English at the start of their programme of learning", and add a usage note to indicate this is typically a diagnostic assessment undertaken by the institution around the time of enrolment.

Rationale:
avoid enshrining non-essential limitations in the spec; this is not necessarily an assessment carried out by the institution

**Comment by alanepaull** [comment]
I agree. This is an easy documentation change, so could go straight into our v1.3.4. It doesn't look like there are any other implications.

Applies to INITIAL_ASSESSMENT_ENGLISH and INITIAL_ASSESSMENT_MATHEMATICS.

**Comment by alanepaull** [comment]
8 May 2018: Agreed.
