### ISSUE TITLE
Classifying students not returned to HESA

### ISSUE THREAD

**Issue by gmoger-jisc** [jiscdev/analytics-udd#268]
In discussion with Gloucester we have seen students returned with a LOCATION_OF_STUDY as '7'. This is not a valid value according to the current spec:
https://github.com/jiscdev/analytics-udd/blob/master/udd/student_on_course_instance.md#location_of_study

These are actually overseas students and so not returned to HESA.  As such no valid HESA code is generated for them by the institution.  Asking them to classify these students is quite a change of process for some institutions and in how they think about student data (giving HESA codes to students who would not be returned).

Options for discussion:

- Add new value to list for 'not HESA returned'

- Field left blank

- Comply with HESA classification and UDD spec as is, with institutions having to apply the appropriate codes for all students they wish to be included in learning analytics

**Comment by arc12** [comment]
I think the field description is important:
"This property indicateS whether the student is based on campus, is studying abroad, on placement, and so on."

This can still apply to a student in both of two cases I can see for "overseas student":
A - attending a UK campus = the attribute is just as it would be for a UK student
B - attending an overseas campus = the attribute is the same except that "abroad" is now relative to the overseas campus location.

The student doesnt need to be coded in a HESA return for this to be a valid attribute; the essence is the definition and definition of codes. The codes may have been derived from the HESA but IMO this is informative; it is the definitions  of the concepts in UDD which is important.
