### ISSUE TITLE
New Staff entity

### ISSUE THREAD

**Issue by wilmTap** [jiscdev/analytics-udd#27]
From Tribal:

> It seems we need an entity to store staff details which will be linked to the Staff Teaching on Module Instance (and also Staff Teaching on a Course Instance). For Student Insight this would be used to automatically populate the system with user accounts for these staff.

I'm assuming this will stay in the 'additional' section?
Are we sure staff.STAFF.TITLE is compulsory?

**Comment by robwynj** [comment]
Yes, STAFF must stay in additional.

I assume TITLE is free text, optional I would assume (could be used for display purposes in SSP for example), and not a set of options (codes).

Kind Regards

Rob

**Comment by robwynj** [comment]
As per previous issue down the list, add the HESA 'STAFFID' as an optional field in the STAFF entity.

https://www.hesa.ac.uk/index.php?option=com_studrec&task=show_file&mnl=15025&href=a^_^STAFFID.html

Kind Regards

Rob
