### ISSUE TITLE
UDD development timeline

### ISSUE THREAD

**Issue by Josh-Ring-jisc** [jiscdev/analytics-udd#272]
It would be helpful if we could maintain a development timeline on the UDD, so the release schedule can be easily anticipated.

**Comment by alanepaull** [comment]
Monday 4 June 2018: Agreed to announce releases at the top of the readme file and as an issue on the tracker with a RELEASE label.

I've added this statement to the top of the README:

_Version 1.4.0 finalised w/c 4 June 2018. For release in September 2018._

and I've put in the Introduction a link to the Releases and version control section. "Release" in this case means it will be made the master branch at that point. Is it actually the intention to make v1.4 the master during September, or should that be earlier? v1.3.3 will still be available as a branch.

**Comment by joshring** [comment]
Dead link on UDD 1.4 introduction should be:

> https://github.com/jiscdev/analytics-udd/tree/v1.4.0#releases-and-version-control

minor issue with capitalisation but needed for the link to work, also can we replicate this on master and other branches?


> Releases and version control

Would be nice to be: 

> Release schedule and version control

**Comment by alanepaull** [comment]
You were too quick for me! I was just checking and amending the link!

I'll sort the other bits out now.

**Comment by alanepaull** [comment]
@Josh-Ring-jisc: I've done v1.3.3, master and 1.4.0. I'll be matching 1.4.1 to 1.4.0, so no problem there. I don't propose to go back to older branches; hope that's OK.
