### ISSUE TITLE
Preferred file type should be TSV

### ISSUE THREAD

**Issue by gmoger-jisc** [jiscdev/analytics-udd#273]
Found the preferred file type on the page below as JSON.  Can this be changed to TSV as it is easier for us to validate.

https://github.com/jiscdev/analytics-udd/blob/master/implementation/filename_conventions.md

**Comment by Josh-Ring-jisc** [comment]
As discussed, TSV format gives simplified data validation for institutions and is a more familiar format to work with.


In addition to the above I think we need to be stricter about enforcing valid file formats.
So submitting `student.data` will **not** be accepted, but submitting `student.tsv` or `student.json` or `student.xml` etc will be accepted

**Comment by alanepaull** [comment]
No problem. Initial preferred file type was JSON, but this can be changed. I'll check this through and amend the UDD repository.

The file name formats are also prescribed in the filename_conventions.md.

Other LA documentation would need updating (I have no access to that): https://docs.analytics.alpha.jisc.ac.uk/docs/learning-data-hub/Technical-Guide:--Data-In-:--UDD-Managed-Integration. Plus, are there any other relevant places outwith UDD repository?

**Comment by alanepaull** [comment]
Monday 4 June 2018: agreed as above. filename_conventions.md and readme.md amended accordingly.
