### ISSUE TITLE
MOD_START/END_DATE in module_instance

### ISSUE THREAD

**Issue by willblenkhorn** [jiscdev/analytics-udd#279]
Hi everyone,

I maybe wrong, but I feel that the MOD_START/END_DATE which currently sits in 'student_on_a_module_instance' could easily be part of module_instance. That way less errors will occur with module dates for module instances, or am I missing something?

Regards,

Will

**Comment by craig-petch** [comment]
Hi Will, Module based dates can be tricky. They can be stored at various levels within an SRS with a level equivalent to SOMI being the lowest. Originally they were put on to SOMI as in some instances we see dates change for certain students when resits are added into the equation. However from what we’ve seen so far module based dates are not particularly well maintained or managed so there’s are larger challenge around the maintenance of the underlying data above that of the UDD structure. If periods are being returned you’ll get the start and end date for the period of the module instance which in many cases may well be the same as what you’ll see at a module instance level.

Cheers

Craig

**Comment by willblenkhorn** [comment]
Hi Craig,

Thanks for your reply. Fair enough, I'm only now coming to appreciate how complex a SRS can be and the amount of work that must go into it to make it work.
