### ISSUE TITLE
Non-zero, positive integers for MOD_COMPLETED_ATTEMPT and MOD_CURRENT_ATTEMPT

### ISSUE THREAD

**Issue by Josh-Ring-jisc** [jiscdev/analytics-udd#283]
**Documentation change:**  It should be documented that the following are non-zero integers:

`MOD_COMPLETED_ATTEMPT` and `MOD_CURRENT_ATTEMPT`

https://github.com/jiscdev/analytics-udd/blob/5aa8dad8dc37322db08877d6c20340ef0ab1a18d/udd/student_on_a_module_instance.md#mod_completed_attempt

**Comment by alanepaull** [comment]
16 July 2018: agreed to amend documentation and format to permit only positive non-zero integers. If no MOD_COMPLETED_ATTEMPT or MOD_CURRENT_ATTEMPT, don't supply the data, do not insert "0".
