### ISSUE TITLE
ASSESSMENT_RESULT is not documented correctly

### ISSUE THREAD

**Issue by petekeating** [jiscdev/analytics-udd#285]
The link from the top of: https://github.com/jiscdev/analytics-udd/blob/master/udd/student_on_assessment_instance.md  doesn't work.
Scrolling down the page it looks like the heading is missing and the information is mixed in with the previous and next elements.
Cheers.

**Comment by alanepaull** [comment]
Thank you, petekeating. Now repaired.

Alan
