### ISSUE TITLE
Make UDD_VERSION mandatory in 1.4.0 onwards.

### ISSUE THREAD

**Issue by willblenkhorn** [jiscdev/analytics-udd#290]
Hi all,

I think the UDD_VERSION should be a mandatory requirement, this helps us to determine what fields are missing and what the data should look like.

Regards,

Will

**Comment by willblenkhorn** [comment]
If this can't be made mandatory in 1.4.0, then it should be made mandatory at the earliest point possible to make sure no breaking changes occur.

**Comment by alanepaull** [comment]
UDD_VERSION is mandatory; it's been mandatory since it was introduced in v1.3.0. Is there somewhere where it is indicated as not mandatory?

**Comment by willblenkhorn** [comment]
That's fine. I must of missed that in the markdowns.
