### ISSUE TITLE
Maintain JSON with UDD spec

### ISSUE THREAD

**Issue by gmoger-jisc** [jiscdev/analytics-udd#292]
Can we look to implement a udd spec stored and maintained as JSON?

This will help with certain processes we are implementing (validation and corrections), so that we can easily reference a single source of truth.

At this stage I am only look for entity fields but this could later be expanded to store data types etc.  For example:
```
{
    "INSTITUTION": [
        'TENANT_ID',
        'TENANT_NAME',
        'UDD_VERSION',
        'MODULE_VLE_MAP_MODE',
        'PROVIDED_AT'
        ]
}
````

**Comment by alanepaull** [comment]
The spec needs all the current information in it. I wouldn't want to store and maintain an entirely separate and incomplete JSON spec without direct and automatic linking to the current github repository. However, it shouldn't be impossible to set up an automatic JSON output for whenever we do a code release (for example).

I'll have a look at how to implement that, including the best location.

Would it be OK to refresh only at each code release? Or are you thinking of a more frequent refresh?

**Comment by gmoger-jisc** [comment]
Each code release would be sufficient.

**Comment by alanepaull** [comment]
Monday 10 September 2018: Agreed. Initially include only entities, properties and data types within 1 JSON file. Store the file in /implementation folder.
Alan to draft and pass to Gareth for checking.

**Comment by alanepaull** [comment]
Added udd.json to /implementation in master, v1.4.0 and v.1.4.1_development.
