### ISSUE TITLE
UDD 1.4 live

### ISSUE THREAD

**Issue by gmoger-jisc** [jiscdev/analytics-udd#293]
@alanepaull and @ds10 

When is 1.4 going to be pushed live to master?

**Comment by alanepaull** [comment]
This can be carried out whenever desired. I was keen to avoid confusing any folks who might be using v1.3.3 via the master branch. When would you prefer this to be done, and who has the final say?!

**Comment by alanepaull** [comment]
I can do the merge tomorrow, Wednesday. v1.3.3 will still be available in its own branch and code release. I'll double-check whether anything went into v1.3.4 but not into v1.4.0.

**Comment by alanepaull** [comment]
v1.4.0 has now been merged into master. There were no substantive issues in relation to v1.3.4 (just 1 small tweak to a definition). 
If you find any problems, please let me know.
