### ISSUE TITLE
MOD_LOCATION still showing on module instance entity

### ISSUE THREAD

**Issue by gmoger-jisc** [jiscdev/analytics-udd#295]
I believe MOD_LOCATION should be deleted from module instance:
https://github.com/jiscdev/analytics-udd/blob/master/udd/module_instance.md#mod_location

This was documented in the changes 1.4.  Can you confirm?

**Comment by alanepaull** [comment]
Apologies, this is an error in the release notes, not in the spec. It was MOD_OPTIONAL that was deprecated (from v1.3.2); this **has** been deleted from v1.4.0. Unfortunately, I put MOD_LOCATION instead of MOD_OPTIONAL in the release notes.

I'll amend them now.

**Comment by alanepaull** [comment]
Release notes, differences.md and spreadsheet amended.
