### ISSUE TITLE
Mandatory fields

### ISSUE THREAD

**Issue by gmoger-jisc** [jiscdev/analytics-udd#298]
Do we have a definitive list of mandatory fields in the UDD?  We have added things like ACTIVE_MEMBERSHIP in 1.4 but I don't see where this is specified in the documentation.

**Comment by alanepaull** [comment]
We have mandatory fields indicated in each MD file in the list at the top. In addition, the UDD_FieldGuide_template.xls lists all the mandatory fields. The E-R diagrams list primary and foreign keys. These files are all in the /media folder.

Noticing that the spreadsheet doesn't have ACTIVE_MEMBERSHIP as mandatory, I will check all these.

**Comment by gmoger-jisc** [comment]
Thanks Alan - got it.  The field guide needs to be updated with active membership and academic year fields being mandatory.

**Comment by alanepaull** [comment]
master, v1.4.0 and v1.4.1_development branches updated.
