### ISSUE TITLE
Suggest labels for UDD areas

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#3]
Would it make sense to have labels to assign to issues according to the section of the UDD to which they relate. That would help us to find previous issues and avoid raising duplicates (and add comments to an existing), and help with processing.

BTW - it isn't possible for me to add a label with current permissions. This isn't necessarily a problem, having labels would still help, even if added as part of a Jisc review step in the workflow.

**Comment by wilmTap** [comment]
Fair enough- will implement that. I've already run into that issue...

**Comment by robwynj** [comment]
Great idea Adam :)

Many Thanks, Rob
