### ISSUE TITLE
Should UDD specify a character encoding?

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#30]
Although software/libraries have got better at auto-detecting encoding, and avoiding horrible encodings. it can still be a drag...

Should UDD be explictly UTF-8 encoded unicode?

Adam

**Comment by wilmTap** [comment]
Yes!

Do we need to specify a format for the data dump? e.g. CSV?

**Comment by wilmTap** [comment]
Specify UTF8. but not file format

**Comment by robwynj** [comment]
Agreed - close issue
