### ISSUE TITLE
Version update to v1.4.1

### ISSUE THREAD

**Issue by alanepaull** [jiscdev/analytics-udd#308]
There will be an update of the UDD to v1.4.1 later today.
This is a minor, non-breaking-change release.

In summary, v1.4.1 release of UDD implements the following, compared to v1.4.0:

- PROVIDED_AT: Added 'Z' clarification to date/time format: in ISO 8601 format - YYYY-MM-DDThh:mmZ or YYYY-MM-DDThh:mm is acceptable
- course: Added code I78 to COURSE_AIM
- student_course_membership: updated WITHDRAWAL_REASON codes and clarified ACTIVE_MEMBERSHIP Notes
- Updated HESA links in many of the MD files to 2018-19 links
- New event and student_event entities added
- New UDD Field Guide introduced and old template removed
- New E-R diagrams and updated change spreadsheet created

**Comment by alanepaull** [comment]
Version 1.4.1 is now live. Please let me know if you experience any problems.

**Comment by alanepaull** [comment]
I propose to delete branch v1.4.0, unless this is still required for anything.

Live branches should be:
- master (v1.4.1)
- v1.4.2_development
- Later v1.5 for breaking changes

Plus any temporary branches that users create.

**Comment by gmoger-jisc** [comment]
Thanks for this Alan. Happy for you delete if you think that's best.
