### ISSUE TITLE
EVENT_NAME - Why mandatory?

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#313]
In the event entity, name is mandatory.
This is inconsistent with the xAPI recipe

I cant see why this should be required, or that it would necessarily exist in source data.

Propose: EVENT_NAME should be optional

**Comment by alanepaull** [comment]
This looks very much like an error. I can update it for the next dot release, as this isn't a breaking change. @gmoger-jisc: are you happy with that? If it causes a problem now, we could do a v1.4.2 release to correct it.

**Comment by gmoger-jisc** [comment]
Yes that is fine.  I can see in the database that it has not been implemented as mandatory so no schema changes needed for us.

**Comment by alanepaull** [comment]
24 June 2019 monthly call: agreed to make ENTITY_NAME optional.

**Comment by alanepaull** [comment]
#323 refers
