### ISSUE TITLE
Add indication of source to EVENT entity

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#315]
The xAPI recipe distinguishes between timetabled and non-timetabled events, which I take to indicate timetabling system or "other" as the source.
It could be useful to be able to unpick the source, and hence nature, of events both for analytical and QA or data quality diagnostics.

I think this should be a general design point: where any entity might not be exclusively populated from one source, the source should be identified

**Comment by gmoger-jisc** [comment]
I like this idea although I'm not sure we would need to specify a source on every entity.

**Comment by arc12** [comment]
I agree, Gareth; so far only EVENT (AFAIK) indicates non-exclusive sourcing.

**Comment by alanepaull** [comment]
#323 refers
