### ISSUE TITLE
event entity updated

### ISSUE THREAD

**Issue by alanepaull** [jiscdev/analytics-udd#323]
The event entity in v1.5_development has been updated in line with:

#313 #314 #315 #316 #317 

https://github.com/jiscdev/analytics-udd/blob/v1.5_development/udd/event.md

To be reviewed and confirmed.

**Comment by Josh-Ring-jisc** [comment]
EVENT_TYPE holds only integer data so should be integer type.

**Comment by arc12** [comment]
@Josh-Ring-jisc IIRC there was a discussion early in UDD development and a principle of typing all categoricals as string was adopted, reserving integers only for things which are countable.

**Comment by alanepaull** [comment]
@arc12 is correct. That's a design feature.

**Comment by alanepaull** [comment]
22 July 2019 monthly call: event entity agreed.
