### ISSUE TITLE
Add difference for 1.5

### ISSUE THREAD

**Issue by gmoger-jisc** [jiscdev/analytics-udd#336]
The differences page for 1.5 does not appear to be complete:
https://github.com/jiscdev/analytics-udd/blob/v1.5_development/differences.md

Can we add a brief summary as per the changes communicated via email?

**Comment by alanepaull** [comment]
I have draft release notes and differences spreadsheet done, with the idea that I would publish these when releasing v1.5. The v1.4.1 to v1.5.0 file is in analytics-udd/media v1.5 now. I attach draft_v1.5.0_ReleaseNotes.xlsx.
[draft_v1.5.0_ReleaseNotes.xlsx](https://github.com/jiscdev/analytics-udd/files/3646430/draft_v1.5.0_ReleaseNotes.xlsx)

**Comment by alanepaull** [comment]
Differences.md updated.
