### ISSUE TITLE
student_course_instance weights, marks and grades

### ISSUE THREAD

**Issue by willblenkhorn** [jiscdev/analytics-udd#338]
Dear all, 

**Background:**

I understand *student_course_instance* to be generally a student's yearly instance of a course, different years have different contributions to the overall mark (GPA) on the course. This overall mark (GPA) is designed to be in *student_course_membership.COURSE_MARK*.

#### Proposed fields for student_on_course_instance:

Field name | Description
-----------|------------
INSTANCE_WEIGHT | A floating point value between 0 and 100 to 1 decimal place, where the sum of INSTANCE_WEIGHT for a given COURSE_ID should sum to 100.
INSTANCE_MARK | A agreed mark between 0 and 100.
INSTANCE_GRADE | An agreed grade the student is awarded.
INSTANCE_RAW_MARK | The original mark scored by the student.

**Comment by gmoger-jisc** [comment]
Can you give more context to this and why it is required beyond simply using the progression outcome:
https://github.com/jiscdev/analytics-udd/blob/master/udd/student_on_course_instance.md#progression

Most institution do not use a GPA style calculation to determine the final degree outcome.

**Comment by arc12** [comment]
I can see an "end of stage" grade/mark might be useful.
In terms of how the final course/programme classification is computed, I believe this is often rather more elaborate than a weighting; sometimes the best N credit modules may be used, or exit velocity used.

**Comment by willblenkhorn** [comment]
I assume that most unis, determine an overall mark/grade for a course instance. In some unis this is most likely at the end of each ACADEMIC_YEAR. Furthermore, each year is usually weighted differently to your degree with most unis putting higher weighting on later years. I understand that this may not apply to all course_instances (such as postgrads) and all unis, but I do think the proposed fields are general enough to be added.

**Comment by Josh-Ring-jisc** [comment]
Gareth: helpful to see the overall progress of a student, also can tell how the students progress counts towards the final outcome.


Adam: Detail around the calculation scheme used could be helpful then, different schemes: 
(please add to this list)

Scheme | Description
------------|----------------
Best N credits | The sum of the best N credits
Credit weighted | The module credits weight the final grade
Exit velocity | For borderline cases where the student is close to a grade band and has performed consistently at or above a grade level, but has not achieved this level overall by a small margin

If using `best N credits` we would benefit from an additional field to record `N`


I think it would be useful to have their stage's:
* Uniform credit weighted mark, for learning analytics purposes
* The university's internal mark, with some detail of the scheme used to determine that. (eg if `best N credits`)
* The university's internal grade, with some detail of the schema used to determine that. (eg if `exit velocity`)

**Comment by Josh-Ring-jisc** [comment]
In addition it would be helpful to know if the current year as a whole counts towards the final degree classification.

**Comment by alanepaull** [comment]
I can see merit in the collection of course_instance marks and grades, along the lines suggested in the OP. I agree it's not limited to unis with GPA. Currently, we only have PROGRESSION, PROGRESSION_SOURCE and X_COURSE_AVERAGE_MARK at roughly this level (above module but below end of course). The requirement might be something like this:

"For analytics purposes, it is useful for the LDH to store, and apps to use, the end-of-stage (course_instance) marks and grades of a student. These could be related to end-of-stage progression, overall course grades and final outcomes within the context of the student's circumstances on entry to the course, changes during the course and the student's activities during the course_instance."

It's less clear to me that storing the details of the calculation of final outcomes within the UDD is necessary. This level of detail may be more appropriate within an app that uses the marks and grades. It looks likely to be very particular to the provider, without the level of standardisation that we might usually experience in the UDD. More of an implementation than a spec issue?

**Comment by Josh-Ring-jisc** [comment]
From the call:

Yearly weighting
mark
grade
raw_mark
raw_grade

**Comment by alanepaull** [comment]
Monday 14 Oct 2019: Agreed to consider new fields (as from @Josh-Ring-jisc above). Jisc to investigate with institutions what they hold and what would be appropriate to capture for LA to flesh out the requirement.

**Comment by ds10** [comment]
From call:

Done during load process, spec to stay the same
