### ISSUE TITLE
Opinions wanted: Removing some sensitive attributes from student table

### ISSUE THREAD

**Issue by Josh-Ring-jisc** [jiscdev/analytics-udd#339]
Wanted to get some **opinions** on removing the following potentially sensitive fields from the student table:

ref: https://github.com/jiscdev/analytics-udd/blob/v1.5_development/udd/student.md

| Field |
---------|
ADDRESS_LINE_1 |
ADDRESS_LINE_2 |
ADDRESS_LINE_3 |
HOME_PHONE |
MOBILE_PHONE |

Was wondering if people had use-cases for having these fields in the UDD.

Best regards
Josh

**Comment by arc12** [comment]
Tribal makes no use of these. In fact our UDD ingestion process is configured to ignore these even if data is provided.

I can see a scenario where a software system does both LA and allows for "contact the student".

My inclination would be to leave them in and simply not collect, advising customers that they dont apply to the project in effect.

**Comment by robwynj** [comment]
Totally agree. No need to worry about these at the moment.

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL, CSM & CSPO Scrum, ISEB Certified
APMG PRINCE2 & AgilePM Certified Practitioner
Director of Data Analytics, Jisc
email: rob.jones@jisc.ac.uk skype: robwynj twitter: @robwynjonesmobile: 07468 727040
web: www.jisc.ac.ukNot<http://www.jisc.ac.ukNot> on iOS? Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by petekeating** [comment]
We've never sent this information across from our student system, and don't intend to. (Mainly as we had no need for it in Data Explorer anyway).

**Comment by Josh-Ring-jisc** [comment]
This seems like something which is not actively being used.

An individual provider can have this in their own DB, but I don't think, based on these responses, there is a need for this to be inside of the UDD standard.

**Comment by robwynj** [comment]
I would like it left there, for now, and anyone can ignore. Not high priority and the UDD can also be used for an individual HEIs need too (not just our purposes). We use for display purposes optional in Data X later on.

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL, CSM & CSPO Scrum, ISEB Certified
APMG PRINCE2 & AgilePM Certified Practitioner
Director of Data Analytics, Jisc
email: rob.jones@jisc.ac.uk skype: robwynj twitter: @robwynjonesmobile: 07468 727040
web: www.jisc.ac.ukNot<http://www.jisc.ac.ukNot> on iOS? Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by alanepaull** [comment]
Additional question: @Josh-Ring-jisc mentioned ADDRESS_LINE_1, ADDRESS_LINE_2, ADDRESS_LINE_3, HOME_PHONE, MOBILE_PHONE. Was there a reason to omit ADDRESS_LINE_4 from the list? Proposal is to deprecate these fields in v1.5.1, and delete in v1.6 - bearing in mind that this gives us plenty of time to address any follow-on issues.

**Comment by arc12** [comment]
My view remains unchanged: while we have no current use for these, I CAN see scenarios where UDD could be used which would need them. Given that they are already there, "leave alone" seems appropriate (I would not encourage speculative addition!). Path of least action!

I think the answer here (such as there can be one) is to see this as an "application profile" issue. As such, it would be reasonable for the Jisc LDH to default to dropping these.

**Comment by Josh-Ring-jisc** [comment]
>When is processing 'necessary'?
Many of the lawful bases for processing depend on the processing being “necessary”. This does not mean that processing has to be absolutely essential. However, it must be more than just useful, and more than just standard practice. **It must be a targeted and proportionate way of achieving a specific purpose. The lawful basis will not apply if you can reasonably achieve the purpose by some other less intrusive means, or by processing less data**.
It is not enough to argue that processing is necessary because you have chosen to operate your business in a particular way. The question is whether the processing is objectively necessary for the stated purpose, not whether it is a necessary part of your chosen methods.


https://ico.org.uk/for-organisations/guide-to-data-protection/guide-to-the-general-data-protection-regulation-gdpr/lawful-basis-for-processing/

**Comment by gmoger-jisc** [comment]
@Josh-Ring-jisc let's discuss internally how to handle with the data hub as it is easy for us to drop them from our implementation of UDD if there are future cases where this might be used.

**Comment by alanepaull** [comment]
Owing to on-going discussion, I will not yet deprecate these fields in v1.5.1_development.

**Comment by Josh-Ring-jisc** [comment]
No real use case has emerged.

**Comment by gmoger-jisc** [comment]
We'll leave them in for now and park this issue until next year when we confirm changes for 1.6.  There is no immediate need to remove them as that can be handled in our implementation.

2-3 weeks is not much time to consult across the broad range of services emerging internally, along with the requirements of our new Data Analytics directorate.  As such let's revisit in the new year.

**Comment by robwynj** [comment]
Agreed.

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL, CSM & CSPO Scrum, ISEB Certified
APMG PRINCE2 & AgilePM Certified Practitioner
Director of Data Analytics, Jisc
email: rob.jones@jisc.ac.uk skype: robwynj twitter: @robwynjonesmobile: 07468 727040
web: www.jisc.ac.ukNot<http://www.jisc.ac.ukNot> on iOS? Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by gmoger-jisc** [comment]
To remain in spec as part of the standard but can be removed from individual implementations if not required.
