### ISSUE TITLE
New Entity - MODULE_VLE_MAP

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/analytics-udd#34]
A simple table to map module instances to modules in the VLE, which may have different codes.

with two elements:

MOD_INSTANCE_ID,
VLE_MOD_ID

if the mapping is actually one VLE module to one MOD rather than MOD_INSTANCE we'd just have each instance in this table. 

We need this for the student app.

It's likely to come from a new source (ie not in the VLE or SRS) and may be optional if there is a 1-1 mapping of module to vle_mod_id.

**Comment by gryglbrt** [comment]
+1 for this. We need it for the staff dashboard as well.
