### ISSUE TITLE
code lists in UDD 1.5 are drastically out of date

### ISSUE THREAD

**Issue by Josh-Ring-jisc** [jiscdev/analytics-udd#340]
![image](https://user-images.githubusercontent.com/29859996/65643863-ae3bb280-dfea-11e9-83d9-bd1c033e0ed0.png)

code lists were last updated 3 years ago, these should be updated.

**Comment by alanepaull** [comment]
We will have a look at this. The tool was produced originally as a potentially useful tool for users to develop to generate the codes for their own use, not as a part of the UDD specification.

I'll see if we can get these updated.

**Comment by alanepaull** [comment]
Now updated to v1.5.0 by @ds10.
