### ISSUE TITLE
courseInstance and moduleInstance unique constraints, propose a 'yearly' table to compliment

### ISSUE THREAD

**Issue by Josh-Ring-jisc** [jiscdev/analytics-udd#345]
### The original definitions of courseInstance and moduleInstance have no unique constraint on `COURSE_ID, ACADEMIC_YEAR` and `MOD_ID, ACADEMIC_YEAR`

So we have a situation where there could be hundreds of `courseInstance` or `moduleInstance` rows for a given combination above.

It would be helpful for analytics to have a table separately, with the same schema as the `courseInstance` and `moduleInstance` tables, **but with this explicit unique constraint**, named something like`courseInstanceYearly` and `moduleInstanceYearly`. Where we have selected one `COURSE_INSTANCE_ID` and `MOD_INSTANCE_ID` out of the possible values which would satisfy the unique constraint given above.

As it is now, we have hundreds of `COURSE_INSTANCE_ID` values from the same `COURSE_ID` and `ACADEMIC_YEAR` from the same university. 

This complicates working with the data as we don't have a workable yearly view for a course or module.

![image](https://user-images.githubusercontent.com/29859996/65869100-98731800-e371-11e9-92eb-44db7ca43177.png)

**Comment by gmoger-jisc** [comment]
This is built on the assumption that there would be 1 course instance per academic year which is not the way all institutions work.  There could be either of these scenarios:

1. Institution bases their course instances on term times and has multiple in year instances (we have 1 institution like this)
2. Institution splits course instances based on mode of study, so 1 course has 2 instances for part/full-time etc.

I need to think about this more but from an analytics perspective this is something we might just have to handle, in which case it may not be the best approach to build into the specification.

**Comment by arc12** [comment]
Yes, Regents has two progression points in the year, so in principle there could be two CI's in one academic year.

300+ looks like someone has misunderstood the semantics of course instance, so this may be in the territory of data quality checks rather than imposing constraints.

**Comment by Josh-Ring-jisc** [comment]
You both seemed to miss this part:

> It would be helpful for analytics to have a table separately, with the same schema as the courseInstance and moduleInstance tables, but with this explicit unique constraint, named something like courseInstanceYearly and moduleInstanceYearly. Where we have selected one COURSE_INSTANCE_ID and MOD_INSTANCE_ID out of the possible values which would satisfy the unique constraint given above.

**Comment by gmoger-jisc** [comment]
I didn't miss it.  I don't think we should be building in additional entities to handle what is both a data quality and analytics issue.  We just have to handle it better at the logic layer to accommodate those institutions like regents with 2 progression points, and work with everyone to be capturing the data correctly.

**Comment by arc12** [comment]
+1

**Comment by Josh-Ring-jisc** [comment]
In terms of validation, there is a variable number of terms for every site/university, so Regents has two, others could well have more. I can't see an obvious way to validate this?



>This is built on the assumption that there would be 1 course instance per academic year which is not the way all institutions work. There could be either of these scenarios:

> Institution bases their course instances on term times and has multiple in year instances (we have 1 institution like this)
>Institution splits course instances based on mode of study, so 1 course has 2 instances for part/full-time etc.
>I need to think about this more but from an analytics perspective this is something we might just have to handle, in which case it may not be the best approach to build into the specification.

This all sounds like far too much individual site-level difference to be able to sensibly accommodate for data products, let alone validate. 

If it's all the same course content, delivered in the same year, why divide it, what's the gain in doing that?

**Comment by Josh-Ring-jisc** [comment]
![image](https://user-images.githubusercontent.com/29859996/65881923-0fb5a580-e38c-11e9-9751-581e78ae906a.png)

This goes beyond just regents, almost every uni has a problem

**Comment by Josh-Ring-jisc** [comment]
I think it's clear there needs to be some sort of constraint on this behaviour, >3 `COURSE_INSTANCE_ID` or `MOD_INSTANCE_ID` values per year for the same `COURSE_ID` or `MOD_ID` does not seem plausible.

**Comment by alanepaull** [comment]
Monday 14 October 2019: We agreed that that a note should be added to course_instance documentation to point out to users that if their output has more than 4 course_instance records (for example) related to a single course in one academic year, this might be an indication of an issue with their output process.

**Comment by alanepaull** [comment]
New Note added to course_instance in v1.5.1_development: https://github.com/jiscdev/analytics-udd/blob/v1.5.1_development/udd/course_instance.md.

Please read the note and let me have any comments in this thread.

**Comment by Josh-Ring-jisc** [comment]
Thanks @alanepaull  Yes it looks good to me.

**Comment by ds10** [comment]
From call:
- Data quality issue.
