### ISSUE TITLE
MOD_START_DATE and MOD_END_DATE

### ISSUE THREAD

**Issue by willblenkhornjisc** [jiscdev/analytics-udd#347]
Dear all,

I was wondering if `MOD_START_DATE` and `MOD_END_DATE` should move from `student_on_a_module_instance` to `module_instance`. To be consistent with the `START_DATE` and `END_DATE` in `course_instance`. For most institutions module_instances will be taught over a specific time period and not student specific.

**Comment by gmoger-jisc** [comment]
Yes, I was never quite sure of the reasoning here.  Also wondering on the view to make these mandatory?

**Comment by arc12** [comment]
-1 for change - they work where they are = I dont see a substantive issue here, therefore nothing to justify the redevelopment cost.

We actually require these, so not optional for us; there are too many cases where optionality would be a PITA.

**Comment by gmoger-jisc** [comment]
Yes, we require them also which is why I think they should be mandatory.

Not precious about where they are however.

**Comment by willblenkhornjisc** [comment]
I think that the redevelopment cost is worth it in the long run. As it's much easier for institutions to keep on top of their data if they have to manage the module instance dates on one row, rather than ~30+ rows. One source of truth is always better than multiple and possibly conflicting truths.

**Comment by craig-petch** [comment]
For info, I think back in the dim and distant past there was a user case for this being on SOMI and that's when a student is required to resit a module (or part of a module) and the end date is extended beyond the Module period date range. So for tracking active students this date was needed at SOMI level. Bit of edge case but one that was important at the time.

**Comment by ds10** [comment]
From call:

- Group doesn't see it worth cost
- maybe resolution is to change description "start of this module instance" is not true?
- any further feedback @willblenkhornjisc  ?

**Comment by willblenkhornjisc** [comment]
I think it would be nice to have it moved over. Though it's more of a nice to have and the spec is ok as it is.
