### ISSUE TITLE
renaming of columns for module and course subject tables.

### ISSUE THREAD

**Issue by willblenkhornjisc** [jiscdev/analytics-udd#348]
Dear all, 

I think that the following columns in `course_subject` and `module_subject` should be renamed with a prefix to differentiate that the two are different.

1. SUBJECT_ID
2. SUBJECT_LABEL
3. ENCODING_ID
4. PROPORTION
5. SEQUENCE_ID

The prefix for `course_subject` could be 'COURSE_' and similarly for `module_subject` could be 'MOD_'.

**Comment by arc12** [comment]
I would strongly like to see naming following semantics. This is generally how UDD is defined. In the case of the two subject-linking tables, the semantics are the same for all except COURSE_ID/MOD_ID. So I see the naming as being "correct" as it stands.

**Comment by Josh-Ring-jisc** [comment]
> This is generally how UDD is defined.

Try:
MOD_START_DATE and START_DATE
ASSESS_SEQ_ID and SEQUENCE_ID
COURSE_JOIN_DATE and MOD_START_DATE (which is actually MOD_JOIN_DATE on student module instance)

**Comment by arc12** [comment]
I assert that the semantics of those example pairs differ. For example, the meaning of the sequence in which assessments are taken is different to the order-of-importance for the subject classification.

For the case in point, the 5 attributes are descriptive of the act of classification according to subject of study, Arguably, the names could be different to reflect this e.g. STUDY_PROPORTION, SUBJ_ENCODING_SCHEME, etc
It would not have been unreasonable to model subject of study using a single entity, with "object type + object id" to refer to course or module instances.

Granted there are cases where we seem to have naming with "MOD_" added where it could be argued it shouldnt, but in general, attributes are plainly named by what they are: we have TERMTIME_ACCOM by itself, and foreign keys are simply named without the parent.

**Comment by alanepaull** [comment]
I confess that we have not been as consistent in this issue than we perhaps should have been. There are anomalies. However, a main reason for anomalies (and things that look like anomalies) was the necessity in earlier days to retain existing naming, rather than implementing changes with knock-on impact.

I suspect there will be little appetite for wholesale renaming of our current properties, unless there is an overriding major problem.

**Comment by willblenkhornjisc** [comment]
That's fair enough. I suppose changing the name of the columns on our backend will suffice as a means to differentiate the two.
