### ISSUE TITLE
avoidance of use of multiple subject classification schemes

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#349]
the current course and module subject entities have constraints/usage-notes which do not prohibit the classification of a course against multiple classification schemes.

While it is reasonable to allow for different courses to be classified by different schemes, I think it is NOT OK to do this for a single course, and I cant see a simple/reliable rule to allow for that to be unpicked, given the variety of proportion/sequence-id which might pertain. Similarly, I cant see an easy way to define a uniqueness constraint. Hence, I propose that the notes/description should have some words of guidance.

**Comment by Josh-Ring-jisc** [comment]
A simple choice is to add an **additional** unique constraint, with only

SUBJECT_ID and COURSE_ID

This way the same course cannot be assigned to multiple subjects

**Comment by arc12** [comment]
It is valid to have more than one subject of study, and for these to map to the same item in the CAH. Furthermore, CAH-mappable subject classification schemes are only a subset of UDD use scenarios.

I'm also of the view that it is an anti-pattern to add constraints to an interoperability spec which are not logically true. For the case in point, I dont think the case against mutliple scheme use is more than "it makes down-stream use messy if you do"

**Comment by Josh-Ring-jisc** [comment]
Perhaps instead, splitting the two schemas into two columns.

This would allow us to specify in a check constraint that if one schema is provided that the other must be null.

**Comment by alanepaull** [comment]
>the notes/description should have some words of guidance.

A bit like this?

"If a course is associated with multiple subject codes, the same subject coding scheme must be used for all codes. Typically this will be either JACS3 or, in the future, HECoS."
(from the Notes against SUBJECT_ID).

Maybe that note needs to be in the entity description too, lest it be missed?

**Comment by alanepaull** [comment]
> the current course and module subject entities have constraints/usage-notes which do not prohibit the classification of a course against multiple classification schemes.

The Notes section on SUBJECT_ID precludes this.

**Comment by arc12** [comment]
sorry, Alan - I think you are right; somewhere between tripping over some issues in my deliberately wild test data (intended to explore the range of what people might do) and consulting the "as is" of the current wording, I got it into my head that the notes were talking about classifying multiple subjects of study, whereas the wording refers to multiple codes.
I think things are, therefore, fine as they are.
