### ISSUE TITLE
New dot release v1.5.1 to be published today 29 October

### ISSUE THREAD

**Issue by alanepaull** [jiscdev/analytics-udd#351]
This new dot release contains the following changes:

- student_course_membership: CARELEAVER deleted (moved to student entity)
- student: CARELEAVER added (moved from student_course_membership)
- course_instance: Note re number of records added

**Comment by alanepaull** [comment]
v1.5.1 now released as new Master branch.

Current branches are now:
- master (v1.5.1)
- v1.4.2 (old branch now deprecated; for deletion)
- v1.5.2_development (for non-breaking changes)
- v1.6_development (for breaking changes)

Any comments, please let me know on this thread.

**Comment by ds10** [comment]
From this
