### ISSUE TITLE
LOCATION in event entity

### ISSUE THREAD

**Issue by gmoger-jisc** [jiscdev/analytics-udd#355]
We capture EVENT_LOCATION with the attendance statement but this has not been defined in the UDD event entity.  

Can we look to add for 1.5.1?

**Comment by gmoger-jisc** [comment]
Any thoughts on this one?

**Comment by willblenkhornjisc** [comment]
It's in the current master, [https://github.com/jiscdev/analytics-udd/blob/master/udd/event.md#event_location](url), or did you mean something else?

**Comment by gmoger-jisc** [comment]
Thanks Will - not sure where I got confused on this one (query came from an institution) but the field certainly is in the spec, the UDD database and has data present!
