### ISSUE TITLE
Student_id_map codify the possible DOMAIN relationships

### ISSUE THREAD

**Issue by Josh-Ring-jisc** [jiscdev/analytics-udd#356]
I hear there are plans to move attributes currently on the `student` table towards `student_id_map`. I am interested to codify these possible DOMAIN values to reduce the ambiguity of the implementation.

https://github.com/jiscdev/analytics-udd/blob/master/udd/student_id_map.md#domain

A sensible starting list:

- VLE_ID
- APPSHIB_ID
- HUSID
- ULN

I have in the Jisc database seen the following distinct values for DOMAIN, prompting this call for more standardisation:

- ULN
- OCLC
- HUSID
- VLE_1
- BLACKBOARD
- VLE
- CCAD

So there's clearly some unis with multiple VLEs going on, which makes sense, perhaps we need an additional descriptive field? so we can differentiate while still maintaining a smaller list of domains.

So proposing an additional field to `student_id_map` and `module_map` which names the provider `PROVIDER_NAME`. So we can differentiate between data sources and providers within the same data source.

**Edit**
The same need for standardisation also applies to `module_map`.`MODULE_MAP_DOMAIN`

**Comment by alanepaull** [comment]
4 Feb 20 call: this issue to be merged with #354
