### ISSUE TITLE
standardisation of id_maps

### ISSUE THREAD

**Issue by willblenkhornjisc** [jiscdev/analytics-udd#365]
Dear all, 

After the recent introduction of module_map and staff_link, it would be nice to make student_id_map conform to a similar setup. Moving all the student related ID's to that e.g. 

1. VLE_ID
2. HUSID
3. APPSHIB_ID
4. ULN

I feel that this will focus the institutions attentions on getting vital ID related columns correct for referential integrity purposes. Helping with analytics and customer satisfaction. 

Regards,

Will

**Comment by gmoger-jisc** [comment]
Discussion has been dealt with in 2 recent issues:
- #356 
- #354 

Can discuss options on monthly call.  Potentially deprecate fields from 1.6 for removed in 1.7.  Would have to establish clear value here as it feels like an unnecessary change from a user perspective.

**Comment by willblenkhornjisc** [comment]
Fair enough, I agree the change may seem unnecessary from a user perspective but I feel its a good move to standardise the id_maps for data collection moving forward.

**Comment by gmoger-jisc** [comment]
Updated entity with fields in line with module map, however we are not enforcing valid values against the DOMAIN yet.  Equally we are not proposing to move identifier fields from the student entity into student id map, rather we can consider student id map an extension for further mappings where needed.

If further use cases emerge they can be added as a new issue.

Added for 1.6.1 release:
https://github.com/jiscdev/analytics-udd/commit/d6b606e44350b4e5fa1b7de1e912d40de524926d
