### ISSUE TITLE
minor issue which affects automatic schema generation

### ISSUE THREAD

**Issue by Josh-Ring-jisc** [jiscdev/analytics-udd#366]
TUTOR_STAFF_ID was not included in the markdown table at the top of the student table page:
https://github.com/jiscdev/analytics-udd/blob/v1.6_development/udd/student.md#student

**Comment by gmoger-jisc** [comment]
Corrected on 1.6 dev branch:
https://github.com/jiscdev/analytics-udd/commit/c0eb1ad7fafe50e161669340ceb28066ca0d179e
