### ISSUE TITLE
SAI assess_retake - discuss definition scope 

### ISSUE THREAD

**Issue by rossadolph-jisc** [jiscdev/analytics-udd#367]
Confirm current definition ASSESS_RETAKE column in student assessment instance or whether to broaden the scope to include all retake reasons not just those resulting of a mitigating circumstances.

**Comment by gmoger-jisc** [comment]
Need to update ASSESS_RETAKE as a counter-part to:
https://github.com/jiscdev/analytics-udd/blob/master/udd/student_on_assessment_instance.md#assessment_current_attempt

**Comment by gmoger-jisc** [comment]
Clarified between the 2 fields in udd 1.6.1:
https://github.com/jiscdev/analytics-udd/commit/43d4034f2025685cc7f10415abdbdabde03d49e6
