### ISSUE TITLE
VLE_ID as *optional* field for a Student on Course Instance?

### ISSUE THREAD

**Issue by robwynj** [jiscdev/analytics-udd#39]
This would be useful for certain institutions (I have one example = Strathclyde) where the VLE_ID changes every academic year for them - hence for linkage to VLE data, this would be useful per course per student to handle this - although this is probably a rarity, I know Strathclyde would use this.

Rob

**Comment by michaelwebbjisc** [comment]
I don't think that's needed, as in the new xAPI recipes the VLE ID is no longer the internal identifer.  In the first instance I've made it the username, but in a later release it will be selectable.

**Comment by robwynj** [comment]
So in terms of linkage to the UDD (and for strathclyde, per course student on course instance), the username will be their email address? Or do we use the VLE_ID in their instance, as an exception (selectable as you mention)
