### ISSUE TITLE
MOD_INSTANCE.MOD_LEVEL move to MODULE - APPROVED (UDD 1.2)

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#4]
Currently we have credit value on module but level on instance. Credit and level are partners so should probably be in the same place. I can't imagine these being instance-specific, as they would be part of formal QA processes for module specification.

Suggest: move MOD_LEVEL

[I think MOD_OPTIONAL may also be better moved]

**Comment by robwynj** [comment]
Hi Adam,

I agree - this needs to be moved for UDD 1.2 - and this also aligns with HESA on MODULE not instance (not sure why segragated initially in 1.0/ 1.1). Michael - let me know you are happy with this.

https://www.hesa.ac.uk/index.php?option=com_studrec&task=show_file&mnl=15051&href=a^_^LEVLPTS.html

Kind Regards

Rob

**Comment by wilmTap** [comment]
Intuitively, that makes a lot of sense to me, but I'm still wrapping my head around the datamodel. I'll have a quick look at the new straw people HEDIIP datamodels to get a sense of where HESA et al are headed, but I suspect they only have student, not module.
Happy to make the change tomorrowish unless someone objects.

**Comment by robwynj** [comment]
Hi Wilbert,

Good to meet you (well sort of anyway!). The current model will be in operation for a while I suspect, but this was based on 14-15 HESA SR (and hasn't changed much for 15-16 from what I gather).

Kind Regards,

Rob

**Comment by robwynj** [comment]
Approved

**Comment by wilmTap** [comment]
In pull request #15
