### ISSUE TITLE
Add pre-entry postcode

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#40]
This isn't something we need right now, but is potentially very useful to match to IMD etc

The postcode before entry, as:
https://www.hesa.ac.uk/component/studrec/show_file/12051/a%5E_%5EPOSTCODE.html

**Comment by robwynj** [comment]
Agreed - and should go into student_additional as ENTRY_POSTCODE (or similar)

https://www.hesa.ac.uk/index.php?option=com_studrec&task=show_file&mnl=15051&href=a^_^POSTCODE.html
