### ISSUE TITLE
Re-instate MAX_POINTS? UDD 1.2 Assessment Instance

### ISSUE THREAD

**Issue by robwynj** [jiscdev/analytics-udd#44]
Dear All,

After conversation with Sandeep last week - up for discussion, but he suggests this needs to be retained for UDD 1.2.

Has been dropped during transition from GRADE (UDD 1.1) to Assessment/ SoAI.

o	Max_Points (or equivalent) - Denoting the maximum points allocated to the assessment by the instructor should be added to UDD v1.2

Kind Regards

Rob

**Comment by wilmTap** [comment]
Meant to indicate the scale as well
