### ISSUE TITLE
COURSE_AVERAGE_GRADE/ YEAR_AVERAGE_GRADE

### ISSUE THREAD

**Issue by robwynj** [jiscdev/analytics-udd#45]
Dear All,

Can we confirm/ consider with relevance to these fields:

a) re-instating COURSE_AVERAGE_GRADE on SoCI (required by UNICON);
b) the context of this information - I assume this is the student's running grade average during the course or also the current year - should we ideally be calculating this for them by default, so long as all the information is at hand within the data given (granular marks/ grade data submitted for all assessments which count).

Kind Regards

Rob

**Comment by wilmTap** [comment]
I've assumed that both COURSE_AVERAGE_GRADE and YEAR_AVERAGE_GRADE refer to module averages and not projected degree classifications.

**Comment by wilmTap** [comment]
Turn into X_COURSE_AVERAGE_MARK. For analysis only, not display. Float data type.
