### ISSUE TITLE
Missing foreign key on course

### ISSUE THREAD

**Issue by wilmTap** [jiscdev/analytics-udd#46]
My understanding is that the institution entity is meant to link to the course entity, preferably by having a TENANT_ID on each course. That's not defined in the UDD at the moment, however.

Proposed fix: add TENANT_ID to course in version 1.3

**Comment by ds10** [comment]
Monday call: This is an indirect relationship, so not desperately needed or a show stopper. Call agreed this  would be useful and to be put in 1.3

**Comment by wilmTap** [comment]
Added as optional in v1.2.4
