### ISSUE TITLE
CourseMembership FK to Course rather than CourseInstance

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#47]
We think StudenCourseMembership should not have COURSE_INSTANCE_ID but should have COURSE_ID. This was an error in the text of the proposal we made for UDD 1.2 (but not the ER diagram).

Adam

**Comment by wilmTap** [comment]
Happy to make the change. Since it's a bit of non-backwards compatible change, do we want to put it into v1.3, or do we reckon that it's early enough to smuggle into a v1.2.1?

**Comment by wilmTap** [comment]
To be done 1.2.1 now
