### ISSUE TITLE
STUDENT_ON_MODULE_INSTANCE.MOD_PASS - APPROVED (document for UDD 1.2)

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#5]
Documentation should make clear how this should be used. e.g. to specify that codes pass=yes/no are only applied for cases when there has been an actual pass/fail decision. It should be unambigious to know how the field is used for cases where there has been a withdrawal or deferral (these should not be lumped in with failures, for example, simply because they are not "passes").

Also clarify the relationship with MOD_OUTCOME

Code 3, "not completed yet" may be redundant or conflating a separate concept (whether the student is active on the course or withdrawn etc)

**Comment by robwynj** [comment]
MOD_OUTCOME information is based on HESA classification here, and an entry specified as NULL would normally be transformed to code 6. This field is separate in meaning to MOD_PASS (pass/ fail).

FYI below:

https://www.hesa.ac.uk/index.php?option=com_studrec&task=show_file&mnl=15051&href=a^_^MODOUT.html

**Comment by arc12** [comment]
@Rob - sure, but its the use of pass/fail I was getting at.

BTW - we've also got some doubts that the HESA outcomes will be available when we need them, as these will (at least until Data Futures rolls out) tend to lag behind course delivery.

**Comment by robwynj** [comment]
Agreed - will updated documentation to confirm the clear purposes of it :)

**Comment by wilmTap** [comment]
I've clarified it in pull request #15 

I've left the values alone, but I wonder whether code 3 should simply be "unknown" rather than "Not completed yet"- that way it would cover all reasons why you might not known the outcome, and you can point people to MOD_OUTCOME if they need to know why.
