### ISSUE TITLE
Student Course Membership - Joining Date?

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#50]
We currently have withdrawal and end dates (two of) but no joining date.

Consider - would this be useful? It can generally be inferred via student on module instance as the earliest date on which a module associated with the course membership starts, but not cleanly in the case of in year transfers.

One for the backlog...?

**Comment by robwynj** [comment]
This would be equivalent of COMDATE - add this in now as optional?

https://www.hesa.ac.uk/index.php?option=com_studrec&task=show_file&mnl=15051&href=a^_^COMDATE.html

**Comment by arc12** [comment]
we're also looking at using age on joining as a field at student-course-membership level, as this is generally what we'd use for buiding predictive models.

**Comment by wilmTap** [comment]
isn't age on joining just student_course_membership.COURSE_JOIN_DATE minus student.DOB?

**Comment by robwynj** [comment]
So this should be an X_ field then calculated internally?

Cheers

Rob

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; PRINCE2, AGILE & SCRUM Certified Practitioner

Consultant – JISC Special Projects

email/ skype: robert.jones@jisc.ac.uk<mailto:robert.jones@jisc.ac.uk> mobile: 07976 508860

**Comment by arc12** [comment]
Yes, in principle, now we have a joining date, things are "OK".

However: a logical or mathematical relationship between these concepts doesn't mean the data supports it. In practice, I've found rather a lot of wildly inaccurate date records, so I would probably trust a recorded age on entry more.

Adam

**Comment by wilmTap** [comment]
Add age on joining in 1.3

**Comment by wilmTap** [comment]
Now made optional for v.1.2.4
