### ISSUE TITLE
Student Course Membership - Withdrawal Date redundant?

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#51]
Since we have expected and actual end dates, is withdrawal date redundant?

Would a clean model use just the actual end date for withdrawals and set the withdrawal reason appropriately. (we should amend the description of COURSE_END_DATE to be more clear; the current language is "completed" which has different overtones than ended, and in my view this should be a neutral end date with the nature of the COURSE_OUTCOME showing what kind of ending it is, and WITHDRAWAL_REASON or COURSE_GRADE etc providing a level of detail contingent on the outcome.)

**Comment by wilmTap** [comment]
Agreed; it's interesting to note that the UDD WITHDRAWAL_DATE is modelled on the HESA ENDDATE, which states "This field records the date the student left the student instance detailed in this return."

**Comment by robwynj** [comment]
I agree this makes perfect sense - remove WITHDRAWAL_DATE

**Comment by arc12** [comment]
deprecated in 1.2.7
issue redundant now
