### ISSUE TITLE
Clean up COURSE_INSTANCE_ID references

### ISSUE THREAD

**Issue by wilmTap** [jiscdev/analytics-udd#55]
The property used to be everywhere, but has now largely been deprecated in favour of STUDENT_COURSE_MEMBERSHIP_ID. However, remnants persist in the diagrams, and in the listing of Student on a Module Instance. These need to removed.

**Comment by arc12** [comment]
I believe this is not redundant. For example that module instances will often be associated with an annual registration aka a course instance.

Definitely: check with Craig Petch and folk familiar with SRS structures

**Comment by craig-petch** [comment]
As Adam indicates we still need to be able to join the student on module instance to the the course instance. The course membership record handles the over arching course information for the student whilst the course instance details provides annual registration information we will still need to be able to join the course and module instances together.  In time we may need to add capture more information at the course instance level (for example identifying Erasmus and Off books students). So this should be left in the module instance record.

**Comment by wilmTap** [comment]
OK, will leave the one in student on module instance and staff on course instance. Other than on course instance itself, it doesn't occur anywhere else.
