### ISSUE TITLE
Student on Course Instance - COURSE_INSTANCE_ID FK missing?

### ISSUE THREAD

**Issue by robwynj** [jiscdev/analytics-udd#56]
Dear All,

Just wanted to double-check this, but shouldn't we have COURSE_INSTANCE_ID as a FK within SoCI?

Kind Regards

Rob

**Comment by craig-petch** [comment]
Hi Rob,

Yes there should be, looks like it was in our original proposal but has got lost during all the changes. I hadn't noticed it missing on here.

**Comment by robwynj** [comment]
Thanks Craig - thought that was the case!

Apart from that, the linkages look solid now.

@Wilbert - can you implement this changes ASAP into UDD 1.2.x please. Have advised Aber & Strathclyde accordingly.

Many Thanks,

Rob
