### ISSUE TITLE
Suggest - .md document granularity

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#6]
I find the very granular structure in moodle to be a little but too granular. In practice, I think people will organise data export according to the implicit tables e.g. "module instance". Suggest we adopt that level, or even group module, module-instance, and student-on-module-instance, as the unit. I think that will make use and revision easier. Just my opionion....

**Comment by wilmTap** [comment]
Seeing the debate on basecamp (https://basecamp.com/2737506/projects/10136653/messages/52988483), folk seem to lean to smaller, so I'll chop the UDD up into the sections you mention.
