### ISSUE TITLE
Make releases out of final version drafts

### ISSUE THREAD

**Issue by ht2** [jiscdev/analytics-udd#62]
It would be good that once a version is finalised and as a process of merging it into master, that a release is made that allows us to grab the HEAD of the repo at the time that version is finalised. As part of our API work, we're having to make some checks on our v1.2.1 version and finding it tricky to track down what is and isn't at that version!

**Comment by wilmTap** [comment]
Apologies, we've relied on the dev branches and slacked on making releases. We'll make a release of the master branch after the merge of the development branches of both the UDD and Jisc xAPI profile.
