### ISSUE TITLE
COURSE_AIM_ATTAINED doesn't contain a valid value if not yet attained.

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/analytics-udd#64]
I think we need to include a valid valid to denote that no course aim has yet been attained, or make the field non-compulsory.

**Comment by robwynj** [comment]
Agreed. Needs confirmation - had validation issues via our API obviously, and specified (to Tribal) that default (temporary code) provided as "X99" for now to get around this....

Rob

**Comment by wilmTap** [comment]
At the moment, the documentation includes both X99 and X89 in addition to the HESA COURSE_AIM value space, with the following note:

> 
This field uses the HESA "COURSEAIM" codeset initially - with the addition of new code 'X98' to denote 'No formal qualification aim, below FE level' for FE equivalent denotation to HE code 'X99'. All course levels are denoted here (TBC with FE college, for final implementation). Specific use of the LARS codeset for FE (from ILR) may need to be considered, or a mapping/ amalgamation with the HESA codeset. This is to be discussed in consultation with the FE sector.

Will that do, or shall we introduce a 'not applicable'?

**Comment by robwynj** [comment]
Hi Wilbert,

Yes, let's add a 'X97' code which denotes "Not Applicable".

Kind Regards

Rob

**Comment by arc12** [comment]
I would much rather have NULLs for data which is not yet knowable - here an aim which is not yet attained. There is no answer to the question "what course aim was attained?"

And have a code for cases where there was attainment but the specifics are not known. IMO this should be used only when the SRS actually records "not known".

Adam

**Comment by robwynj** [comment]
Well other fields are "optional" on this basis, and should therefore be such and NULL gets through fine.... I will leave it to a democratic vote for our meeting later!

**Comment by wilmTap** [comment]
I've made the property optional.
