### ISSUE TITLE
TUTOR_STAFF_ID (STUDENT_ADDITIONAL) - compulsory?

### ISSUE THREAD

**Issue by robwynj** [jiscdev/analytics-udd#65]
Dear All,

I believe that TUTOR_STAFF_ID (STUDENT_ADDITIONAL entity) should be optional (not mandatory) - not always the case that they will link a course tutor to a student (on SRS) or may want them to have exposure/ do LA interventions for example. Plus, referential integrity here vs STAFF entity if value is not valid ie. blank or dummy data, in future.

Any thoughts?

Kind Regards

Rob

**Comment by craig-petch** [comment]
Hi Rob, I'd agree with setting that optional, not every site will have or want to supply that information or operate in that way.  The staff related entities allow us to map multiple staff who have a relationship with a course or module (and to help identify access in student insight for example), but I would assume that attribute is more helpful to capture an individual's current tutor but agree it needs to be flexible when that's not available (or if they do not want to supply it)

Craig
