### ISSUE TITLE
Student Course Membership/ SoMI/ SoAI - "marks" fields valid values in 1-100 range - should be 0-100?

### ISSUE THREAD

**Issue by robwynj** [jiscdev/analytics-udd#67]
Dear All,

Been going through the UDD API validation of student UDD data, and wanted to confirm that the valid values for any of the marks fields for the entities should actually be 0-100 (which makes sense - as somebody can get zero).

See:

https://github.com/jiscdev/analytics-udd/blob/master/udd/student_course_membership.md#course_mark

https://github.com/jiscdev/analytics-udd/blob/master/udd/student_on_a_module_instance.md#mod_actual_mark

https://github.com/jiscdev/analytics-udd/blob/master/udd/student_on_assessment_instance.md#assess_actual_mark

Many Thanks

Rob

**Comment by wilmTap** [comment]
There were a couple on AGREED_MARK in student_on_a_module_instance and ASSESS_AGREED_MARK in student_on_assessment_instance as well.

All fixed now in 1.3.

**Comment by robwynj** [comment]
Thanks Wilbert - so all are now 0-100 :) Ideal - useful and we can get into the UDD HT2 API validation :)

Many Thanks

Rob
