### ISSUE TITLE
SoCI - COURSE_LOCATION should be OPTIONAL?

### ISSUE THREAD

**Issue by robwynj** [jiscdev/analytics-udd#68]
Dear All,

COURSE_LOCATION should be optional - would also make sense too as MODULEINSTANCE.MOD_LOCATION is already optional.

https://github.com/jiscdev/analytics-udd/blob/master/udd/student_on_course_instance.md#course_location

https://github.com/jiscdev/analytics-udd/blob/master/udd/module_instance.md#mod_location

Out of interest, should COURSE_LOCATION be at COURSEINSTANCE level anyway.

All up for discussion!

Many Thanks

Rob

**Comment by craig-petch** [comment]
Hi Rob, agree with it being optional, not everyone will/want to report this.

We could move it to course location so to be consistent with module location and module instance. It may also work better for any changes to location over a time.  

Craig

**Comment by robwynj** [comment]
Yes, totally agree :)

Thanks Craig,

Rob

**Comment by wilmTap** [comment]
Moved and made optional in 1.3

Thanks!

**Comment by wilmTap** [comment]
Moved COURSE_LOCATION back to Student on Course Instance and made optional.
