### ISSUE TITLE
Student Course Membership - WITHDRAWAL_REASON & WITHDRAWAL_DATE - OPTIONAL?

### ISSUE THREAD

**Issue by robwynj** [jiscdev/analytics-udd#69]
Hi,

Again, should these fields be optional - IMHO yes. Comments please - or default/ indicative option codes (or a default date entry eg 2199-12-31) should be specified in UDD/ API, for validation purposes...

https://github.com/jiscdev/analytics-udd/blob/master/udd/student_course_membership.md#withdrawal_reason

https://github.com/jiscdev/analytics-udd/blob/master/udd/student_course_membership.md#withdrawal_date

Many Thanks

Rob

**Comment by arc12** [comment]
definitely optional.
a student who has not withdrawn would have NULLs for both these fields.

for the case where a student has withdrawn, at least one of these MUST be populated and both SHOULD be populated if the data is available.

Adam

**Comment by robwynj** [comment]
Spot-on - as thought :)

Thanks Adam - hope you're well, not seen you in ages!

Cheers

Rob

**Comment by wilmTap** [comment]
WITHDRAWAL_DATE was deleted in 1.3 as part of resolving issue #51.

I made WITHDRAWAL_REASON optional, and NULL was already there.

Cheers

**Comment by robwynj** [comment]
Thanks Wilbert :)

**Comment by wilmTap** [comment]
WITHDRAWAL_DATE is back for v1.2.4, but optional
