### ISSUE TITLE
STUDENT_ON_MOD_INSTANCE and course withdrawals

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#7]
Use of STUDENT_ON_MOD_INSTANCE for students who have withdrawn from the parent course should be documented. e.g. that records remain in this case (both completed and aborted module instances). This is probably assumed, but clarity saves the day!

I assume code=4 for MOD_OUTCOME covers the case of aborted module instances arising from course withdrawal (and possibly other reasons).

**Comment by robwynj** [comment]
Hi Adam,

We could give guidance to map (or we do it ourselves during transformation, mmm) to MOD_OUTCOME = 4 where applicable - based on the obvious determinants of STUDENT_ON_COURSE_INSTANCE.WITHDRAWAL_REASON and/ or WITHDRAWAL_DATE - on basis of these BOTH being populated of course (not  NULL) -  but we still store/ receive actual  MOD_OUTCOME where not NULL. 

FYI - STUDENT_ON_MOD_INSTANCE.MOD_OUTCOME = NULL maps to 6 (default mapping, for population with valid code).

Kind Regards

Rob

**Comment by wilmTap** [comment]
superceded by #24
