### ISSUE TITLE
Field-level Extensibility

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#74]
While I acknowledge extensibility can be a double-edged sword and I'm very supportive of the idea of a standardised UDD, I can forsee situations where work with an institution might be constrained if we do not have a mechanism to extend the data which is being moved around. I mean the addition of fields to existing UDD entities that are pure attributes rather than either extending with new entities or relational keys. It would be convenient if the infrastructure could support these "off-spec" fields, and to do so in a way that is clear and expresses real intention rather than an accident in data provision with random field names...

A proposal, for discussion:
Consider a field name prefix (e.g. "E_") to denote an extenstion field (scoped as outlined above).
LRW would accept up to a sensible number of these so long as the names are unique in the entity/table data sent in a transaction (and maybe with specified bounded length) but would apply no validation, storing the data as an opaque string. The same approach could be used for experimental UDD features.

Not urgent, but if we reach consensus then...

Adam

**Comment by wilmTap** [comment]
Namespaces!

But seriously, in order to avoid collisions, I think we'd need to assign a prefix for everyone in a position to add extensions. Otherwise, you'd have to coordinate who uses what term, which kind of defeats the purpose.

**Comment by arc12** [comment]
Maybe namespaces, but maybe not. I agree we'd need to discuss the practicalities; the issue statement is a starter...

To some extent, the institution/tenant provides a kind of namespace.

An alternative might be extension registration.

Adam

**Comment by wilmTap** [comment]
Needs @ht2 feedback

**Comment by andrewhickey** [comment]
A possible solution would be to allow a key where anything could be set then consumers could set their own data without any need for further updates.

```
STUDENT_ID,
extensions: { // any data can go under here e.g. namespaced by consumer
  tribal: { some data },
  unicon: { some data },
  extension1: "data1"
}

```
alternatively we could have editable keys per consumer with freeform data inside. This would stop people accidentally overwriting others data but would need an API update every time we added a new API user.

```
STUDENT_ID,
tribal: { // any data can go under here
  tribalext1: "tribalext1",
  tribalext2: "tribalext2"
},
unicon: { 
  uniconext1: "unicondata1",
  uniconext2: "unicondata2"
}
```

Happy to go with either solution

**Comment by arc12** [comment]
Could we discuss this in the context of 1.3 please.

It may be that this is not so much a UDD specification matter as a LRW behaviour issue.

I don;t want to go mad on extensions, but the facility to occasionally add a small extension is quite useful and a good pathway to test ideas for innovation without tainting the main spec. For example, other issues talks about progression codes, sandwich years, etc; it would have been helpful to be able to slip these into the LRW.

**Comment by alanepaull** [comment]
With this issue, and with #77, I suggest that we have a separate discussion (Skype?) with @michaelwebbjisc, @robwynj and relevant technical folks (HT2?).  I'm unsure of the implementation effects (or what is currently implemented) or practicalities in respect of this issue and the system identifiers for staff and students.

**Comment by alanepaull** [comment]
From Monday 5 Dec call:

Separate discussion between @michaelwebbjisc / @leebaylis / @robwynj / HT2 folks to be arranged.

**Comment by arc12** [comment]
A note on practical matters from our side:

Our processing relies on tabular data.
Most simple, then, is a plain list of attributes in the response, with extensions and core UDD side-by-side.
JSON in the LRW shouldn't be a problem, but we'd want to get rid of JSON structures at the earliest point. So long as its done in a way we can apply a projection in the query, I'm fairly neutral to the option chosen. This would require some rework, however, as we currently only project-out, rather than project-in.

**Comment by alanepaull** [comment]
Monday 16 January 2017:  These extensions could be both vendor and institution specific.  It was felt that, at this stage, prescribing these in the UDD would be off-spec for the UDD, and that we should limit the UDD to a description of how to do the extensions, while including them in LRW functionality.  To be discussed further with HT2.

**Comment by alanepaull** [comment]
I have drafted a description: https://github.com/jiscdev/analytics-udd/blob/v1.3/utilities/field_level_extensions.md.
This is a very drafty document, and contains a number of questions that I think we need to clear up:
1) This data would not be validated through normal UDD validation routines, as it is JSON format data. What validation applies, if any?
2) Is the UDD entity name from the md file OK for identifying the entity, or do we need the endpoint?
3) Could we have a realistic example please?

I also note @arc12's wish to get rid of JSON structures, if possible, whereas this process may entrench them.

Alan

**Comment by arc12** [comment]
I move to exclude from v1.3.0, defer to later "dot" release
Should be part of a discussion on the LRW replatforming for UDD data. i.e. a non-spec issue at the moment

**Comment by alanepaull** [comment]
Monday 13 February: agreed to include this in v1.3.0, if possible.

I've drafted an MD file for this, as a result of our discussions; please see https://github.com/jiscdev/analytics-udd/blob/v1.3/extension.md.  This is very much a draft, and open to comment and re-writing as necessary.  I've currently written is as having a concatenated PK, but a single PK could be created if preferred.

There's also a snippet in the README:

_Extensions:  There is provision for data extensions at the level of property (in other words, "field-level extensions"). Although not strictly part of the UDD, a separate entity is provided and described at extension.md._

1 question:  Do we need a central vocabulary of extension labels, or are these to be maintained by vendors / institutions?  They won't be part of the UDD, but could still be controlled, potentially, as long as that doesn't get in the way of practical usage.  I think we probably don't need this, but we did discuss the danger of clashing property values.  I don't think we came to a conclusion (but I may be incorrect).

**Comment by arc12** [comment]
On the question:
I think the extension labels should not be registered but should explicitly be under the control of the entity identified by VENDOR, which SHOULD be registered and controlled by Jisc. (They may also maintain their own set of extensions with VENDOR = "Jisc" and, therefore, control the values of PROPERTY_NAME when VENDOR == "Jisc")

Some other queries/comments:
1. Is VENDOR the best word?
2. I'm cautious about "PRIMARY_KEY" (as a field name and in the notes) because of the risk of confusion. We've been using PK to designate something more natural so far, whereas we're now introducing a surrogate PK in the interest of making the data management easier. A more explicit name "SURROGATE_KEY" or even "REF_KEY" might help to keep casual readers and conversations on the right track.
3. The anomaly of "student_on_a_module_instance" having "_a_" in the middle glares at me. There is probably some assumption of this as a file name in the Jisc process, but once we've started with using it in the extensions, we'll have built more of a barrier to change. Should we harmonise now?
4. Documentation on PRIMARY_KEY should clarify that the key refers to the ENTITY.
5. I think PROPERTY_VALUE should be a string, with a note that it should be parsable to whatever definition the VENDOR has for the property. I imagine it will be stored as a string in the LRW, so stringification and parsing should be clearly the responsibility of the data source and sink.
6. ALthogh I don't see this as implying change in the documentation, I do think the implementation in the LRW will require care. In particular, we need to have clear and simple logic for how updates propagate. For example, if the value of an extension changes, I suggest that the parent entity should show a change in the update-date as well as the record in the extensions.

**Comment by alanepaull** [comment]
Control of extension labels: I agree.  I'd rather NOT control these in the UDD.  Control by the organisation identified by VENDOR seems appropriate, especially as we have a concatenated key here, so I think there's no conflict between identical labels.

1.  I think this should be vendor or institution.  Roy suggested that an institution might well want to control these.  How about ORGANISATION, or if that's too long, ORG?  And define this as normally a vendor, an institution or Jisc, with the role of controlling 'their' extensions.

2.  Point taken.  REF_KEY gets my vote, for the reason you give.

3.  Hmmm.  There was a great deal of resistance earlier to changing names for things already in use.  If there's consensus, I'd be happy to do that, but...

4.  "Holds the unique single primary key identifying the record in the UDD entity to which the extension applies."

5.  That seems very reasonable, as long as there aren't any practical difficulties with typing in the database, or at least that must be taken into account on implementation.

6.  I agree.  This needs to be made clear when we've finished agreeing everything for v1.3.0, and when the DB is implemented.

Thanks for all those points, @arc12.  I'll modify the MD as above.

**Comment by arc12** [comment]
Re "Hmmm. There was a great deal of resistance earlier to changing names for things already in use. If there's consensus, I'd be happy to do that, but..."

... and I was one of those resisting (also in the context of the LRW API endpoint URLs)! It just shouts ANOMALY! I see a gradation of impact here:
- API endpoint changes = worst
- file name convention = lowish
- canonical entity names = fairly minimal

**Comment by alanepaull** [comment]
I'll leave this last one (student_on_**a_**module_instance) for now, till we get consensus.

**Comment by alanepaull** [comment]
Re ORGANISATION: this is intended to be the vendor, the institution or Jisc.

If this is to be validated, we'll need a table of valid organisations, for example "Tribal", "University of Gloucestershire", "Jisc", and so on.  I'm happy to construct this, if someone can attempt a raw listing.  My first guess is:  all vendors currently involved and supplying data, all institutions currently involved, plus Jisc.  Then we can add new folks when they join up.

**Comment by arc12** [comment]
Not necessarily a spec issue, but a "good practice" IMO is the avoidance of extension proliferation, and especially extensions for which there is no existing or planned utilisation. To extend this: people who are preparing data at the source end should not willy-nilly create extensions with the expectation that they will magically appear in dashboards, apps, etc...

**Comment by alanepaull** [comment]
Monday 27 Feb meeting:  We agreed that single field primary keys for the entities with composite keys would consist of a concatenation of the components of the composite key separated by a tilde.  The order of the components must be the same as in the MD file defining the entity.  This decision, including the use of the tilde as a reserved character, to be documented.  Where this new primary key is not provided by the data supplier, the LRW loading mechanism will create it.

For example: student_on_course_instance has a single field primary key STUDENT_ON_COURSE_INSTANCE_ID.  This consists of:

'''xxxxxx~yyyyyy

where xxxxxx is the STUDENT_COURSE_MEMBERSHIP_ID and yyyyyy is the COURSE_INSTANCE_ID.  The tilde is a reserved character that splits the components.  Note that the combination of STUDENT_COURSE_MEMBERSHIP_ID and COURSE_INSTANCE_ID is a uniqueness constraint.

**Comment by alanepaull** [comment]
Note: the entity student_id_map does NOT have a single primary key.

**Comment by ryansmith94** [comment]
Can someone here please answer [my questions](https://github.com/jiscdev/analytics-udd/issues/169#issuecomment-284460136) on #169?

**Comment by alanepaull** [comment]
The outcome of this issue has been revised and updated.  Please see #169 and #187.
