### ISSUE TITLE
Canonical names for entities

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#76]
Folks -
at present, I don't think we have specified canonical names for the entites/tables. We have names like "student on a module instance", either in text or as markdown file names. There is some variation but nothing un-guessable.

Data in various places and the LRW API has made assumptions about lexical content of file names and URI paths, and these are arguably "off-spec" matters, but I wonder whether we should document canonical entity names. Actually, I'd be inclined not to leave path/file naming "off-spec" because consistency will be practically useful.

Adam

**Comment by wilmTap** [comment]
markdown file names across the board.
