### ISSUE TITLE
System identifiers for students (and staff?)

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#77]
This issue raised with the understanding that the current approach is a stop-gap with the merit of being simple in the simple case.

A minor issue is that 'VLE_ID' [0..*] is an oddity in being multiple. In practice, this means we'd break it out to a separate table. I imagine that a long-term solution to ID resolution between application event stores logged to the LRW (which will not only be VLEs) would entail a separate table, so I see this as "coming out in the wash".

The main weakness I see with the current approach is that the values in VLE_ID are not "namespaced" according to the application to which they belong. Things will break if two applications use the same identifier for different students. IMO this needs attention in the 1.3-1.4 horizon, before we have to start inventing work-arounds.

I suggest we also standardise on one resolution table, and avoid multiple idents with unique names: DASH_SHIB, APP_SHIB, VLE, ...

Addition of application ids for staff is conceivably a separate issue.

Aadm

**Comment by wilmTap** [comment]
We've talked in the past about having a general ID resolution entity for students to all LRW entities. It was deferred in favour of the solution we have now, but we could re-introduce it. 

The question is the scope: once we have an ID resolution entity, we could, if we wanted to, refactor a lot of things around student_membership. It seems more of a 2.0 to me, in any case.

**Comment by arc12** [comment]
Also relevant to this issue, and something to consider when addressing it is
USERNAME on STUDENT_ADDITIONAL.

Q1: is this of practical utility in the ID lookup scenario? Could this be pulled into the xAPI statements when an ISO is in use?
Q2: should STAFF have an equivalent?

**Comment by wilmTap** [comment]
Needs a proposal, @wilmTap to work up

**Comment by arc12** [comment]
could we put this on the 1.3 label please.
Even if we merely represent the same information in a new structure in the first instance, I think we really need to future-proof ourselves.

Straw man proposal:
add new entity: STUDENT_IDENTIFIER
fields: STUDENT_ID, DOMAIN, IDENTIFIER

STUDENT_ID = PK in STUDENT
DOMAIN = URL of service (e.g. VLE home, SHIB IdP) or reserved word (e.g. HUSID, ULN)
IDENTIFIER = identifier in the domain for this student

Uniqueness constraint: all three columns

We could use the same pattern for staff: STAFF_IDENTIFIER...

Note: in practice, I would expect data for different domains to come into the LRW from different sources. This seems to match a separated STUDENT_IDENTIFIER collection better than including various identifiers in STUDENT.

**Comment by alanepaull** [comment]
I think we'd need to check with ht2 what's in the LRW.  It may be that it tallies with what's available there, so it wouldn't be too much of a strain for 1.3.  I've added Andrew and James in as assignees and changed the label to 1.3.

**Comment by alanepaull** [comment]
From Monday 5 Dec call:

cf. Adam's comment on 3 Nov.  A primary purpose for this is to enhance efficiency of real-time querying .  Try to avoid a new entity if possible.

**Comment by arc12** [comment]
could we clarify the querying requirement?
what are the query terms ie the WHERE? an identifier I guess, but is it the UDD STUDENT_ID or the "foreign" id?
what are the sought facts i.e. the SELECT?

I should add that our scenario is one of efficient batch processing of id mapping. e.g. given a shed-load of xAPI statements from system X, to determine the UDD STUDENT_ID for each. I would expect this to require the creation of an index (in our code) on the non-UDD identifier in both xAPI and the udd-id-mapping data.

**Comment by alanepaull** [comment]
Monday 16 January 2017: To be discussed further with @andrewhickey.  Michael to comment on possible solution, using JSON key/value sets as a structured property to replace the current ID.

**Comment by arc12** [comment]
I think it would be good to address this in v1.3.0, although it has been difficult to get to consensus so far.
Given the LRW replatforming for UDD data, it might be timely to change the strategy for these mapping identifiers.

**Comment by robwynj** [comment]
Optional fields, for both - ?

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; APMG PRINCE2 & APMG AGILE Certified Practitioner

Senior Data & Analytics Integrator - Jisc UK Learning Analytics
Cluster Lead – Jisc Data & Analytics Service

email/ skype: rob.jones@jisc.ac.uk<mailto:rob.jones@jisc.ac.uk> mobile: 07468 727040  web: www.jisc.ac.uk<http://www.jisc.ac.uk>

**Comment by alanepaull** [comment]
Monday 13 February: We agreed to introduce a new UDD_STUDENT_IDENTIFIER entity that will contain STUDENT_ID, DOMAIN, IDENTIFIER, along the lines of @arc12's November 3 comment above.

**UDD_STUDENT_ID** is the UDD identifier for the student.  I've added the UDD prefix to differentiate it clearly from an institution-based ID.  I'm a little unclear about the impact of this on student.md#student_id, which is currently defined as "The institution's own unique identifier of the student."  If this student_id is to be left "as is", will it need a DOMAIN in the student entity?

DOMAIN is the system that's using its own student id, for example a VLE or SRS.  I think possible values for our controlled list might initially be:

- HUSID
- ULN
- VLE_1
- VLE_2
- VLE_3
- SRS_1
- SRS_2
- SRS_3

any others for now?

IDENTIFIER is the local id for the student, as used in the above DOMAIN.

**Comment by arc12** [comment]
I think the STUDENT.STUDENT_ID is the master identifier, and I would expect that this will always be the student record system identifier (although I don't see that this should be a requirement, it is a practical reality and will ensure that the student identifier which appears in the dashboard is the one which users would expect).

i.e. I expect that the new student identifier lookup (STUDENT_ID_MAP ??) information is always a mapping from the identifier in some "other" system back to the master identifier in the SRS. So: we don't have a domain for SRS.

**Comment by alanepaull** [comment]
That looks good to me.

So we could have (instead of my previous version):

New entity: STUDENT_ID_MAP (it does what it says on the tin), with STUDENT_ID, DOMAIN and IDENTIFIER.

STUDENT_ID is the master identifier for the student, identical to student.md#student_id, and drawn from the student record system in practice.

DOMAIN is the system that's using its own student id, for example a VLE. I think possible values for our controlled list might initially be these.  Useful to include both HUSID and ULN I think.  Maybe UPN for FE?

HUSID
ULN
UPN
VLE_1
VLE_2
VLE_3

IDENTIFIER is the local id for the student, as used in the above DOMAIN.

**Comment by alanepaull** [comment]
I've created a student_id_map MD file on this basis.
If we agree, then we can close this issue.

**Comment by alanepaull** [comment]
The property VLE_ID in the student entity is currently set as 0..*.  This makes it cumbersome to use.  We agreed to change this to 0..1, but to enable multiple VLE_ID identifiers in the student_id_map entity. The entry for VLE_1 in the student_id_map should appear in student.VLE_ID.

This may raise a wider question about repeated data, and the danger of inconsistency.  We agreed (quite quickly) that it was OK to repeat identifier data in student and in student_id_map.  However, as we didn't really discuss it much, I would like to check that (i) this is what we want, and (ii) which identifiers should be covered.  The implications are that we would repeat ULN, HUSID, VLE_ID (for the main VLE), APPSHIB_ID (??), USERNAME (??) - all of these are in student, and are at least candidates for inclusion in student_id_map.  I guess that for performance reasons we might want to repeat them, but I felt it's better to check now, rather than regret later.  Please give a view as to which ones should be included in both student and student_id_map.

**Comment by arc12** [comment]
Good to raise this Alan. I think we may have been hasty. This is not responding to your question, I think but it is a thought which arose...

There are implications for situations where there really is more than one VLE in play, but we have not explored them. Maybe it would be better to leave this as a possiblity which the structure affords but which is not currently permitted.
How would we map activity data to students/modules/courses in UDD-land?
The issue I see is that we have not documented how we would resolve VLE_1/2 or whatever to some data in the statements held in the LRW. I imagine we would use actor.account.homePage. In which case, I suppose that DOMAIN should be that URL and not something opaque like VLE_2, which would require another look-up to be created.
In the short term, I think we live with a reserved word like "VLE_ID" and bear in mind the multiple-vle scenario for the future. At least the new data structure enables us to broaden the range of applications.

(incidentally - I see a typo on actor.account.homePage for the vle resource view statement template - Module-View.md)

As to your question: I am not particular. Actually, I can see logic for leaving the ULN and HUSID only in STUDENT, and putting only those software-centric ones in the new mapping entity, with the expectation that most would be subsequently deprecated from STUDENT.

**Comment by alanepaull** [comment]
Having thought about this a bit more (and drafted a different comment!), I'm now thinking that VLE_1/2 and so on is a hostage to fortune.  Could we go for the, possibly quick?, solution to replace VLE_1/2 in student_id_map with the VLE's URL, as you've also suggested?  This potential solution means that we don't have to be definitive about the system the URL identifies - it could just be a domain with a student identifier.  It also gives us a look-up at least, and should match with xAPI statements (we could be explicit about that).

This sounds to me like a better solution than a hand-wave at "VLE_1", "VLE_2", and so on.

I'm not particularly worried about repeating data, at least in the short term.

**Comment by alanepaull** [comment]
Monday 13 March: Agreed to replace VLE_1 and so on with a URL identifying the system.  This should be OK for v1.3.0.  If there are difficulties, we can amend it for v1.3.1.

**Comment by alanepaull** [comment]
Monday 3 July 2017: Agreed to review in relation to v1.4

**Comment by leebaylis** [comment]
Gloucestershire are asking what is supposed to go in DOMAIN and I am not sure from the discussion above -- is it a URI identifying the platform (e.g. https://en.wikipedia.org/wiki/Moodle, or http://moodle.org) or is it a URI identifying the specific instance of the platform as in use at the institution (e.g. https://moodle.glos.ac.uk)

**Comment by leebaylis** [comment]
I didn't unnasign andrew? I've put him back!

**Comment by ht2** [comment]
Hey guys, unfortunately Andrew has moved onto to pastures green(er?). I would presume that when he left this repo it auto unassigned him, and its gone and blamed you for it Lee!

**Comment by alanepaull** [comment]
@leebaylis: The purpose of DOMAIN is for the institution to be able to identify the platform that the individual person is using. In the vast majority of cases, I suspect it won't matter whether it's a generic identifier for the platform (moodle, rather than a library system). However, in case the provider has more than one platform of a given type, I would go with the specific instance of the platform (https://moodle.glos.ac.uk in your example).

**Comment by leebaylis** [comment]
thanks!
next question from gloucs -- are there any conventions whereby they can bypass creating lengthy tables here if they use the same identifier for all systems -- e.g. does absence of a system DOMAIN in this table imply the UDD STUDENT_ID is in use on said system?

**Comment by alanepaull** [comment]
DOMAIN is mandatory in this table, so its absence implies that it won't be loaded into the Learning Data Hub :).

This table is specific to the lookup of student IDs, on the understanding that there may be cases where a there's a different internal student ID for a different system, for example an SRS might have a different ID from the VLE or a library system. If the student IDs are always the same, I don't know whether this table is important. This would be a question for @ht2 or @robwynj, I think, as they will have a better appreciation of implementation issues.

**Comment by arc12** [comment]
Our processing code allows for the case where the ids are already the same, i.e. do not require mapping, simply by not doing any mapping. Actually, we don't yet yse this entity but still rely on the attribute on STUDENT, but the logic is the same.

Most efficient, operationally, would be to NOT use this entity when the learning system uses SRS ids.

**Comment by alanepaull** [comment]
Monday 19 March 2018: no evidence that student_id_map is being used operationally. Agreed to leave the facility in place in case it is useful in the future, but to close the issue.
