### ISSUE TITLE
Multiple cardinality issues Student on Module Instance

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#79]
I think the following are in 1.2.4 and master, but are not correct. Should be optional IMO:
MOD_GRADE [1]
MOD_END_DATE [1]
MOD_AGREED_GRADE [1]
MOD_CREDITS_ACHIEVED [1]
MOD_COMPLETED_ATTEMPT [1]

**Comment by wilmTap** [comment]
They've been taken from [the constraints expressed in v1.2.3](https://github.com/jiscdev/analytics-udd/blob/e19a15b52d6be09a0b3659280d6b41287556c789/udd/student_on_a_module_instance.md#mod_completed_attempt)  That doesn't necessarily mean they're right, though; happy to change them.

**Comment by wilmTap** [comment]
See issue #78

**Comment by wilmTap** [comment]
They're all in my issue #78 list for optionality, apart from MOD_END_DATE. Surely that one's known?

**Comment by wilmTap** [comment]
Agreed; leave MOD_END_DATe as is
