### ISSUE TITLE
Table to match VLE courses to Modules

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/analytics-udd#8]
We need to be able to match courses as defined in the VLE to modules (or module instances - need to make a decision on which).

**Comment by arc12** [comment]
While I would expect module instances to be very common, we can be sure people will use Moodle in a variety of cross-cutting ways.
I think we should be guided by the data we can get. What mapping data can institutions actually provide us with?

**Comment by robwynj** [comment]
Hi Michael,

I would expect that VLE data would be linked per module instance. Will be interesting to see what the Moodle data from Exeter has shown up, and what Bb historic log information from Aberystwyth describes.

Kind Regards

Rob

**Comment by robwynj** [comment]
Obtaining mdl_course from ULCC today, for Exeter Moodle.

Rob
