### ISSUE TITLE
Cardinality issues - Student on Assessment Instance

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#80]
ASSESS_AGREED_GRADE [1]
ASSESS_ACTUAL_GRADE [1]

These are at odds with the MARK equivalents and necessarily NULL for assessments not yet graded.

Adam

**Comment by wilmTap** [comment]
As in #79, the constraints were inherited from v1.2.3 and earlier, and it touches on the 'explicit NULL versus missing property' question raised in #78

**Comment by robwynj** [comment]
Good point ala HESA / XML. Up to the floor to decide!

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; PRINCE2, AGILE & SCRUM Certified Practitioner

Consultant – JISC Special Projects

email/ skype: robert.jones@jisc.ac.uk<mailto:robert.jones@jisc.ac.uk> mobile: 07976 508860

**Comment by wilmTap** [comment]
Both on the optionality hitlist in issue #79
