### ISSUE TITLE
STUDENT_COURSE_MEMBERSHIP_SEQ needs clarification

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#82]
There are several issues which render the description imperfect in clarity.

References to course instance are not relevant in a description of fields the SCM entity but appear in the definition of thie SEQ field: "The institution's own unique identifier for the student and the course instance they are assigned to.".

Additionally:
There are references to this being an identifier, and the type is string but I feel it really should be a sequence code. At the very least, conformity to the UDD should guarantee that I can sort this and get the correct ordering; its not just an identifier. I would actually prefer this to be an integer sequence which gives the order to a series of SCM records for the same student.

Being able to order course memberships is quite important in practice, so I'd like to get this field tidy!

Adam

**Comment by wilmTap** [comment]
Craig to supply text.
