### ISSUE TITLE
_RESULT fields for student on module and assessment instances have conflicting description

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#83]
"Code 3 is applied in all cases where the outcome is either not known (yet), or doesn't apply; because a student withdrew or deferred, for example." but the table of code values contains a code 4 for deferred.

Attribute descriptive text is also inconsistent with the table.

It might be better to avoid code 4, and to signal deferral or withdrawal by other mechanisms at the instance or course membership level.

We might also want to consider the case where the result is not known but should have been. So, codes for:
- passed
- failed
- not yet assessed
- assessed but result not known

I think the desciption should also be clear whether the case where initial marks are recorded but not the agreed (exam board) mark. Is that still a code=3 situation? I think the answer is "no", but the answer is less important than knowing one way or the other IMO.

Adam

**Comment by wilmTap** [comment]
So the code table should be changed tp:

1. Passed
2. Failed
3. Not yet assessed
4. Deprecated (was: deferred)
5. Assessed but result not known

Then the note should be expanded to say only agreed marks count.

I think that would just about count as a backwards compatible change to the model.

**Comment by wilmTap** [comment]
If this is agreeable to everyone, could we also get some Welsh translations, please, @robwynj :-) ?

**Comment by wilmTap** [comment]
Agreed:
1. Pass
2. Fail
3. Not known
4. Deprecated (was deferred)
