### ISSUE TITLE
ENTRY_QUALS code list error?

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#84]
> J31	(Other) Qualification at level 5			
> J31	(Other) Qualification at level 5 or above (DEPRECATED SINCE 01/08/2013)		J32	5 

Two codes J31

should the second one be J32?

or should the note about deprecation be a note, and not a table entry.

This causes me a practical problem in that I'm requiring all codes are unique before we'd use the code list for validation/quality-checks,

[added: C80 duplicated also]

**Comment by robwynj** [comment]
Think this revolves around the work I started to do on unification with FE codeset (England ILR).

Rob

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; PRINCE2, AGILE & SCRUM Certified Practitioner

Consultant – JISC Special Projects

email/ skype: robert.jones@jisc.ac.uk<mailto:robert.jones@jisc.ac.uk> mobile: 07976 508860

**Comment by arc12** [comment]
Rob - same problem with DISABILITY1

> 53 	A social/communication impairment such as Asperger's syndrome/other autistic spectrum disorder 		53 	15
> 53 	A social/communication impairment such as Asperger's syndrome/other autistic spectrum disorder 		N/A 	1 

which also has four lines with code 00

**Comment by arc12** [comment]
I think it would be *highly desirable* for the code in these tables to be a unique value (per table). This means we can use the codes to look up the Welsh/English label to apply.

BTW: I've got a short bit of code to read the markdown and generate JSON versions of the code lists, using the code as a key-name. These duplicate keys break it! One thing which would improve matters is to change all the headers for the codelist tables so that the one which contains the code is labelled with the attribute name it applies to. That means I can write JSON with the attribute name as a key in an associative array rather than just emitting a list.

I'm happy to post the code for this extraction.

Adam

**Comment by arc12** [comment]
A further suggestion: omit "NULL" from the code list. I think this is logically-speaking a separate fact about the optionality of the data rather than a code. It (NULLs here) also causes me to have to work around the fact that the pandas library turns columns with nulls into a floating point data type (sigh).

**Comment by arc12** [comment]
Sample JSON code lists extracted from markdown (missing student lists, ENTRY_QUALS hacked as per opening ussue statement)
[extracted_codelists.zip](https://github.com/jiscdev/analytics-udd/files/329909/extracted_codelists.zip)

**Comment by arc12** [comment]
see PR #89

**Comment by wilmTap** [comment]
Agreed
