### ISSUE TITLE
Typing of code-list (categorical) attributes

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#85]
At present we have some integer and some string data types on fields with specified code lists.

In the interest of processing consisency, and to reduce the risk of mismatches when codes are treated as numbers and strings at different times, it would be better to always have a data type of string.

I suggest the spec is modified accordingly, and that the LRW should cast everything to string except for what is specified as an int or decimal.

**Comment by wilmTap** [comment]
It'd be interesting to hear what others think. It certainly sounds a v1.3 change to me.

**Comment by wilmTap** [comment]
Agreed in principle for v1.3

**Comment by arc12** [comment]
This will also help with consistency of coding missing data in categorical fields as we move between different platforms, for which the representation of "null" may differ if we have integers, but an empty string should be nice and consistent.

**Comment by alanepaull** [comment]
Items with Int format in coded lists in 1.3 are:

student.LEARN_DIF
student.DISABILITY1
student.DISABILITY2

Changed to String (256).

**Comment by robwynj** [comment]
Well spotted - had this issue today as per observations between myself and @huwrobertsjisc using the new validation tool.

Many Thanks
