### ISSUE TITLE
Include COURSE_AIM code list in explicit form

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#86]
Currently COURSE_AIM is specified by reference to HESA + some extensions in note form.

Problems:
- will need to unify with FE
- no Welsh labels
- won't be picked up by my code-list extaction script.

**Comment by arc12** [comment]
html table attached
[course_aim_table.txt](https://github.com/jiscdev/analytics-udd/files/330204/course_aim_table.txt)

**Comment by wilmTap** [comment]
In PR #92

**Comment by wilmTap** [comment]
Agreed
