### ISSUE TITLE
Request for CAMPUS - APPROVED (for UDD 1.2)

### ISSUE THREAD

**Issue by robwynj** [jiscdev/analytics-udd#9]
Suggested by Aberystwyth University - related to HESA SR spec. for CAMPID

https://www.hesa.ac.uk/index.php?option=com_studrec&task=show_file&mnl=14051&href=a^_^CAMPID.html

"Should the model cater for students from alternative locations. We have a branch campus and I assume there may be other partnerships in the future. So, internally we have to differentiate between these students to take into account different rules for different locations."

Suggest for UDD 1.2 (in "Student on Course" instance)

**Comment by arc12** [comment]
Rob - this is also relevant for our Exeter pilot, with course delivered at two sites: Streatham and Penhryn

The courses are currently separately coded at COURSE_ID level in our data extracts.

There are (at least) two perspectives on this, both of which the UDD should support:
- presentation of learning analytics results
- possible relevance to predictive models

So: yes, I think the model probably should encompass campus/site, taking account of both those perspectives. This will involve, I think, working through scenarios for the presentation aspect, to make sure that student-on-course-instance is the most robust place to capture this, to give us the kind of institutional structure navigation which users will expect.

[incidentally, we've also discussed the possible benefits of refactoring student-on-course-instance, but we'll explain this in a future communication]

**Comment by robwynj** [comment]
Great - as far as the purpose in concerned, the need is there in one if not two ways, so we'll put this in for 1.2.

**Comment by wilmTap** [comment]
Added a patch to #15 

I've assumed it was compulsory where it applies, and I've left it a 256 character string (HESA's 1 character string seemed a little mean)
