### ISSUE TITLE
Clarification YEAR_COM

### ISSUE THREAD

**Issue by arc12** [jiscdev/analytics-udd#93]
Problem statement: the current description may be interpreted differently by different people when mapping SRS data to the UDD, meaning that down-stream processing is compromised.

Clarify in the description whether this refers to:
- the calendar year of the student's commencement (in which case, how is this different to the year from student-course-membership start date), 
- the calendar year of the start of the first course instance of the course which the student joined.
- an academic year for either of the above.

Adam

**Comment by wilmTap** [comment]
Agreed:

Deprecate YEAR_COM and make it optional
