### ISSUE TITLE
SCM: COURSE_MARK - currently mandatory (should be optional?) UDD 1.2.4

### ISSUE THREAD

**Issue by robwynj** [jiscdev/analytics-udd#95]
We must have discussed this before, but wanted to put it out there again.

Also, have noted as UDD API issue, in that 0 (zero) is not accepted as a valid mark. I assume this is an API issue, as marks can be 0-100!

Kind Regards

Rob

**Comment by robwynj** [comment]
Hi Wilbert,

Can we confirm if this is now optional, for UDD 1.2.5 please :)

Many Thanks

Rob

**Comment by wilmTap** [comment]
Ah; I focused on the 0-100 bit. v1.2.5 was merged in four days ago with all the decisions we took from 2 weeks ago.

Not to worry, though: it's in v1.2.6 now.

**Comment by robwynj** [comment]
Hi Wilbert,

What’s in 1.2.6 now – the optional part, or the 0-100 or both I assume – looks like we will be moving to 1.2.6 sooner than 1.2.5?

Cheers

Rob

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; PRINCE2, AGILE & SCRUM Certified Practitioner

Consultant – JISC Special Projects

email/ skype: robert.jones@jisc.ac.uk<mailto:robert.jones@jisc.ac.uk> mobile: 07976 508860

**Comment by wilmTap** [comment]
Hi Rob, 

The 0-100 change has been in since v1.2.4. We're on v1.2.5 now, and it is proposed that the COURSE_MARK is made optional in v1.2.6

**Comment by robwynj** [comment]
Ahh, the API doesn’t reflect this from what I can see – in 1.2.4 – discuss with HT2….

--
Rob Wyn Jones BSc(Hons) MBCS
ITIL & ISEB Certified; PRINCE2, AGILE & SCRUM Certified Practitioner

Consultant – JISC Special Projects

email/ skype: robert.jones@jisc.ac.uk<mailto:robert.jones@jisc.ac.uk> mobile: 07976 508860
