### ISSUE TITLE
SoCI: X_ fields should be optional?

### ISSUE THREAD

**Issue by robwynj** [jiscdev/analytics-udd#96]
X_COURSE_AVERAGE_MARK
X_YEAR_AVERAGE_MARK

These are currently mandatory - shouldn't they be optional (to support transactional process from HEIs).

Many Thanks,

Rob

**Comment by robwynj** [comment]
Hi Wilbert,

Can we confirm if these can be optional, for UDD 1.2.5 please?

Kind Regards

Rob

**Comment by wilmTap** [comment]
I think we probably need a discussion about who is responsible for the creation of X_ fields and how we mark that. That is: since they are derived from other properties, the providers may not need to supply them, even if we do want to make sure they are present in the LRW.

**Comment by robwynj** [comment]
@michaelwebbjisc can you comment on this - we have some X_ fields which are mandatory for the UDD, but for loading from HEIs doesn't work. Shall these be optional (all/ most of all others are anyway?).

Kind Regards

Rob

**Comment by wilmTap** [comment]
Agreed: made optional for now.
